return {
    -- FFXI internal icons, all starting with \xEF
    fire =        string.char(0xEF, 0x1F),        -- Elemental fire sign
    ice =         string.char(0xEF, 0x20),        -- Elemental ice sign
    wind =        string.char(0xEF, 0x21),        -- Elemental wind sign
    earth =       string.char(0xEF, 0x22),        -- Elemental earth sign
    lightning =   string.char(0xEF, 0x23),        -- Elemental lightning sign
    water =       string.char(0xEF, 0x24),        -- Elemental water sign
    light =       string.char(0xEF, 0x25),        -- Elemental light sign
    darkness =    string.char(0xEF, 0x26),        -- Elemental darkness sign
    atstart =     string.char(0xEF, 0x27),        -- Auto-translate, green beginning brace
    atend =       string.char(0xEF, 0x28),        -- Auto-translate, red finishing brace
    on =          string.char(0xEF, 0x29),        -- ON sign (as used in menus
    off =         string.char(0xEF, 0x2A),        -- OFF sign
    oui =         string.char(0xEF, 0x2B),        -- ON sign (French)
    non =         string.char(0xEF, 0x2C),        -- OFF sign (French)
    ein =         string.char(0xEF, 0x2D),        -- ON sign (German)
    aus =         string.char(0xEF, 0x2E),        -- OFF sign (German)
    bronze1 =     string.char(0xEF, 0x2F),        -- Mentor Rank Flag Bronze 1
    bronze2 =     string.char(0xEF, 0x30),        -- Mentor Rank Flag Bronze 2
    bronze3 =     string.char(0xEF, 0x31),        -- Mentor Rank Flag Bronze 3
    bronze4 =     string.char(0xEF, 0x32),        -- Mentor Rank Flag Bronze 4
    bronze5 =     string.char(0xEF, 0x33),        -- Mentor Rank Flag Bronze 5
    bronze6 =     string.char(0xEF, 0x34),        -- Mentor Rank Flag Bronze 6
    bronze7 =     string.char(0xEF, 0x35),        -- Mentor Rank Flag Bronze 7
    bronze8 =     string.char(0xEF, 0x36),        -- Mentor Rank Flag Bronze 8
    bronze9 =     string.char(0xEF, 0x37),        -- Mentor Rank Flag Bronze 9
    bronze10 =    string.char(0xEF, 0x38),        -- Mentor Rank Flag Bronze 10
    silver1 =     string.char(0xEF, 0x39),        -- Mentor Rank Flag Silver 1
    silver2 =     string.char(0xEF, 0x3A),        -- Mentor Rank Flag Silver 2
    silver3 =     string.char(0xEF, 0x3B),        -- Mentor Rank Flag Silver 3
    silver4 =     string.char(0xEF, 0x3C),        -- Mentor Rank Flag Silver 4
    silver5 =     string.char(0xEF, 0x3D),        -- Mentor Rank Flag Silver 5
    silver6 =     string.char(0xEF, 0x3E),        -- Mentor Rank Flag Silver 6
    silver7 =     string.char(0xEF, 0x3F),        -- Mentor Rank Flag Silver 7
    silver8 =     string.char(0xEF, 0x40),        -- Mentor Rank Flag Silver 8
    silver9 =     string.char(0xEF, 0x41),        -- Mentor Rank Flag Silver 9
    silver10 =    string.char(0xEF, 0x42),        -- Mentor Rank Flag Silver 10
    gold1 =       string.char(0xEF, 0x43),        -- Mentor Rank Flag Gold 1
    gold2 =       string.char(0xEF, 0x44),        -- Mentor Rank Flag Gold 2
    gold3 =       string.char(0xEF, 0x45),        -- Mentor Rank Flag Gold 3
    gold4 =       string.char(0xEF, 0x46),        -- Mentor Rank Flag Gold 4
    gold5 =       string.char(0xEF, 0x47),        -- Mentor Rank Flag Gold 5
    gold6 =       string.char(0xEF, 0x48),        -- Mentor Rank Flag Gold 6
    gold7 =       string.char(0xEF, 0x49),        -- Mentor Rank Flag Gold 7
    gold8 =       string.char(0xEF, 0x4A),        -- Mentor Rank Flag Gold 8
    gold9 =       string.char(0xEF, 0x4B),        -- Mentor Rank Flag Gold 9
    gold10 =      string.char(0xEF, 0x4C),        -- Mentor Rank Flag Gold 10
    info =        string.char(0xEF, 0x4D),        -- Information Icon (Blue)
}
