-- Automatically generated file: Zones

return {
    [0] = {id=0,en="unknown",ja="unknown",de="unbekannt",fr="inconnu"},
    [1] = {id=1,en="Phanauet Channel",ja="ファノエ運河",de="Phanauet-Kanal",fr="Canal de Phanauët"},
    [2] = {id=2,en="Carpenters' Landing",ja="ギルド桟橋",de="Zimmerer-Anlegestelle",fr="Jetée des charpentiers"},
    [3] = {id=3,en="Manaclipper",ja="マナクリッパー",de="Manaklipper",fr="Manaclipper"},
    [4] = {id=4,en="Bibiki Bay",ja="ビビキー湾",de="Bibiki-Bucht",fr="Baie de Bibiki"},
    [5] = {id=5,en="Uleguerand Range",ja="ウルガラン山脈",de="Uleguerand-Gbg.",fr="Chaîne d'Uleguerand"},
    [6] = {id=6,en="Bearclaw Pinnacle",ja="熊爪嶽",de="Bärenklauen-Gipfel",fr="Griffes de l'Ours"},
    [7] = {id=7,en="Attohwa Chasm",ja="アットワ地溝",de="Attohwa-Schlucht",fr="Gouffre d'Attohwa"},
    [8] = {id=8,en="Boneyard Gully",ja="千骸谷",de="Boneyard-Schlucht",fr="Couloir de l'ossuaire"},
    [9] = {id=9,en="Pso'Xja",ja="ソ・ジヤ",de="Pso'Xja",fr="Pso'Xja"},
    [10] = {id=10,en="The Shrouded Maw",ja="異界の口",de="Schleier-Schlund",fr="La Gueule Voilée"},
    [11] = {id=11,en="Oldton Movalpolos",ja="ムバルポロス旧市街",de="Oldton-Movalpolos",fr="Vieux-Movalpolos"},
    [12] = {id=12,en="Newton Movalpolos",ja="ムバルポロス新市街",de="Newton-Movalpolos",fr="Nouveau-Movalpolos"},
    [13] = {id=13,en="Mine Shaft #2716",ja="2716号採石場",de="Minenschacht #2716",fr="Puits de Mine #2716"},
    [14] = {id=14,en="Hall of Transference",ja="転移の間",de="Transferenz-Halle",fr="Salle du transfert"},
    [15] = {id=15,en="Abyssea - Konschtat",ja="アビセア-コンシュタット",de="Abyssea - Konschtat",fr="Abyssée - Konschtat"},
    [16] = {id=16,en="Promyvion - Holla",ja="プロミヴォン-ホラ",de="Promyvion - Holla",fr="Promyvion - Holla"},
    [17] = {id=17,en="Spire of Holla",ja="ホラの塔",de="Turm von Holla",fr="Aiguille de Holla"},
    [18] = {id=18,en="Promyvion - Dem",ja="プロミヴォン-デム",de="Promyvion - Dem",fr="Promyvion - Dem"},
    [19] = {id=19,en="Spire of Dem",ja="デムの塔",de="Turm von Dem",fr="Aiguille de Dem"},
    [20] = {id=20,en="Promyvion - Mea",ja="プロミヴォン-メア",de="Promyvion - Mea",fr="Promyvion - Mea"},
    [21] = {id=21,en="Spire of Mea",ja="メアの塔",de="Turm von Mea",fr="Aiguille de Mea"},
    [22] = {id=22,en="Promyvion - Vahzl",ja="プロミヴォン-ヴァズ",de="Promyvion - Vahzl",fr="Promyvion - Vahzl"},
    [23] = {id=23,en="Spire of Vahzl",ja="ヴァズの塔",de="Turm von Vahzl",fr="Aiguille de Vahzl"},
    [24] = {id=24,en="Lufaise Meadows",ja="ルフェーゼ野",de="Lufaise-Wiesen",fr="Prairie de Lufaise"},
    [25] = {id=25,en="Misareaux Coast",ja="ミザレオ海岸",de="Misareaux-Küste",fr="Côte de Misareaux"},
    [26] = {id=26,en="Tavnazian Safehold",ja="タブナジア地下壕",de="Tavnazia-Zuflucht",fr="Refuge tavnazien"},
    [27] = {id=27,en="Phomiuna Aqueducts",ja="フォミュナ水道",de="Phomiuna-Aquädukte",fr="Aqueducs de Phomiuna"},
    [28] = {id=28,en="Sacrarium",ja="礼拝堂",de="Sacrarium",fr="Sacrarium"},
    [29] = {id=29,en="Riverne - Site #B01",ja="リヴェーヌ岩塊群サイトB01",de="Riverne - Stelle #B01",fr="Riverne - Site #B01"},
    [30] = {id=30,en="Riverne - Site #A01",ja="リヴェーヌ岩塊群サイトA01",de="Riverne - Stelle #A01",fr="Riverne - Site #A01"},
    [31] = {id=31,en="Monarch Linn",ja="帝龍の飛泉",de="Königsfall",fr="Précipice du Monarque"},
    [32] = {id=32,en="Sealion's Den",ja="海獅子の巣窟",de="Seelöwen-Höhle",fr="Antre de l'Otarie"},
    [33] = {id=33,en="Al'Taieu",ja="アル・タユ",de="Al'Taieu",fr="Al'Taieu"},
    [34] = {id=34,en="Grand Palace of Hu'Xzoi",ja="フ・ゾイの王宮",de="Palast von Hu'Xzoi",fr="Grand Palais de Hu'Xzoi"},
    [35] = {id=35,en="The Garden of Ru'Hmet",ja="ル・メトの園",de="Garten von Ru'Hmet",fr="Le Jardin de Ru'Hmet"},
    [36] = {id=36,en="Empyreal Paradox",ja="天象の鎖",de="Empyreal-Paradox",fr="Paradoxe empyréen"},
    [37] = {id=37,en="Temenos",ja="テメナス",de="Temenos",fr="Temenos"},
    [38] = {id=38,en="Apollyon",ja="アポリオン",de="Apollyon",fr="Apollyon"},
    [39] = {id=39,en="Dynamis - Valkurm",ja="デュナミス-バルクルム",de="Dynamis - Valkurm",fr="Dynamis - Valkurm"},
    [40] = {id=40,en="Dynamis - Buburimu",ja="デュナミス-ブブリム",de="Dynamis - Buburimu",fr="Dynamis - Buburimu"},
    [41] = {id=41,en="Dynamis - Qufim",ja="デュナミス-クフィム",de="Dynamis - Qufim",fr="Dynamis - Qufim"},
    [42] = {id=42,en="Dynamis - Tavnazia",ja="デュナミス-タブナジア",de="Dynamis - Tavnazia",fr="Dynamis - Tavnazia"},
    [43] = {id=43,en="Diorama Abdhaljs-Ghelsba",ja="アブダルスの箱庭-ゲルスバ",de="Diorama Abdhaljs - Ghelsba",fr="Diorama Abdhaljs-Ghelsba"},
    [44] = {id=44,en="Abdhaljs Isle-Purgonorgo",ja="アブダルスの島-プルゴノルゴ",de="Diorama Abdhaljs - Purgonorgo",fr="Ile Abdhaljs-Purgonorgo"},
    [45] = {id=45,en="Abyssea - Tahrongi",ja="アビセア-タロンギ",de="Abyssea - Tahrongi",fr="Abyssée - Tahrongi"},
    [46] = {id=46,en="Open sea route to Al Zahbi",ja="外洋航路：アルザビ行き",de="Offene Seeroute nach Al Zahbi",fr="Route maritime : Al Zahbi"},
    [47] = {id=47,en="Open sea route to Mhaura",ja="外洋航路：マウラ行き",de="Offene Seeroute nach Mhaura",fr="Route maritime : Mhaura"},
    [48] = {id=48,en="Al Zahbi",ja="アルザビ",de="Al Zahbi",fr="Al Zahbi"},
    [50] = {id=50,en="Aht Urhgan Whitegate",ja="アトルガン白門",de="Aht Urhgan-Weißtor",fr="Portes Blanches"},
    [51] = {id=51,en="Wajaom Woodlands",ja="ワジャーム樹林",de="Wald von Wajaom",fr="Bois de Wajaom"},
    [52] = {id=52,en="Bhaflau Thickets",ja="バフラウ段丘",de="Bhaflau-Dickicht",fr="Futaie de Bhaflau"},
    [53] = {id=53,en="Nashmau",ja="ナシュモ",de="Nashmau",fr="Nashmau"},
    [54] = {id=54,en="Arrapago Reef",ja="アラパゴ暗礁域",de="Arrapago-Riff",fr="Récifs d'Arrapago"},
    [55] = {id=55,en="Ilrusi Atoll",ja="イルルシ環礁",de="Ilrusi-Atoll",fr="Atoll d'Ilrusi"},
    [56] = {id=56,en="Periqia",ja="ペリキア",de="Periqia",fr="Periqia"},
    [57] = {id=57,en="Talacca Cove",ja="タラッカ入江",de="Talacca-Bucht",fr="Crique de Talacca"},
    [58] = {id=58,en="Silver Sea route to Nashmau",ja="銀海航路：ナシュモ行き",de="Silberne Seeroute nach Nashmau",fr="Route de la Mer d'Argent : Nashmau"},
    [59] = {id=59,en="Silver Sea route to Al Zahbi",ja="銀海航路：アルザビ行き",de="Silberne Seeroute nach Al Zahbi",fr="Route de la Mer d'Argent : Al Zahbi"},
    [60] = {id=60,en="The Ashu Talif",ja="アシュタリフ号",de="Ashu Talif",fr="L'Ashu Talif"},
    [61] = {id=61,en="Mount Zhayolm",ja="ゼオルム火山",de="Berg Zhayolm",fr="Mont Zhayolm"},
    [62] = {id=62,en="Halvung",ja="ハルブーン",de="Halvung",fr="Halvung"},
    [63] = {id=63,en="Lebros Cavern",ja="レベロス風穴",de="Lebros-Höhle",fr="Caverne de Lebros"},
    [64] = {id=64,en="Navukgo Execution Chamber",ja="ナバゴ処刑場",de="Navukgo-Hinrichtungskammer",fr="Chambre d'exécution de Navukgo"},
    [65] = {id=65,en="Mamook",ja="マムーク",de="Mamook",fr="Mamook"},
    [66] = {id=66,en="Mamool Ja Training Grounds",ja="マムージャ兵訓練所",de="Mamool Ja-Trainingslager",fr="Camp d'entraînement mamool ja"},
    [67] = {id=67,en="Jade Sepulcher",ja="翡翠廟",de="Jade-Grabstätte",fr="Sanctuaire de Jade"},
    [68] = {id=68,en="Aydeewa Subterrane",ja="エジワ蘿洞",de="Aydeewa-Untergrund",fr="Souterrains d'Aydeewa"},
    [69] = {id=69,en="Leujaoam Sanctum",ja="ルジャワン霊窟",de="Leujaoam-Heiligtum",fr="Antre des âmes de Leujaoam"},
    [70] = {id=70,en="Chocobo Circuit",ja="チョコボサーキット",de="Chocobo-Rennbahn",fr="Chocodrome"},
    [71] = {id=71,en="The Colosseum",ja="コロセウム",de="Das Kolosseum",fr="Colisée"},
    [72] = {id=72,en="Alzadaal Undersea Ruins",ja="アルザダール海底遺跡群",de="Unterwasserr. Alzadaal",fr="Ruines immergées"},
    [73] = {id=73,en="Zhayolm Remnants",ja="ゼオルム遺構",de="Zhayolm-Ruinen",fr="Vestiges de Zhayolm"},
    [74] = {id=74,en="Arrapago Remnants",ja="アラパゴ遺構",de="Arrapago-Ruinen",fr="Vestiges d'Arrapago"},
    [75] = {id=75,en="Bhaflau Remnants",ja="バフラウ遺構",de="Bhaflau-Ruinen",fr="Vestiges de Bhaflau"},
    [76] = {id=76,en="Silver Sea Remnants",ja="銀海遺構",de="Silbersee-Ruinen",fr="Vestiges Mer d'Argent"},
    [77] = {id=77,en="Nyzul Isle",ja="ナイズル島",de="Nyzul-Insel",fr="Ile de Nyzul"},
    [78] = {id=78,en="Hazhalm Testing Grounds",ja="ハザルム試験場",de="Hazhalm-Testfakultät",fr="Laboratoire d'Hazhalm"},
    [79] = {id=79,en="Caedarva Mire",ja="カダーバの浮沼",de="Caedarva-Sumpf",fr="Bourbier de Caedarva"},
    [80] = {id=80,en="Southern San d'Oria [S]",ja="南サンドリア〔Ｓ〕",de="Süd-San d'Oria (R)",fr="San d'Oria Sud (R)"},
    [81] = {id=81,en="East Ronfaure [S]",ja="東ロンフォール〔Ｓ〕",de="Ost-Ronfaure (R)",fr="Ronfaure oriental (R)"},
    [82] = {id=82,en="Jugner Forest [S]",ja="ジャグナー森林〔Ｓ〕",de="Jugner-Wald (R)",fr="Forêt de Jugner (R)"},
    [83] = {id=83,en="Vunkerl Inlet [S]",ja="ブンカール浦〔Ｓ〕",de="Vunkerl-Bucht (R)",fr="Calanques de Vunkerl (R)"},
    [84] = {id=84,en="Batallia Downs [S]",ja="バタリア丘陵〔Ｓ〕",de="Batallia-Tiefen (R)",fr="Collines de Batallia (R)"},
    [85] = {id=85,en="La Vaule [S]",ja="ラヴォール村〔Ｓ〕",de="La Vaule (R)",fr="La Vaule (R)"},
    [86] = {id=86,en="Everbloom Hollow",ja="常花の石窟",de="Immergrün-Höhle",fr="Grotte éternelle floraison"},
    [87] = {id=87,en="Bastok Markets [S]",ja="バストゥーク商業区〔Ｓ〕",de="Bastok-Markt (R)",fr="Marché de Bastok (R)"},
    [88] = {id=88,en="North Gustaberg [S]",ja="北グスタベルグ〔Ｓ〕",de="Nord-Gustaberg (R)",fr="Gustaberg Nord (R)"},
    [89] = {id=89,en="Grauberg [S]",ja="グロウベルグ〔Ｓ〕",de="Grauberg (R)",fr="Grauberg (R)"},
    [90] = {id=90,en="Pashhow Marshlands [S]",ja="パシュハウ沼〔Ｓ〕",de="Pashhow-Sumpfland (R)",fr="Marécages Pashhow (R)"},
    [91] = {id=91,en="Rolanberry Fields [S]",ja="ロランベリー耕地〔Ｓ〕",de="Rolanbeeren-Felder (R)",fr="Champs Rolanberry (R)"},
    [92] = {id=92,en="Beadeaux [S]",ja="ベドー〔Ｓ〕",de="Beadeaux (R)",fr="Beadeaux (R)"},
    [93] = {id=93,en="Ruhotz Silvermines",ja="ルホッツ銀山",de="Ruhotz-Silberminen",fr="Mines d'argent de Ruhotz"},
    [94] = {id=94,en="Windurst Waters [S]",ja="ウィンダス水の区〔Ｓ〕",de="Windurst-Weiher (R)",fr="Canaux de Windurst (R)"},
    [95] = {id=95,en="West Sarutabaruta [S]",ja="西サルタバルタ〔Ｓ〕",de="West-Sarutabaruta (R)",fr="Sarutabaruta Ouest (R)"},
    [96] = {id=96,en="Fort Karugo-Narugo [S]",ja="カルゴナルゴ城砦〔Ｓ〕",de="Karugo-Narugo-F. (R)",fr="Fort Karugo-Narugo (R)"},
    [97] = {id=97,en="Meriphataud Mountains [S]",ja="メリファト山地〔Ｓ〕",de="Meriphataud-Berge (R)",fr="Mont. de Mériphataud (R)"},
    [98] = {id=98,en="Sauromugue Champaign [S]",ja="ソロムグ原野〔Ｓ〕",de="Sauromugue-Ebene (R)",fr="Camp. de Sauromugue (R)"},
    [99] = {id=99,en="Castle Oztroja [S]",ja="オズトロヤ城〔Ｓ〕",de="Oztroja-Schloss (R)",fr="Château d'Oztroja (R)"},
    [100] = {id=100,en="West Ronfaure",ja="西ロンフォール",de="West-Ronfaure",fr="Ronfaure occidental"},
    [101] = {id=101,en="East Ronfaure",ja="東ロンフォール",de="Ost-Ronfaure",fr="Ronfaure oriental"},
    [102] = {id=102,en="La Theine Plateau",ja="ラテーヌ高原",de="La Theine-Plateau",fr="Plateau de La Theine"},
    [103] = {id=103,en="Valkurm Dunes",ja="バルクルム砂丘",de="Valkurm-Dünen",fr="Dunes de Valkurm"},
    [104] = {id=104,en="Jugner Forest",ja="ジャグナー森林",de="Jugner-Wald",fr="Forêt de Jugner"},
    [105] = {id=105,en="Batallia Downs",ja="バタリア丘陵",de="Batallia-Tiefen",fr="Collines de Batallia"},
    [106] = {id=106,en="North Gustaberg",ja="北グスタベルグ",de="Nord-Gustaberg",fr="Gustaberg Nord"},
    [107] = {id=107,en="South Gustaberg",ja="南グスタベルグ",de="Süd-Gustaberg",fr="Gustaberg Sud"},
    [108] = {id=108,en="Konschtat Highlands",ja="コンシュタット高地",de="Konschtat-Hochland",fr="Htes-Terres Konschtat"},
    [109] = {id=109,en="Pashhow Marshlands",ja="パシュハウ沼",de="Pashhow-Sumpfland",fr="Marécages de Pashhow"},
    [110] = {id=110,en="Rolanberry Fields",ja="ロランベリー耕地",de="Rolanbeeren-Felder",fr="Champs de Rolanberry"},
    [111] = {id=111,en="Beaucedine Glacier",ja="ボスディン氷河",de="Beaucedine-Gletscher",fr="Glacier de Beaucedine"},
    [112] = {id=112,en="Xarcabard",ja="ザルカバード",de="Xarcabard",fr="Xarcabard"},
    [113] = {id=113,en="Cape Teriggan",ja="テリガン岬",de="Kap Teriggan",fr="Cap Teriggan"},
    [114] = {id=114,en="Eastern Altepa Desert",ja="東アルテパ砂漠",de="Ost-Altepa-Wüste",fr="Désert d'Altepa oriental"},
    [115] = {id=115,en="West Sarutabaruta",ja="西サルタバルタ",de="West-Sarutabaruta",fr="Sarutabaruta Ouest"},
    [116] = {id=116,en="East Sarutabaruta",ja="東サルタバルタ",de="Ost-Sarutabaruta",fr="Sarutabaruta Est"},
    [117] = {id=117,en="Tahrongi Canyon",ja="タロンギ大峡谷",de="Tahrongi-Schlucht",fr="Gorges de Tahrongi"},
    [118] = {id=118,en="Buburimu Peninsula",ja="ブブリム半島",de="Buburimu-Halbinsel",fr="Péninsule de Buburimu"},
    [119] = {id=119,en="Meriphataud Mountains",ja="メリファト山地",de="Meriphataud-Berge",fr="Montagnes Mériphataud"},
    [120] = {id=120,en="Sauromugue Champaign",ja="ソロムグ原野",de="Sauromugue-Ebene",fr="Campagne Sauromugue"},
    [121] = {id=121,en="The Sanctuary of Zi'Tah",ja="聖地ジ・タ",de="Heiligtum von Zi'Tah",fr="Sanctuaire de Zi'Tah"},
    [122] = {id=122,en="Ro'Maeve",ja="ロ・メーヴ",de="Ro'Maeve",fr="Ro'Maeve"},
    [123] = {id=123,en="Yuhtunga Jungle",ja="ユタンガ大森林",de="Yuhtunga-Dschungel",fr="Jungle de Yuhtunga"},
    [124] = {id=124,en="Yhoator Jungle",ja="ヨアトル大森林",de="Yhoator-Dschungel",fr="Jungle de Yhoator"},
    [125] = {id=125,en="Western Altepa Desert",ja="西アルテパ砂漠",de="West-Altepa-Wüste",fr="Désert d'Altepa occid."},
    [126] = {id=126,en="Qufim Island",ja="クフィム島",de="Qufim-Insel",fr="Ile de Qufim"},
    [127] = {id=127,en="Behemoth's Dominion",ja="ベヒーモスの縄張り",de="Behemoth-Dominion",fr="Territoire de Béhémoth"},
    [128] = {id=128,en="Valley of Sorrows",ja="慟哭の谷",de="Tränental",fr="Vallée de douleur"},
    [129] = {id=129,en="Ghoyu's Reverie",ja="ゴユの空洞",de="Ghoyus Kaverne (R)",fr="Rêverie de Ghoyu"},
    [130] = {id=130,en="Ru'Aun Gardens",ja="ル・オンの庭",de="Ru'Aun-Gärten",fr="Jardins de Ru'Aun"},
    [131] = {id=131,en="Mordion Gaol",ja="モルディオン監獄",de="Mordion-Kerker",fr="Prison de Mordion"},
    [132] = {id=132,en="Abyssea - La Theine",ja="アビセア-ラテーヌ",de="Abyssea - La Theine",fr="Abyssée - La Theine"},
    [134] = {id=134,en="Dynamis - Beaucedine",ja="デュナミス-ボスディン",de="Dynamis - Beaucedine",fr="Dynamis - Beaucedine"},
    [135] = {id=135,en="Dynamis - Xarcabard",ja="デュナミス-ザルカバード",de="Dynamis - Xarcabard",fr="Dynamis - Xarcabard"},
    [136] = {id=136,en="Beaucedine Glacier [S]",ja="ボスディン氷河〔Ｓ〕",de="Beaucedine-Gletscher (R)",fr="Glacier de Beaucedine (R)"},
    [137] = {id=137,en="Xarcabard [S]",ja="ザルカバード〔Ｓ〕",de="Xarcabard (R)",fr="Xarcabard (R)"},
    [138] = {id=138,en="Castle Zvahl Baileys [S]",ja="ズヴァール城外郭〔Ｓ〕",de="Zvahl-Schloss - Hof (R)",fr="Murs d'enc. Chât. Zvahl (R)"},
    [139] = {id=139,en="Horlais Peak",ja="ホルレーの岩峰",de="Horlais-Gipfel",fr="Pic de Horlais"},
    [140] = {id=140,en="Ghelsba Outpost",ja="ゲルスバ野営陣",de="Ghelsba-Außenpst.",fr="Avant-poste de Ghelsba"},
    [141] = {id=141,en="Fort Ghelsba",ja="ゲルスバ砦",de="Ghelsba-Festung",fr="Fort de Ghelsba"},
    [142] = {id=142,en="Yughott Grotto",ja="ユグホトの岩屋",de="Yughott-Grotte",fr="Grotte de Yughott"},
    [143] = {id=143,en="Palborough Mines",ja="パルブロ鉱山",de="Palborough-Minen",fr="Mines de Palborough"},
    [144] = {id=144,en="Waughroon Shrine",ja="ワールンの祠",de="Waughroon-Schrein",fr="Tombeau de Waughroon"},
    [145] = {id=145,en="Giddeus",ja="ギデアス",de="Giddeus",fr="Giddeus"},
    [146] = {id=146,en="Balga's Dais",ja="バルガの舞台",de="Balgas Podium",fr="Estrade de Balga"},
    [147] = {id=147,en="Beadeaux",ja="ベドー",de="Beadeaux",fr="Beadeaux"},
    [148] = {id=148,en="Qulun Dome",ja="クゥルンの大伽藍",de="Qulun-Kuppel",fr="Dôme de Qulun"},
    [149] = {id=149,en="Davoi",ja="ダボイ",de="Davoi",fr="Davoï"},
    [150] = {id=150,en="Monastic Cavern",ja="修道窟",de="Monastik-Höhle",fr="Caverne monastique"},
    [151] = {id=151,en="Castle Oztroja",ja="オズトロヤ城",de="Oztroja-Schloss",fr="Château d'Oztroja"},
    [152] = {id=152,en="Altar Room",ja="祭壇の間",de="Altarraum",fr="Salle de l'autel"},
    [153] = {id=153,en="The Boyahda Tree",ja="ボヤーダ樹",de="Der Boyahda-Baum",fr="L'arbre de Boyahda"},
    [154] = {id=154,en="Dragon's Aery",ja="龍のねぐら",de="Drachen-Nest",fr="Volière aux dragons"},
    [155] = {id=155,en="Castle Zvahl Keep [S]",ja="ズヴァール城内郭〔Ｓ〕",de="Zvahl-Schloss - Fried (R)",fr="Donjon Château Zvahl (R)"},
    [156] = {id=156,en="Throne Room [S]",ja="王の間〔Ｓ〕",de="Thronsaal (R)",fr="Salle du trône (R)"},
    [157] = {id=157,en="Middle Delkfutt's Tower",ja="デルクフの塔中層",de="Mittel-Delkfutts-Turm",fr="Tour Delkfutt niv. méd."},
    [158] = {id=158,en="Upper Delkfutt's Tower",ja="デルクフの塔上層",de="Ober-Delkfutts-Turm",fr="Tour Delkfutt niv. sup."},
    [159] = {id=159,en="Temple of Uggalepih",ja="ウガレピ寺院",de="Uggalepih-Tempel",fr="Temple d'Uggalepih"},
    [160] = {id=160,en="Den of Rancor",ja="怨念洞",de="Höhle des Hasses",fr="Tanière de la rancœur"},
    [161] = {id=161,en="Castle Zvahl Baileys",ja="ズヴァール城外郭",de="Zvahl-Schloss - Hof",fr="Murs d'enc. Chât. Zvahl"},
    [162] = {id=162,en="Castle Zvahl Keep",ja="ズヴァール城内郭",de="Zvahl-Schloss - Fried",fr="Donjon Château Zvahl"},
    [163] = {id=163,en="Sacrificial Chamber",ja="生贄の間",de="Opferkammer",fr="Chambre du sacrifice"},
    [164] = {id=164,en="Garlaige Citadel [S]",ja="ガルレージュ要塞〔Ｓ〕",de="Garlaige-Zitadelle (R)",fr="Citadelle de Garlaige (R)"},
    [165] = {id=165,en="Throne Room",ja="王の間",de="Thronsaal",fr="Salle du trône"},
    [166] = {id=166,en="Ranguemont Pass",ja="ラングモント峠",de="Ranguemont-Pass",fr="Défilé de Ranguemont"},
    [167] = {id=167,en="Bostaunieux Oubliette",ja="ボストーニュ監獄",de="Bostaunieux-Kerker",fr="Oubliettes Bostaunieux"},
    [168] = {id=168,en="Chamber of Oracles",ja="宣託の間",de="Orakelkammer",fr="Chambre des Oracles"},
    [169] = {id=169,en="Toraimarai Canal",ja="トライマライ水路",de="Toraimarai-Kanal",fr="Canal de Toraimarai"},
    [170] = {id=170,en="Full Moon Fountain",ja="満月の泉",de="Vollmond-Brunnen",fr="Fontaine de la pleine lune"},
    [171] = {id=171,en="Crawlers' Nest [S]",ja="クロウラーの巣〔Ｓ〕",de="Raupen-Nest (R)",fr="Nid des chenilles (R)"},
    [172] = {id=172,en="Zeruhn Mines",ja="ツェールン鉱山",de="Zeruhn-Minen",fr="Mines de Zeruhn"},
    [173] = {id=173,en="Korroloka Tunnel",ja="コロロカの洞門",de="Korroloka-Tunnel",fr="Tunnel de Korroloka"},
    [174] = {id=174,en="Kuftal Tunnel",ja="クフタルの洞門",de="Kuftal-Tunnel",fr="Tunnel de Kuftal"},
    [175] = {id=175,en="The Eldieme Necropolis [S]",ja="エルディーム古墳〔Ｓ〕",de="Eldieme-Nekropolis (R)",fr="Nécropole d'Eldieme (R)"},
    [176] = {id=176,en="Sea Serpent Grotto",ja="海蛇の岩窟",de="Seeschlangen-Grotte",fr="Grotte du serpent de mer"},
    [177] = {id=177,en="Ve'Lugannon Palace",ja="ヴェ・ルガノン宮殿",de="Ve'Lugannon-Palast",fr="Palais de Ve'Lugannon"},
    [178] = {id=178,en="The Shrine of Ru'Avitau",ja="ル・アビタウ神殿",de="Ru'Avitau-Schrein",fr="Tombeau de Ru'Avitau"},
    [179] = {id=179,en="Stellar Fulcrum",ja="天輪の場",de="Sternen-Fulcrum",fr="Axe stellaire"},
    [180] = {id=180,en="La'Loff Amphitheater",ja="ラ・ロフの劇場",de="La'Loff-Amphitheater",fr="Amphithéâtre de La'Loff"},
    [181] = {id=181,en="The Celestial Nexus",ja="宿星の座",de="Himmels-Nexus",fr="Le Noeud céleste"},
    [182] = {id=182,en="Walk of Echoes",ja="ウォークオブエコーズ",de="Gang der Echos",fr="Promenoir des échos"},
    [183] = {id=183,en="Maquette Abdhaljs-Legion",ja="アブダルスの模型-レギオン",de="Maquette Abdhaljs - Legion",fr="Maquette Abdhaljs-Légion"},
    [184] = {id=184,en="Lower Delkfutt's Tower",ja="デルクフの塔下層",de="Unter-Delkfutts-Turm",fr="Tour Delkfutt niv. inf."},
    [185] = {id=185,en="Dynamis - San d'Oria",ja="デュナミス-サンドリア",de="Dynamis - San d'Oria",fr="Dynamis - San d'Oria"},
    [186] = {id=186,en="Dynamis - Bastok",ja="デュナミス-バストゥーク",de="Dynamis - Bastok",fr="Dynamis - Bastok"},
    [187] = {id=187,en="Dynamis - Windurst",ja="デュナミス-ウィンダス",de="Dynamis - Windurst",fr="Dynamis - Windurst"},
    [188] = {id=188,en="Dynamis - Jeuno",ja="デュナミス-ジュノ",de="Dynamis - Jeuno",fr="Dynamis - Jeuno"},
    [190] = {id=190,en="King Ranperre's Tomb",ja="龍王ランペールの墓",de="K. Ranperres Grab",fr="Tombe du roi Ranperre"},
    [191] = {id=191,en="Dangruf Wadi",ja="ダングルフの涸れ谷",de="Dangruf-Wadi",fr="Oued Dangruf"},
    [192] = {id=192,en="Inner Horutoto Ruins",ja="内ホルトト遺跡",de="Inn. Horut.-Ruinen",fr="Ruines int. d'Horutoto"},
    [193] = {id=193,en="Ordelle's Caves",ja="オルデール鍾乳洞",de="Ordelles Höhlen",fr="Cavernes d'Ordelle"},
    [194] = {id=194,en="Outer Horutoto Ruins",ja="外ホルトト遺跡",de="Äuß. Horut.-Ruinen",fr="Ruines ext. d'Horutoto"},
    [195] = {id=195,en="The Eldieme Necropolis",ja="エルディーム古墳",de="Eldieme-Nekropolis",fr="Nécropole d'Eldieme"},
    [196] = {id=196,en="Gusgen Mines",ja="グスゲン鉱山",de="Gusgen-Minen",fr="Mines de Gusgen"},
    [197] = {id=197,en="Crawlers' Nest",ja="クロウラーの巣",de="Raupen-Nest",fr="Nid des chenilles"},
    [198] = {id=198,en="Maze of Shakhrami",ja="シャクラミの地下迷宮",de="Shakhrami-Labyrinth",fr="Dédale de Shakhrami"},
    [200] = {id=200,en="Garlaige Citadel",ja="ガルレージュ要塞",de="Garlaige-Zitadelle",fr="Citadelle de Garlaige"},
    [201] = {id=201,en="Cloister of Gales",ja="突風の回廊",de="Orkan-Kloster",fr="Cloître des ouragans"},
    [202] = {id=202,en="Cloister of Storms",ja="雷鳴の回廊",de="Sturm-Kloster",fr="Cloître des foudres"},
    [203] = {id=203,en="Cloister of Frost",ja="凍結の回廊",de="Frost-Kloster",fr="Cloître du givre"},
    [204] = {id=204,en="Fei'Yin",ja="フェ・イン",de="Fei'Yin",fr="Fei'Yin"},
    [205] = {id=205,en="Ifrit's Cauldron",ja="イフリートの釜",de="Ifrit-Kessel",fr="Chaudron d'Ifrit"},
    [206] = {id=206,en="Qu'Bia Arena",ja="ク・ビアの闘技場",de="Qu'Bia-Arena",fr="Arènes de Qu'Bia"},
    [207] = {id=207,en="Cloister of Flames",ja="灼熱の回廊",de="Flammen-Kloster",fr="Cloître du brasier"},
    [208] = {id=208,en="Quicksand Caves",ja="流砂洞",de="Treibsand-Höhlen",fr="Caves sables mouvants"},
    [209] = {id=209,en="Cloister of Tremors",ja="震動の回廊",de="Beben-Kloster",fr="Cloître des tremblements"},
    [211] = {id=211,en="Cloister of Tides",ja="海流の回廊",de="Gezeiten-Kloster",fr="Cloître des marées"},
    [212] = {id=212,en="Gustav Tunnel",ja="グスタフの洞門",de="Gustav-Tunnel",fr="Tunnel de Gustav"},
    [213] = {id=213,en="Labyrinth of Onzozo",ja="オンゾゾの迷路",de="Labyrinth von Onzozo",fr="Labyrinthe d'Onzozo"},
    [215] = {id=215,en="Abyssea - Attohwa",ja="アビセア-アットワ",de="Abyssea - Attohwa",fr="Abyssée - Attohwa"},
    [216] = {id=216,en="Abyssea - Misareaux",ja="アビセア-ミザレオ",de="Abyssea - Misareaux",fr="Abyssée - Misareaux"},
    [217] = {id=217,en="Abyssea - Vunkerl",ja="アビセア-ブンカール",de="Abyssea - Vunkerl",fr="Abyssée - Vunkerl"},
    [218] = {id=218,en="Abyssea - Altepa",ja="アビセア-アルテパ",de="Abyssea - Altepa",fr="Abyssée - Altepa"},
    [220] = {id=220,en="Ship bound for Selbina",ja="航路：セルビナ行き",de="Schiff nach Selbina",fr="Ferry pour Selbina"},
    [221] = {id=221,en="Ship bound for Mhaura",ja="航路：マウラ行き",de="Schiff nach Mhaura",fr="Ferry pour Mhaura"},
    [222] = {id=222,en="Provenance",ja="真界",de="Provenienz",fr="Provenance"},
    [223] = {id=223,en="San d'Oria-Jeuno Airship",ja="飛空艇航路",de="SdO.-Jeu. Luftschiff",fr="Aéronef San d'Oria-Jeuno"},
    [224] = {id=224,en="Bastok-Jeuno Airship",ja="飛空艇航路",de="Bast.-Jeu. Luftschiff",fr="Aéronef Bastok-Jeuno"},
    [225] = {id=225,en="Windurst-Jeuno Airship",ja="飛空艇航路",de="Wind.-Jeu. Luftschiff",fr="Aéronef Windurst-Jeuno"},
    [226] = {id=226,en="Kazham-Jeuno Airship",ja="飛空艇航路",de="Kazh.-Jeu. Luftschiff",fr="Aéronef Kazham-Jeuno"},
    [227] = {id=227,en="Ship bound for Selbina",ja="航路：セルビナ行き",de="Schiff nach Selbina",fr="Ferry pour Selbina"},
    [228] = {id=228,en="Ship bound for Mhaura",ja="航路：マウラ行き",de="Schiff nach Mhaura",fr="Ferry pour Mhaura"},
    [230] = {id=230,en="Southern San d'Oria",ja="南サンドリア",de="Süd-San d'Oria",fr="San d'Oria Sud"},
    [231] = {id=231,en="Northern San d'Oria",ja="北サンドリア",de="Nord-San d'Oria",fr="San d'Oria Nord"},
    [232] = {id=232,en="Port San d'Oria",ja="サンドリア港",de="San d'Oria-Hafen",fr="Port de San d'Oria"},
    [233] = {id=233,en="Chateau d'Oraguille",ja="ドラギーユ城",de="Oraguille-Schloss",fr="Château d'Oraguille"},
    [234] = {id=234,en="Bastok Mines",ja="バストゥーク鉱山区",de="Bastok-Minen",fr="Mines de Bastok"},
    [235] = {id=235,en="Bastok Markets",ja="バストゥーク商業区",de="Bastok-Markt",fr="Marché de Bastok"},
    [236] = {id=236,en="Port Bastok",ja="バストゥーク港",de="Bastok-Hafen",fr="Port de Bastok"},
    [237] = {id=237,en="Metalworks",ja="大工房",de="Metallwerke",fr="Forges"},
    [238] = {id=238,en="Windurst Waters",ja="ウィンダス水の区",de="Windurst-Weiher",fr="Canaux de Windurst"},
    [239] = {id=239,en="Windurst Walls",ja="ウィンダス石の区",de="Windurst-Mauern",fr="Remparts de Windurst"},
    [240] = {id=240,en="Port Windurst",ja="ウィンダス港",de="Windurst-Hafen",fr="Port de Windurst"},
    [241] = {id=241,en="Windurst Woods",ja="ウィンダス森の区",de="Windurst-Wälder",fr="Forêt de Windurst"},
    [242] = {id=242,en="Heavens Tower",ja="天の塔",de="Himmelsturm",fr="Tour des cieux"},
    [243] = {id=243,en="Ru'Lude Gardens",ja="ル・ルデの庭",de="Ru'Lude-Gärten",fr="Jardins de Ru'Lude"},
    [244] = {id=244,en="Upper Jeuno",ja="ジュノ上層",de="Ober-Jeuno",fr="Haut Jeuno"},
    [245] = {id=245,en="Lower Jeuno",ja="ジュノ下層",de="Unter-Jeuno",fr="Bas Jeuno"},
    [246] = {id=246,en="Port Jeuno",ja="ジュノ港",de="Jeuno-Hafen",fr="Port de Jeuno"},
    [247] = {id=247,en="Rabao",ja="ラバオ",de="Rabao",fr="Rabao"},
    [248] = {id=248,en="Selbina",ja="セルビナ",de="Selbina",fr="Selbina"},
    [249] = {id=249,en="Mhaura",ja="マウラ",de="Mhaura",fr="Mhaura"},
    [250] = {id=250,en="Kazham",ja="カザム",de="Kazham",fr="Kazham"},
    [251] = {id=251,en="Hall of the Gods",ja="神々の間",de="Halle der Götter",fr="Antichambre des dieux"},
    [252] = {id=252,en="Norg",ja="ノーグ",de="Norg",fr="Norg"},
    [253] = {id=253,en="Abyssea - Uleguerand",ja="アビセア-ウルガラン",de="Abyssea - Uleguerand",fr="Abyssée - Uleguerand"},
    [254] = {id=254,en="Abyssea - Grauberg",ja="アビセア-グロウベルグ",de="Abyssea - Grauberg",fr="Abyssée - Grauberg"},
    [255] = {id=255,en="Abyssea - Empyreal Paradox",ja="アビセア-天象の鎖",de="Abyssea - Paradox",fr="Abyssée - Paradoxe empyréen"},
    [256] = {id=256,en="Western Adoulin",ja="西アドゥリン",de="West-Adoulin",fr="Adoulin Ouest"},
    [257] = {id=257,en="Eastern Adoulin",ja="東アドゥリン",de="Ost-Adoulin",fr="Adoulin Est"},
    [258] = {id=258,en="Rala Waterways",ja="ララ水道",de="Rala-Aquädukt",fr="Voies d'eau de Rala"},
    [259] = {id=259,en="Rala Waterways [U]",ja="ララ水道〔Ｕ〕",de="Rala-Aquädukt (U)",fr="Voies d'eau de Rala (I)"},
    [260] = {id=260,en="Yahse Hunting Grounds",ja="ヤッセの狩り場",de="Yahse-Jagdgründe",fr="Chasses de Yahse"},
    [261] = {id=261,en="Ceizak Battlegrounds",ja="ケイザック古戦場",de="Ceizak-Schlachtfeld",fr="Champs d'honneur de Ceizak"},
    [262] = {id=262,en="Foret de Hennetiel",ja="エヌティエル水林",de="Hennetiel-Forst",fr="Forêt de Hennetiel"},
    [263] = {id=263,en="Yorcia Weald",ja="ヨルシア森林",de="Yorcia-Hain",fr="Sylve de Yorcia"},
    [264] = {id=264,en="Yorcia Weald [U]",ja="ヨルシア森林〔Ｕ〕",de="Yorcia-Hain (U)",fr="Sylve de Yorcia (I)"},
    [265] = {id=265,en="Morimar Basalt Fields",ja="モリマー台地",de="Morimar-Basaltplateau",fr="Pl. de basalte de Morimar"},
    [266] = {id=266,en="Marjami Ravine",ja="マリアミ渓谷",de="Marjami-Tal",fr="Vallée de Marjami"},
    [267] = {id=267,en="Kamihr Drifts",ja="カミール山麓",de="Kamihr-Ausläufer",fr="Congères de Kamihr"},
    [268] = {id=268,en="Sih Gates",ja="シィの門",de="Sih-Passage",fr="Passe de Sih"},
    [269] = {id=269,en="Moh Gates",ja="モーの門",de="Moh-Passage",fr="Passe de Moh"},
    [270] = {id=270,en="Cirdas Caverns",ja="シルダス洞窟",de="Cirdas-Höhlen",fr="Cavernes de Cirdas"},
    [271] = {id=271,en="Cirdas Caverns [U]",ja="シルダス洞窟〔Ｕ〕",de="Cirdas-Höhlen (U)",fr="Cavernes de Cirdas (I)"},
    [272] = {id=272,en="Dho Gates",ja="ドーの門",de="Dho-Passage",fr="Passe de Doh"},
    [273] = {id=273,en="Woh Gates",ja="ウォーの門",de="Woh-Passage",fr="Passe de Woh"},
    [274] = {id=274,en="Outer Ra'Kaznar",ja="ラ・カザナル宮外郭",de="Ra'Kaznar-Umgebung",fr="Périphérie de Ra'Kaznar"},
    [275] = {id=275,en="Outer Ra'Kaznar [U]",ja="ラ・カザナル宮外郭〔Ｕ〕",de="Ra'Kaznar-Umgebung (U)",fr="Périphérie de Ra'Kaznar (I)"},
    [280] = {id=280,en="Mog Garden",ja="モグガーデン",de="Mog-Garten",fr="Jardins Mog"},
    [283] = {id=283,en="Silver Knife",ja="シルバー・ナイフ",de="Das Silberne Messer",fr="Couteau d'argent"},
    [284] = {id=284,en="Celennia Memorial Library",ja="セレニア図書館",de="Celennia-Gedächtnisbibliothek",fr="Bibliothèque Celennia"},
    [285] = {id=285,en="Feretory",ja="魂の聖櫃",de="Seelenschrein",fr="Sanctuaire des âmes"},
}, {"id", "en", "ja", "de", "fr"}

--[[
Copyright © 2013-2014, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
