-- Automatically generated file: Buffs

return {
    [0] = {id=0,en="KO",ja="戦闘不能",de="K.o.",fr="K.O.",enl="KO'd",jal="戦闘不能",del="K.o.",frl="K.O.",duration=3600},
    [1] = {id=1,en="weakness",ja="衰弱",de="Schwäche",fr="Anémie",enl="weakened",jal="衰弱",del="Schwäche",frl="Anémie",duration=300},
    [2] = {id=2,en="sleep",ja="睡眠",de="Schlaf",fr="Sommeil",enl="asleep",jal="睡眠",del="Schlaf",frl="Sommeil"},
    [3] = {id=3,en="poison",ja="毒",de="Gift",fr="Poison",enl="poisoned",jal="毒",del="Gift",frl="Poison"},
    [4] = {id=4,en="paralysis",ja="麻痺",de="Paralyse",fr="Paralysie",enl="paralyzed",jal="麻痺",del="Paralyse",frl="Paralysie"},
    [5] = {id=5,en="blindness",ja="暗闇",de="Blind",fr="Cécité",enl="blinded",jal="暗闇",del="Blind",frl="Cécité"},
    [6] = {id=6,en="silence",ja="静寂",de="Schweigen",fr="Silence",enl="silenced",jal="静寂",del="Schweigen",frl="Silence"},
    [7] = {id=7,en="petrification",ja="石化",de="Stein",fr="Pétrification",enl="petrified",jal="石化",del="Stein",frl="Pétrification"},
    [8] = {id=8,en="disease",ja="病気",de="Krankheit",fr="Maladie",enl="diseased",jal="病気",del="Krankheit",frl="Maladie"},
    [9] = {id=9,en="curse",ja="呪い",de="Fluch",fr="Maléfice",enl="cursed",jal="呪い",del="Fluch",frl="Maléfice"},
    [10] = {id=10,en="stun",ja="スタン",de="Betäubung",fr="Etourdissement",enl="stunned",jal="スタン",del="Betäubung",frl="Etourdissement"},
    [11] = {id=11,en="bind",ja="バインド",de="Fessel",fr="Entrave",enl="bound",jal="バインド",del="Fessel",frl="Entrave"},
    [12] = {id=12,en="weight",ja="ヘヴィ",de="Gewicht",fr="Pesanteur",enl="weighed down",jal="ヘヴィ",del="Gewicht",frl="Pesanteur"},
    [13] = {id=13,en="slow",ja="スロウ",de="Gemach",fr="Lenteur",enl="slowed",jal="スロウ",del="Gemach",frl="Lenteur"},
    [14] = {id=14,en="charm",ja="魅了",de="Verzaubert",fr="Charme",enl="charmed",jal="魅了",del="Verzaubert",frl="Charme"},
    [15] = {id=15,en="doom",ja="死の宣告",de="Verhängnis",fr="Glas",enl="doomed",jal="死の宣告",del="Verhängnis",frl="Glas"},
    [16] = {id=16,en="amnesia",ja="アムネジア",de="Amnesie",fr="Amnésie",enl="amnesic",jal="アムネジア",del="Amnesie",frl="Amnésie"},
    [17] = {id=17,en="charm",ja="魅了",de="Verzaubert",fr="Charme",enl="charmed",jal="魅了",del="Verzaubert",frl="Charme"},
    [18] = {id=18,en="gradual petrification",ja="徐々に石化",de="Petrifikation",fr="Pétrification graduelle",enl="gradually petrifying",jal="徐々に石化",del="Petrifikation",frl="Pétrification graduelle"},
    [19] = {id=19,en="sleep",ja="睡眠",de="Schlaf",fr="Sommeil",enl="asleep",jal="睡眠",del="Schlaf",frl="Sommeil"},
    [20] = {id=20,en="curse",ja="呪い",de="Fluch",fr="Maléfice",enl="cursed",jal="呪い",del="Fluch",frl="Maléfice"},
    [21] = {id=21,en="addle",ja="アドル",de="Geist-Vernebelung",fr="Egarement",enl="addled",jal="アドル",del="Geist-Vernebelung",frl="Egarement"},
    [22] = {id=22,en="intimidate",ja="ひるみ",de="Drangsalierung",fr="Intimidation",enl="intimidated",jal="ひるみ",del="Drangsalierung",frl="Intimidation"},
    [23] = {id=23,en="Kaustra",ja="メルトン",de="Kaustra",fr="Kaustra",enl="afflicted with Kaustra",jal="メルトン",del="Kaustra",frl="Kaustra"},
    [28] = {id=28,en="terror",ja="テラー",de="Angst",fr="Terreur",enl="terrorized",jal="テラー",del="Angst",frl="Terreur"},
    [29] = {id=29,en="mute",ja="沈黙",de="Stumm",fr="Mutisme",enl="muted",jal="沈黙",del="Stumm",frl="Mutisme"},
    [30] = {id=30,en="bane",ja="呪詛",de="Bann",fr="Possession",enl="baned",jal="呪詛",del="Bann",frl="Possession"},
    [31] = {id=31,en="plague",ja="悪疫",de="Pest",fr="Peste",enl="plagued",jal="悪疫",del="Pest",frl="Peste"},
    [32] = {id=32,en="Flee",ja="とんずら",de="Reißaus",fr="Fuite",enl="fleeing",jal="とんずら",del="Reißaus",frl="Fuite",duration=30},
    [33] = {id=33,en="Haste",ja="ヘイスト",de="Hast",fr="Hâte",enl="hastened",jal="ヘイスト",del="Hast",frl="Hâte",duration=180},
    [34] = {id=34,en="Blaze Spikes",ja="ブレイズスパイク",de="Flammenspitzen",fr="Pointes de feu",enl="Blaze Spikes",jal="ブレイズスパイク",del="Flammenspitzen",frl="Pointes de feu",duration=180},
    [35] = {id=35,en="Ice Spikes",ja="アイススパイク",de="Eisspitzen",fr="Pointes de glace",enl="Ice Spikes",jal="アイススパイク",del="Eisspitzen",frl="Pointes de glace",duration=180},
    [36] = {id=36,en="Blink",ja="ブリンク",de="Spiegelschimmer",fr="Faux-semblant",enl="Blink",jal="ブリンク",del="Spiegelschimmer",frl="Faux-semblant",duration=300},
    [37] = {id=37,en="Stoneskin",ja="ストンスキン",de="Steinhaut",fr="Cuirasse",enl="Stoneskin",jal="ストンスキン",del="Steinhaut",frl="Cuirasse",duration=300},
    [38] = {id=38,en="Shock Spikes",ja="ショックスパイク",de="Schockspitzen",fr="Pointes de foudre",enl="Shock Spikes",jal="ショックスパイク",del="Schockspitzen",frl="Pointes de foudre",duration=180},
    [39] = {id=39,en="Aquaveil",ja="アクアベール",de="Wasserschleier",fr="Aquavoile",enl="Aquaveil",jal="アクアベール",del="Wasserschleier",frl="Aquavoile",duration=300},
    [40] = {id=40,en="Protect",ja="プロテス",de="Schutz",fr="Bouclier",enl="Protect",jal="プロテス",del="Schutz",frl="Bouclier",duration=1800},
    [41] = {id=41,en="Shell",ja="シェル",de="Schutzschirm",fr="Barrière",enl="Shell",jal="シェル",del="Schutzschirm",frl="Barrière",duration=1800},
    [42] = {id=42,en="Regen",ja="リジェネ",de="Regenerieren",fr="Récup",enl="regenerating",jal="リジェネ",del="Regenerieren",frl="Récup",duration=60},
    [43] = {id=43,en="Refresh",ja="リフレシュ",de="Erfrischen",fr="Recharge",enl="refreshing",jal="リフレシュ",del="Erfrischen",frl="Recharge",duration=150},
    [44] = {id=44,en="Mighty Strikes",ja="マイティストライク",de="Powerschläge",fr="Destro-frappes",enl="Mighty Strikes",jal="マイティストライク",del="Powerschläge",frl="Destro-frappes",duration=45},
    [45] = {id=45,en="Boost",ja="ためる",de="Boost",fr="Accumulation",enl="Boost",jal="ためる",del="Boost",frl="Accumulation",duration=180},
    [46] = {id=46,en="Hundred Fists",ja="百烈拳",de="Hundert Fäuste",fr="Cent poings",enl="Hundred Fists",jal="百烈拳",del="Hundert Fäuste",frl="Cent poings",duration=45},
    [47] = {id=47,en="Manafont",ja="魔力の泉",de="Mana-Fontäne",fr="Source de Mana",enl="Manafont",jal="魔力の泉",del="Mana-Fontäne",frl="Source de Mana",duration=60},
    [48] = {id=48,en="Chainspell",ja="連続魔",de="Kettenspruch",fr="Chaîne de sorts",enl="Chainspell",jal="連続魔",del="Kettenspruch",frl="Chaîne de sorts",duration=60},
    [49] = {id=49,en="Perfect Dodge",ja="絶対回避",de="Superkniff",fr="Esquive absolue",enl="Perfect Dodge",jal="絶対回避",del="Superkniff",frl="Esquive absolue",duration=30},
    [50] = {id=50,en="Invincible",ja="インビンシブル",de="Unbesiegbar",fr="Invincible",enl="Invincible",jal="インビンシブル",del="Unbesiegbar",frl="Invincible",duration=30},
    [51] = {id=51,en="Blood Weapon",ja="ブラッドウェポン",de="Blutwaffe",fr="Arme sanguinaire",enl="Blood Weapon",jal="ブラッドウェポン",del="Blutwaffe",frl="Arme sanguinaire",duration=30},
    [52] = {id=52,en="Soul Voice",ja="ソウルボイス",de="Seelenstimme",fr="Voix de l'âme",enl="Soul Voice",jal="ソウルボイス",del="Seelenstimme",frl="Voix de l'âme",duration=180},
    [53] = {id=53,en="Eagle Eye Shot",ja="イーグルアイ",de="Adleraugen-Schuss",fr="Œil d'aigle",enl="Eagle Eye Shot",jal="イーグルアイ",del="Adleraugen-Schuss",frl="Œil d'aigle"},
    [54] = {id=54,en="Meikyo Shisui",ja="明鏡止水",de="Meikyo Shisui",fr="Meikyo Shisui",enl="Meikyo Shisui",jal="明鏡止水",del="Meikyo Shisui",frl="Meikyo Shisui",duration=30},
    [55] = {id=55,en="Astral Flow",ja="アストラルフロウ",de="Astralstrom",fr="Aura astrale",enl="Astral Flow",jal="アストラルフロウ",del="Astralstrom",frl="Aura astrale",duration=180},
    [56] = {id=56,en="Berserk",ja="バーサク",de="Berserker",fr="Berserk",enl="Berserk",jal="バーサク",del="Berserker",frl="Berserk",duration=180},
    [57] = {id=57,en="Defender",ja="ディフェンダー",de="Defender",fr="Défenseur",enl="Defender",jal="ディフェンダー",del="Defender",frl="Défenseur",duration=180},
    [58] = {id=58,en="Aggressor",ja="アグレッサー",de="Aggressor",fr="Agresseur",enl="Aggressor",jal="アグレッサー",del="Aggressor",frl="Agresseur",duration=180},
    [59] = {id=59,en="Focus",ja="集中",de="Fokus",fr="Précision",enl="Focus",jal="集中",del="Fokus",frl="Précision",duration=120},
    [60] = {id=60,en="Dodge",ja="回避",de="Ausweichen",fr="Esquive +",enl="Dodge",jal="回避",del="Ausweichen",frl="Esquive +",duration=120},
    [61] = {id=61,en="Counterstance",ja="かまえる",de="Gegenzug",fr="Qui-vive",enl="Counterstance",jal="かまえる",del="Gegenzug",frl="Qui-vive",duration=300},
    [62] = {id=62,en="Sentinel",ja="センチネル",de="Sentinel",fr="Sentinelle",enl="Sentinel",jal="センチネル",del="Sentinel",frl="Sentinelle",duration=30},
    [63] = {id=63,en="Souleater",ja="暗黒",de="Seelenfresser",fr="Noirceur",enl="Souleater",jal="暗黒",del="Seelenfresser",frl="Noirceur",duration=60},
    [64] = {id=64,en="Last Resort",ja="ラストリゾート",de="Letzter Ausweg",fr="Dernier recours",enl="Last Resort",jal="ラストリゾート",del="Letzter Ausweg",frl="Dernier recours",duration=180},
    [65] = {id=65,en="Sneak Attack",ja="不意打ち",de="Schleichattacke",fr="Attaque furtive",enl="Sneak Attack",jal="不意打ち",del="Schleichattacke",frl="Attaque furtive",duration=60},
    [66] = {id=66,en="Copy Image",ja="分身",de="Kopiebild",fr="Réplique",enl="Copy Image",jal="分身",del="Kopiebild",frl="Réplique"},
    [67] = {id=67,en="Third Eye",ja="心眼",de="3. Auge",fr="Troisième œil",enl="Third Eye",jal="心眼",del="3. Auge",frl="Troisième œil",duration=30},
    [68] = {id=68,en="Warcry",ja="ウォークライ",de="Kampfschrei",fr="Cri de guerre",enl="Warcry",jal="ウォークライ",del="Kampfschrei",frl="Cri de guerre",duration=30},
    [69] = {id=69,en="Invisible",ja="インビジ",de="Unsichtbar",fr="Invisible",enl="Invisible",jal="インビジ",del="Unsichtbar",frl="Invisible",duration=300},
    [70] = {id=70,en="Deodorize",ja="デオード",de="Parfümieren",fr="Inodore",enl="Deodorize",jal="デオード",del="Parfümieren",frl="Inodore",duration=300},
    [71] = {id=71,en="Sneak",ja="スニーク",de="Schleichen",fr="Furtivité",enl="Sneak",jal="スニーク",del="Schleichen",frl="Furtivité",duration=300},
    [72] = {id=72,en="Sharpshot",ja="狙い撃ち",de="Fangschuss",fr="Visée",enl="Sharpshot",jal="狙い撃ち",del="Fangschuss",frl="Visée",duration=60},
    [73] = {id=73,en="Barrage",ja="乱れ撃ち",de="Trommelfeuer",fr="Tir en rafale",enl="Barrage",jal="乱れ撃ち",del="Trommelfeuer",frl="Tir en rafale",duration=60},
    [74] = {id=74,en="Holy Circle",ja="ホーリーサークル",de="Heiliger Kreis",fr="Cercle sacré",enl="Holy Circle",jal="ホーリーサークル",del="Heiliger Kreis",frl="Cercle sacré",duration=180},
    [75] = {id=75,en="Arcane Circle",ja="アルケインサークル",de="Arcana-Kreis",fr="Cercle ésotérique",enl="Arcane Circle",jal="アルケインサークル",del="Arcana-Kreis",frl="Cercle ésotérique",duration=180},
    [76] = {id=76,en="Hide",ja="かくれる",de="Verstecken",fr="Dissimulation",enl="hiding",jal="かくれる",del="Verstecken",frl="Dissimulation"},
    [77] = {id=77,en="Camouflage",ja="カモフラージュ",de="Tarnung",fr="Camouflage",enl="camouflaged",jal="カモフラージュ",del="Tarnung",frl="Camouflage"},
    [78] = {id=78,en="Divine Seal",ja="女神の印",de="Göttersiegel",fr="Sceau divin",enl="Divine Seal",jal="女神の印",del="Göttersiegel",frl="Sceau divin",duration=60},
    [79] = {id=79,en="Elemental Seal",ja="精霊の印",de="Elementar-Siegel",fr="Sceau élémentaire",enl="Elemental Seal",jal="精霊の印",del="Elementar-Siegel",frl="Sceau élémentaire",duration=60},
    [80] = {id=80,en="STR Boost",ja="STRアップ",de="STR-Boost",fr="STR augmentée",enl="STR-boosted",jal="STRアップ",del="STR-Boost",frl="STR augmentée"},
    [81] = {id=81,en="DEX Boost",ja="DEXアップ",de="DEX-Boost",fr="DEX augmentée",enl="DEX-boosted",jal="DEXアップ",del="DEX-Boost",frl="DEX augmentée"},
    [82] = {id=82,en="VIT Boost",ja="VITアップ",de="VIT-Boost",fr="VIT augmentée",enl="VIT-boosted",jal="VITアップ",del="VIT-Boost",frl="VIT augmentée"},
    [83] = {id=83,en="AGI Boost",ja="AGIアップ",de="AGI-Boost",fr="AGI augmentée",enl="AGI-boosted",jal="AGIアップ",del="AGI-Boost",frl="AGI augmentée"},
    [84] = {id=84,en="INT Boost",ja="INTアップ",de="INT-Boost",fr="INT augmentée",enl="INT-boosted",jal="INTアップ",del="INT-Boost",frl="INT augmentée"},
    [85] = {id=85,en="MND Boost",ja="MNDアップ",de="MND-Boost",fr="MND augmenté",enl="MND-boosted",jal="MNDアップ",del="MND-Boost",frl="MND augmenté"},
    [86] = {id=86,en="CHR Boost",ja="CHRアップ",de="CHR-Boost",fr="CHR augmenté",enl="CHR-boosted",jal="CHRアップ",del="CHR-Boost",frl="CHR augmenté"},
    [87] = {id=87,en="Trick Attack",ja="だまし討ち",de="Trickattacke",fr="Attaque sournoise",enl="Trick Attack",jal="だまし討ち",del="Trickattacke",frl="Attaque sournoise",duration=60},
    [88] = {id=88,en="Max HP Boost",ja="HPmaxアップ",de="Max HP-Boost",fr="Max. HP augmenté",enl="Max HP-boosted",jal="HPmaxアップ",del="Max HP-Boost",frl="Max. HP augmenté"},
    [89] = {id=89,en="Max MP Boost",ja="MPmaxアップ",de="Max MP-Boost",fr="Max. MP augmenté",enl="Max MP-boosted",jal="MPmaxアップ",del="Max MP-Boost",frl="Max. MP augmenté"},
    [90] = {id=90,en="Accuracy Boost",ja="命中率アップ",de="Präzisions-Boost",fr="Précision augmentée",enl="accuracy-boosted",jal="命中率アップ",del="Präzisions-Boost",frl="Précision augmentée"},
    [91] = {id=91,en="Attack Boost",ja="攻撃力アップ",de="Attacken-Boost",fr="Attaque augmentée",enl="attack-boosted",jal="攻撃力アップ",del="Attacken-Boost",frl="Attaque augmentée"},
    [92] = {id=92,en="Evasion Boost",ja="回避率アップ",de="Ausweich-Boost",fr="Esquive augmentée",enl="evasion-boosted",jal="回避率アップ",del="Ausweich-Boost",frl="Esquive augmentée"},
    [93] = {id=93,en="Defense Boost",ja="防御力アップ",de="Verteidigungs-Boost",fr="Défense augmentée",enl="defense-boosted",jal="防御力アップ",del="Verteidigungs-Boost",frl="Défense augmentée"},
    [94] = {id=94,en="Enfire",ja="エンファイア",de="Feuer +",fr="EndoFeu",enl="Enfire",jal="エンファイア",del="Feuer +",frl="EndoFeu"},
    [95] = {id=95,en="Enblizzard",ja="エンブリザド",de="Eis +",fr="EndoGlace",enl="Enblizzard",jal="エンブリザド",del="Eis +",frl="EndoGlace"},
    [96] = {id=96,en="Enaero",ja="エンエアロ",de="Wind +",fr="EndoVent",enl="Enaero",jal="エンエアロ",del="Wind +",frl="EndoVent"},
    [97] = {id=97,en="Enstone",ja="エンストーン",de="Erde +",fr="EndoPierre",enl="Enstone",jal="エンストーン",del="Erde +",frl="EndoPierre"},
    [98] = {id=98,en="Enthunder",ja="エンサンダー",de="Donner +",fr="EndoFoudre",enl="Enthunder",jal="エンサンダー",del="Donner +",frl="EndoFoudre"},
    [99] = {id=99,en="Enwater",ja="エンウォータ",de="Wasser +",fr="EndoEau",enl="Enwater",jal="エンウォータ",del="Wasser +",frl="EndoEau"},
    [100] = {id=100,en="Barfire",ja="バファイ",de="Feuerriegel",fr="AntiFeu",enl="Barfire",jal="バファイ",del="Feuerriegel",frl="AntiFeu",duration=150},
    [101] = {id=101,en="Barblizzard",ja="バブリザ",de="Eisriegel",fr="AntiGlace",enl="Barblizzard",jal="バブリザ",del="Eisriegel",frl="AntiGlace",duration=150},
    [102] = {id=102,en="Baraero",ja="バエアロ",de="Windriegel",fr="AntiVent",enl="Baraero",jal="バエアロ",del="Windriegel",frl="AntiVent",duration=150},
    [103] = {id=103,en="Barstone",ja="バストン",de="Erdenriegel",fr="AntiPierre",enl="Barstone",jal="バストン",del="Erdenriegel",frl="AntiPierre",duration=150},
    [104] = {id=104,en="Barthunder",ja="バサンダ",de="Donnerriegel",fr="AntiFoudre",enl="Barthunder",jal="バサンダ",del="Donnerriegel",frl="AntiFoudre",duration=150},
    [105] = {id=105,en="Barwater",ja="バウォタ",de="Wasserriegel",fr="AntiEau",enl="Barwater",jal="バウォタ",del="Wasserriegel",frl="AntiEau",duration=150},
    [106] = {id=106,en="Barsleep",ja="バスリプル",de="Schlafriegel",fr="AntiSommeil",enl="Barsleep",jal="バスリプル",del="Schlafriegel",frl="AntiSommeil",duration=480},
    [107] = {id=107,en="Barpoison",ja="バポイズン",de="Giftriegel",fr="AntiPoison",enl="Barpoison",jal="バポイズン",del="Giftriegel",frl="AntiPoison",duration=480},
    [108] = {id=108,en="Barparalyze",ja="バパライズ",de="Paralyseriegel",fr="AntiParalysie",enl="Barparalyze",jal="バパライズ",del="Paralyseriegel",frl="AntiParalysie",duration=480},
    [109] = {id=109,en="Barblind",ja="バブライン",de="Blindriegel",fr="AntiCécité",enl="Barblind",jal="バブライン",del="Blindriegel",frl="AntiCécité",duration=480},
    [110] = {id=110,en="Barsilence",ja="バサイレス",de="Schweigriegel",fr="AntiSilence",enl="Barsilence",jal="バサイレス",del="Schweigriegel",frl="AntiSilence",duration=480},
    [111] = {id=111,en="Barpetrify",ja="バブレイク",de="Steinriegel",fr="AntiPétrification",enl="Barpetrify",jal="バブレイク",del="Steinriegel",frl="AntiPétrification",duration=480},
    [112] = {id=112,en="Barvirus",ja="バウィルス",de="Virenriegel",fr="AntiVirus",enl="Barvirus",jal="バウィルス",del="Virenriegel",frl="AntiVirus",duration=480},
    [113] = {id=113,en="Reraise",ja="リレイズ",de="Wiederauferstehen",fr="Revie",enl="Reraise",jal="リレイズ",del="Wiederauferstehen",frl="Revie",duration=3600},
    [114] = {id=114,en="Cover",ja="かばう",de="Deckung",fr="Couverture",enl="Cover",jal="かばう",del="Deckung",frl="Couverture",duration=15},
    [115] = {id=115,en="Unlimited Shot",ja="エンドレスショット",de="Dauerschuss",fr="Tirs illimités",enl="Unlimited Shot",jal="エンドレスショット",del="Dauerschuss",frl="Tirs illimités",duration=60},
    [116] = {id=116,en="Phalanx",ja="ファランクス",de="Phalanx",fr="Phalange",enl="Phalanx",jal="ファランクス",del="Phalanx",frl="Phalange"},
    [117] = {id=117,en="Warding Circle",ja="護摩の守護円",de="Gewahrsamskreis",fr="Cercle protecteur",enl="Warding Circle",jal="護摩の守護円",del="Gewahrsamskreis",frl="Cercle protecteur",duration=180},
    [118] = {id=118,en="Ancient Circle",ja="エンシェントサークル",de="Urkreis",fr="Cercle ancien",enl="Ancient Circle",jal="エンシェントサークル",del="Urkreis",frl="Cercle ancien",duration=180},
    [119] = {id=119,en="STR Boost",ja="STRアップ",de="STR-Boost",fr="STR augmentée",enl="STR-boosted",jal="STRアップ",del="STR-Boost",frl="STR augmentée"},
    [120] = {id=120,en="DEX Boost",ja="DEXアップ",de="DEX-Boost",fr="DEX augmentée",enl="DEX-boosted",jal="DEXアップ",del="DEX-Boost",frl="DEX augmentée"},
    [121] = {id=121,en="VIT Boost",ja="VITアップ",de="VIT-Boost",fr="VIT augmentée",enl="VIT-boosted",jal="VITアップ",del="VIT-Boost",frl="VIT augmentée"},
    [122] = {id=122,en="AGI Boost",ja="AGIアップ",de="AGI-Boost",fr="AGI augmentée",enl="AGI-boosted",jal="AGIアップ",del="AGI-Boost",frl="AGI augmentée"},
    [123] = {id=123,en="INT Boost",ja="INTアップ",de="INT-Boost",fr="INT augmentée",enl="INT-boosted",jal="INTアップ",del="INT-Boost",frl="INT augmentée"},
    [124] = {id=124,en="MND Boost",ja="MNDアップ",de="MND-Boost",fr="MND augmenté",enl="MND-boosted",jal="MNDアップ",del="MND-Boost",frl="MND augmenté"},
    [125] = {id=125,en="CHR Boost",ja="CHRアップ",de="CHR-Boost",fr="CHR augmenté",enl="CHR-boosted",jal="CHRアップ",del="CHR-Boost",frl="CHR augmenté"},
    [126] = {id=126,en="Spirit Surge",ja="竜剣",de="Seelenstoß",fr="Souffle d'esprit",enl="Spirit Surge",jal="竜剣",del="Seelenstoß",frl="Souffle d'esprit",duration=60},
    [127] = {id=127,en="Costume",ja="コスチューム",de="Kostüm",fr="Costume",enl="Costume",jal="コスチューム",del="Kostüm",frl="Costume"},
    [128] = {id=128,en="Burn",ja="バーン",de="Brennen",fr="Combustion",enl="afflicted with Burn",jal="バーン",del="Brennen",frl="Combustion"},
    [129] = {id=129,en="Frost",ja="フロスト",de="Frost",fr="Givre",enl="afflicted with Frost",jal="フロスト",del="Frost",frl="Givre"},
    [130] = {id=130,en="Choke",ja="チョーク",de="Drossel",fr="Suffocation",enl="afflicted with Choke",jal="チョーク",del="Drossel",frl="Suffocation"},
    [131] = {id=131,en="Rasp",ja="ラスプ",de="Raspel",fr="Râpe",enl="afflicted with Rasp",jal="ラスプ",del="Raspel",frl="Râpe"},
    [132] = {id=132,en="Shock",ja="ショック",de="Schock",fr="Choc",enl="afflicted with Shock",jal="ショック",del="Schock",frl="Choc"},
    [133] = {id=133,en="Drown",ja="ドラウン",de="Ertrinken",fr="Submersion",enl="afflicted with Drown",jal="ドラウン",del="Ertrinken",frl="Submersion"},
    [134] = {id=134,en="Dia",ja="ディア",de="Dia",fr="Lumen",enl="afflicted with Dia",jal="ディア",del="Dia",frl="Lumen"},
    [135] = {id=135,en="Bio",ja="バイオ",de="Bio",fr="Bactérie",enl="afflicted with Bio",jal="バイオ",del="Bio",frl="Bactérie"},
    [136] = {id=136,en="STR Down",ja="STRダウン",de="STR-Down",fr="STR réduite",enl="afflicted with STR Down",jal="STRダウン",del="STR-Down",frl="STR réduite"},
    [137] = {id=137,en="DEX Down",ja="DEXダウン",de="DEX-Down",fr="DEX réduite",enl="afflicted with DEX Down",jal="DEXダウン",del="DEX-Down",frl="DEX réduite"},
    [138] = {id=138,en="VIT Down",ja="VITダウン",de="VIT-Down",fr="VIT réduite",enl="afflicted with VIT Down",jal="VITダウン",del="VIT-Down",frl="VIT réduite"},
    [139] = {id=139,en="AGI Down",ja="AGIダウン",de="AGI-Down",fr="AGI réduite",enl="afflicted with AGI Down",jal="AGIダウン",del="AGI-Down",frl="AGI réduite"},
    [140] = {id=140,en="INT Down",ja="INTダウン",de="INT-Down",fr="INT réduite",enl="afflicted with INT Down",jal="INTダウン",del="INT-Down",frl="INT réduite"},
    [141] = {id=141,en="MND Down",ja="MNDダウン",de="MND-Down",fr="MND réduit",enl="afflicted with MND Down",jal="MNDダウン",del="MND-Down",frl="MND réduit"},
    [142] = {id=142,en="CHR Down",ja="CHRダウン",de="CHR-Down",fr="CHR réduit",enl="afflicted with CHR Down",jal="CHRダウン",del="CHR-Down",frl="CHR réduit"},
    [143] = {id=143,en="Level Restriction",ja="レベル制限",de="Level-Einschränkung",fr="Restriction de niveau",enl="level-restricted",jal="レベル制限",del="Level-Einschränkung",frl="Restriction de niveau"},
    [144] = {id=144,en="Max HP Down",ja="HPmaxダウン",de="Max HP-Down",fr="Max. HP réduit",enl="afflicted with Max HP Down",jal="HPmaxダウン",del="Max HP-Down",frl="Max. HP réduit"},
    [145] = {id=145,en="Max MP Down",ja="MPmaxダウン",de="Max MP-Down",fr="Max. MP réduit",enl="afflicted with Max MP Down",jal="MPmaxダウン",del="Max MP-Down",frl="Max. MP réduit"},
    [146] = {id=146,en="Accuracy Down",ja="命中率ダウン",de="Präzisions-Down",fr="Précision réduite",enl="afflicted with Accuracy Down",jal="命中率ダウン",del="Präzisions-Down",frl="Précision réduite"},
    [147] = {id=147,en="Attack Down",ja="攻撃力ダウン",de="Attacken-Down",fr="Attaque réduite",enl="afflicted with Attack Down",jal="攻撃力ダウン",del="Attacken-Down",frl="Attaque réduite"},
    [148] = {id=148,en="Evasion Down",ja="回避率ダウン",de="Ausweich-Down",fr="Esquive réduite",enl="afflicted with Evasion Down",jal="回避率ダウン",del="Ausweich-Down",frl="Esquive réduite"},
    [149] = {id=149,en="Defense Down",ja="防御力ダウン",de="Verteidigungs-Down",fr="Défense réduite",enl="afflicted with Defense Down",jal="防御力ダウン",del="Verteidigungs-Down",frl="Défense réduite"},
    [150] = {id=150,en="Physical Shield",ja="物理バリア",de="Körperschild",fr="Bouclier physique",enl="Physical Shield",jal="物理バリア",del="Körperschild",frl="Bouclier physique"},
    [151] = {id=151,en="Arrow Shield",ja="遠隔物理バリア",de="Pfeilschild",fr="Bouclier à flèches",enl="Arrow Shield",jal="遠隔物理バリア",del="Pfeilschild",frl="Bouclier à flèches"},
    [152] = {id=152,en="Magic Shield",ja="魔法バリア",de="Magieschild",fr="Bouclier magique",enl="Magic Shield",jal="魔法バリア",del="Magieschild",frl="Bouclier magique"},
    [153] = {id=153,en="Damage Spikes",ja="ダメージスパイク",de="Schadensspitzen",fr="Pointes de dégâts",enl="Damage Spikes",jal="ダメージスパイク",del="Schadensspitzen",frl="Pointes de dégâts"},
    [154] = {id=154,en="Shining Ruby",ja="ルビーの輝き",de="Glanzrubin",fr="Rubis brillant",enl="Shining Ruby",jal="ルビーの輝き",del="Glanzrubin",frl="Rubis brillant",duration=180},
    [155] = {id=155,en="medicine",ja="服薬中",de="Unter Medikament",fr="Remède",enl="medicated",jal="服薬中",del="Unter Medikament",frl="Remède"},
    [156] = {id=156,en="Flash",ja="フラッシュ",de="Blitzlicht",fr="Flash",enl="afflicted with Flash",jal="フラッシュ",del="Blitzlicht",frl="Flash"},
    [157] = {id=157,en="SJ Restriction",ja="サポートジョブ無効",de="NJ-Beschränkung",fr="Restriction JS",enl="SJ Restriction",jal="サポートジョブ無効",del="NJ-Beschränkung",frl="Restriction JS"},
    [158] = {id=158,en="Provoke",ja="挑発",de="Provoziert",fr="Provocation",enl="provoked",jal="挑発",del="Provoziert",frl="Provocation"},
    [159] = {id=159,en="penalty",ja="ペナルティ",de="Bestrafung",fr="Pénalité",enl="penalized",jal="ペナルティ",del="Bestrafung",frl="Pénalité"},
    [160] = {id=160,en="preparations",ja="試合復帰準備中",de="Vorbereitungen",fr="Préparations",enl="preparing for battle",jal="試合復帰準備中",del="Vorbereitungen",frl="Préparations"},
    [161] = {id=161,en="Sprint",ja="スプリント",de="Sprint",fr="Sprint",enl="Sprint",jal="スプリント",del="Sprint",frl="Sprint"},
    [162] = {id=162,en="enchantment",ja="エンチャント",de="Verzaubertes Item",fr="Enchantement",enl="enchanted",jal="エンチャント",del="Verzaubertes Item",frl="Enchantement"},
    [163] = {id=163,en="Azure Lore",ja="アジュールロー",de="Blaues Gesetz",fr="Sagesse d'azur",enl="Azure Lore",jal="アジュールロー",del="Blaues Gesetz",frl="Sagesse d'azur"},
    [164] = {id=164,en="Chain Affinity",ja="ブルーチェーン",de="Blaue Kette",fr="Lien de chaînes",enl="Chain Affinity",jal="ブルーチェーン",del="Blaue Kette",frl="Lien de chaînes",duration=30},
    [165] = {id=165,en="Burst Affinity",ja="ブルーバースト",de="Blauer Ausbruch",fr="Lien d'explosions",enl="Burst Affinity",jal="ブルーバースト",del="Blauer Ausbruch",frl="Lien d'explosions",duration=30},
    [166] = {id=166,en="Overdrive",ja="オーバードライヴ",de="Overdrive",fr="Suractivité",enl="Overdrive",jal="オーバードライヴ",del="Overdrive",frl="Suractivité"},
    [167] = {id=167,en="Magic Def. Down",ja="魔法防御力ダウン",de="Verminderte Magieabwehr",fr="Déf. magique réduite",enl="Magic Def. Down",jal="魔法防御力ダウン",del="Verminderte Magieabwehr",frl="Déf. magique réduite"},
    [168] = {id=168,en="Inhibit TP",ja="インヒビットTP",de="TP-Sperre",fr="Inhibition de TP",enl="TP-inhibited",jal="インヒビットTP",del="TP-Sperre",frl="Inhibition de TP"},
    [169] = {id=169,en="Potency",ja="ポテンシー",de="Wirksamkeit",fr="Puissance",enl="Potency",jal="ポテンシー",del="Wirksamkeit",frl="Puissance",duration=60},
    [170] = {id=170,en="Regain",ja="リゲイン",de="Wiedererlangen",fr="Regain",enl="Regain",jal="リゲイン",del="Wiedererlangen",frl="Regain",duration=180},
    [171] = {id=171,en="Pax",ja="パクス",de="Pax",fr="Pax",enl="Pax",jal="パクス",del="Pax",frl="Pax",duration=60},
    [172] = {id=172,en="Intension",ja="インテンション",de="Intensivierung",fr="Intensification",enl="Intension",jal="インテンション",del="Intensivierung",frl="Intensification"},
    [173] = {id=173,en="Dread Spikes",ja="ドレッドスパイク",de="Furchtspitzen",fr="Pointes d'effroi",enl="Dread Spikes",jal="ドレッドスパイク",del="Furchtspitzen",frl="Pointes d'effroi"},
    [174] = {id=174,en="Magic Acc. Down",ja="魔法命中率ダウン",de="Magiepräzisions-Down",fr="Préc. magique réduite",enl="Magic Acc. Down",jal="魔法命中率ダウン",del="Magiepräzisions-Down",frl="Préc. magique réduite"},
    [175] = {id=175,en="Magic Atk. Down",ja="魔法攻撃力ダウン",de="Magieattacken-Down",fr="Attq. magique réduite",enl="Magic Atk. Down",jal="魔法攻撃力ダウン",del="Magieattacken-Down",frl="Attq. magique réduite"},
    [176] = {id=176,en="quickening",ja="移動速度アップ",de="Beschleunigung",fr="Vitesse déplacement augmentée",enl="quickened",jal="移動速度アップ",del="Beschleunigung",frl="Vitesse déplacement augmentée"},
    [177] = {id=177,en="encumbrance",ja="装備変更不可",de="Belastung",fr="Astreinte",enl="encumbered",jal="装備変更不可",del="Belastung",frl="Astreinte"},
    [178] = {id=178,en="Firestorm",ja="熱波の陣",de="Feuerfront",fr="Loi de la canicule",enl="Firestorm",jal="熱波の陣",del="Feuerfront",frl="Loi de la canicule"},
    [179] = {id=179,en="Hailstorm",ja="吹雪の陣",de="Hagelfront",fr="Loi du blizzard",enl="Hailstorm",jal="吹雪の陣",del="Hagelfront",frl="Loi du blizzard"},
    [180] = {id=180,en="Windstorm",ja="烈風の陣",de="Sturmfront",fr="Loi des ouragans",enl="Windstorm",jal="烈風の陣",del="Sturmfront",frl="Loi des ouragans"},
    [181] = {id=181,en="Sandstorm",ja="砂塵の陣",de="Staubfront",fr="Loi de la sécheresse",enl="Sandstorm",jal="砂塵の陣",del="Staubfront",frl="Loi de la sécheresse"},
    [182] = {id=182,en="Thunderstorm",ja="疾雷の陣",de="Gewitterfront",fr="Loi des orages",enl="Thunderstorm",jal="疾雷の陣",del="Gewitterfront",frl="Loi des orages"},
    [183] = {id=183,en="Rainstorm",ja="豪雨の陣",de="Regenfront",fr="Loi des averses",enl="Rainstorm",jal="豪雨の陣",del="Regenfront",frl="Loi des averses"},
    [184] = {id=184,en="Aurorastorm",ja="極光の陣",de="Aurorafront",fr="Loi de l'aurore",enl="Aurorastorm",jal="極光の陣",del="Aurorafront",frl="Loi de l'aurore"},
    [185] = {id=185,en="Voidstorm",ja="妖霧の陣",de="Nebelfront",fr="Loi du crépuscule",enl="Voidstorm",jal="妖霧の陣",del="Nebelfront",frl="Loi du crépuscule"},
    [186] = {id=186,en="Helix",ja="計略",de="Kern",fr="Thèse",enl="Helix",jal="計略",del="Kern",frl="Thèse"},
    [187] = {id=187,en="Sublimation: Activated",ja="机上演習:蓄積中",de="MP-Anhäufung",fr="Révisions en cours",enl="Sublimation: Activated",jal="机上演習:蓄積中",del="MP-Anhäufung",frl="Révisions en cours"},
    [188] = {id=188,en="Sublimation: Complete",ja="机上演習:蓄積完了",de="MP-Speicher",fr="Révisions terminées",enl="Sublimation: Complete",jal="机上演習:蓄積完了",del="MP-Speicher",frl="Révisions terminées"},
    [189] = {id=189,en="Max TP Down",ja="TPmaxダウン",de="Max TP-Down",fr="Max. TP réduit",enl="Max TP Down",jal="TPmaxダウン",del="Max TP-Down",frl="Max. TP réduit"},
    [190] = {id=190,en="Magic Atk. Boost",ja="魔法攻撃力アップ",de="Magieattacken-Boost",fr="Attq. magique augmentée",enl="Magic Atk. Boost",jal="魔法攻撃力アップ",del="Magieattacken-Boost",frl="Attq. magique augmentée"},
    [191] = {id=191,en="Magic Def. Boost",ja="魔法防御力アップ",de="Magieverteidigungs-Boost",fr="Déf. magique augmentée",enl="Magic Def. Boost",jal="魔法防御力アップ",del="Magieverteidigungs-Boost",frl="Déf. magique augmentée"},
    [192] = {id=192,en="Requiem",ja="レクイエム",de="Requiem",fr="Requiem",enl="Requiem",jal="レクイエム",del="Requiem",frl="Requiem"},
    [193] = {id=193,en="Lullaby",ja="ララバイ",de="Wiegenlied",fr="Berceuse",enl="Lullaby",jal="ララバイ",del="Wiegenlied",frl="Berceuse"},
    [194] = {id=194,en="Elegy",ja="エレジー",de="Elegie",fr="Elégie",enl="Elegy",jal="エレジー",del="Elegie",frl="Elégie"},
    [195] = {id=195,en="Paeon",ja="ピーアン",de="Paeon",fr="Péan",enl="Paeon",jal="ピーアン",del="Paeon",frl="Péan"},
    [196] = {id=196,en="Ballad",ja="バラード",de="Ballade",fr="Ballade",enl="Ballad",jal="バラード",del="Ballade",frl="Ballade"},
    [197] = {id=197,en="Minne",ja="ミンネ",de="Minne",fr="Lied",enl="Minne",jal="ミンネ",del="Minne",frl="Lied"},
    [198] = {id=198,en="Minuet",ja="メヌエット",de="Menuett",fr="Menuet",enl="Minuet",jal="メヌエット",del="Menuett",frl="Menuet"},
    [199] = {id=199,en="Madrigal",ja="マドリガル",de="Madrigal",fr="Madrigal",enl="Madrigal",jal="マドリガル",del="Madrigal",frl="Madrigal"},
    [200] = {id=200,en="Prelude",ja="プレリュード",de="Präludium",fr="Prélude",enl="Prelude",jal="プレリュード",del="Präludium",frl="Prélude"},
    [201] = {id=201,en="Mambo",ja="マンボ",de="Mambo",fr="Mambo",enl="Mambo",jal="マンボ",del="Mambo",frl="Mambo"},
    [202] = {id=202,en="Aubade",ja="オーバード",de="Aubade",fr="Aubade",enl="Aubade",jal="オーバード",del="Aubade",frl="Aubade"},
    [203] = {id=203,en="Pastoral",ja="パストラル",de="Kirchenlied",fr="Pastorale",enl="Pastoral",jal="パストラル",del="Kirchenlied",frl="Pastorale"},
    [204] = {id=204,en="Hum",ja="ハミング",de="Summen",fr="Chant",enl="Hum",jal="ハミング",del="Summen",frl="Chant"},
    [205] = {id=205,en="Fantasia",ja="ファンタジア",de="Fantasia",fr="Fantaisie",enl="Fantasia",jal="ファンタジア",del="Fantasia",frl="Fantaisie"},
    [206] = {id=206,en="Operetta",ja="オペレッタ",de="Operette",fr="Opérette",enl="Operetta",jal="オペレッタ",del="Operette",frl="Opérette"},
    [207] = {id=207,en="Capriccio",ja="カプリチオ",de="Capriccio",fr="Capriccio",enl="Capriccio",jal="カプリチオ",del="Capriccio",frl="Capriccio"},
    [208] = {id=208,en="Serenade",ja="セレナーデ",de="Serenade",fr="Sérénade",enl="Serenade",jal="セレナーデ",del="Serenade",frl="Sérénade"},
    [209] = {id=209,en="Round",ja="ロンド",de="Rondo",fr="Rondo",enl="Round",jal="ロンド",del="Rondo",frl="Rondo"},
    [210] = {id=210,en="Gavotte",ja="ガボット",de="Gavotte",fr="Gavotte",enl="Gavotte",jal="ガボット",del="Gavotte",frl="Gavotte"},
    [211] = {id=211,en="Fugue",ja="フーガ",de="Fuge",fr="Fugue",enl="Fugue",jal="フーガ",del="Fuge",frl="Fugue"},
    [212] = {id=212,en="Rhapsody",ja="ラプソディ",de="Rhapsodie",fr="Rhapsodie",enl="Rhapsody",jal="ラプソディ",del="Rhapsodie",frl="Rhapsodie"},
    [213] = {id=213,en="Aria",ja="アリア",de="Arie",fr="Aria",enl="Aria",jal="アリア",del="Arie",frl="Aria"},
    [214] = {id=214,en="March",ja="マーチ",de="Marsch",fr="Marche",enl="March",jal="マーチ",del="Marsch",frl="Marche"},
    [215] = {id=215,en="Etude",ja="エチュード",de="Etüde",fr="Etude",enl="Etude",jal="エチュード",del="Etüde",frl="Etude"},
    [216] = {id=216,en="Carol",ja="カロル",de="Gesang",fr="Cantique",enl="Carol",jal="カロル",del="Gesang",frl="Cantique"},
    [217] = {id=217,en="Threnody",ja="スレノディ",de="Klagelied",fr="Thrène",enl="Threnody",jal="スレノディ",del="Klagelied",frl="Thrène"},
    [218] = {id=218,en="Hymnus",ja="ヒムヌス",de="Hymne",fr="Hymne",enl="Hymnus",jal="ヒムヌス",del="Hymne",frl="Hymne"},
    [219] = {id=219,en="Mazurka",ja="マズルカ",de="Mazurka",fr="Mazurka",enl="Mazurka",jal="マズルカ",del="Mazurka",frl="Mazurka"},
    [220] = {id=220,en="Sirvente",ja="シルベント",de="Sirvente",fr="Sirvente",enl="Sirvente",jal="シルベント",del="Sirvente",frl="Sirvente"},
    [221] = {id=221,en="Dirge",ja="ダージュ",de="Abenteurer-Klagelied",fr="Mélopée",enl="Dirge",jal="ダージュ",del="Abenteurer-Klagelied",frl="Mélopée"},
    [222] = {id=222,en="Scherzo",ja="スケルツォ",de="Scherzo",fr="Scherzo",enl="Scherzo",jal="スケルツォ",del="Scherzo",frl="Scherzo"},
    [223] = {id=223,en="Nocturne",ja="ノクターン",de="Nocturne",fr="Nocturne",enl="Nocturne",jal="ノクターン",del="Nocturne",frl="Nocturne"},
    [227] = {id=227,en="Store TP",ja="ストアTP",de="TP-Lagern",fr="Réserve TP",enl="Store TP",jal="ストアTP",del="TP-Lagern",frl="Réserve TP"},
    [228] = {id=228,en="Embrava",ja="オーラ",de="Embrava",fr="Hardiesse",enl="Embrava",jal="オーラ",del="Embrava",frl="Hardiesse"},
    [229] = {id=229,en="Manawell",ja="魔力の雫",de="Mana-Quell",fr="Rosée de Mana",enl="Manawell",jal="魔力の雫",del="Mana-Quell",frl="Rosée de Mana"},
    [230] = {id=230,en="Spontaneity",ja="クイックマジック",de="Spontanität",fr="Spontanéité",enl="Spontaneity",jal="クイックマジック",del="Spontanität",frl="Spontanéité"},
    [231] = {id=231,en="Marcato",ja="マルカート",de="Marcato",fr="Marcato",enl="Marcato",jal="マルカート",del="Marcato",frl="Marcato"},
    [233] = {id=233,en="Auto-Regen",ja="オートリジェネ",de="Auto-Regenerieren",fr="Auto-récup",enl="Auto-Regen",jal="オートリジェネ",del="Auto-Regenerieren",frl="Auto-récup"},
    [234] = {id=234,en="Auto-Refresh",ja="オートリフレシュ",de="Auto-Erfrischen",fr="Auto-recharge",enl="Auto-Refresh",jal="オートリフレシュ",del="Auto-Erfrischen",frl="Auto-recharge"},
    [235] = {id=235,en="Fishing Imagery",ja="釣りイメージ",de="Angelbilder",fr="Image pêche",enl="Fishing Imagery",jal="釣りイメージ",del="Angelbilder",frl="Image pêche"},
    [236] = {id=236,en="Woodworking Imagery",ja="木工イメージ",de="Tischlereibilder",fr="Image menuiserie",enl="Woodworking Imagery",jal="木工イメージ",del="Tischlereibilder",frl="Image menuiserie"},
    [237] = {id=237,en="Smithing Imagery",ja="鍛冶イメージ",de="Schmiedebilder",fr="Image métallurgie",enl="Smithing Imagery",jal="鍛冶イメージ",del="Schmiedebilder",frl="Image métallurgie"},
    [238] = {id=238,en="Goldsmithing Imagery",ja="彫金イメージ",de="Goldschmiedebilder",fr="Image orfèvrerie",enl="Goldsmithing Imagery",jal="彫金イメージ",del="Goldschmiedebilder",frl="Image orfèvrerie"},
    [239] = {id=239,en="Clothcraft Imagery",ja="裁縫イメージ",de="Schneiderbilder",fr="Image confection",enl="Clothcraft Imagery",jal="裁縫イメージ",del="Schneiderbilder",frl="Image confection"},
    [240] = {id=240,en="Leathercraft Imagery",ja="革細工イメージ",de="Ledereibilder",fr="Image tannerie",enl="Leathercraft Imagery",jal="革細工イメージ",del="Ledereibilder",frl="Image tannerie"},
    [241] = {id=241,en="Bonecraft Imagery",ja="骨細工イメージ",de="Knochenwerksbilder",fr="Image osserie",enl="Bonecraft Imagery",jal="骨細工イメージ",del="Knochenwerksbilder",frl="Image osserie"},
    [242] = {id=242,en="Alchemy Imagery",ja="錬金術イメージ",de="Alchemiebilder",fr="Image alchimie",enl="Alchemy Imagery",jal="錬金術イメージ",del="Alchemiebilder",frl="Image alchimie"},
    [243] = {id=243,en="Cooking Imagery",ja="調理イメージ",de="Kochbilder",fr="Image cuisine",enl="Cooking Imagery",jal="調理イメージ",del="Kochbilder",frl="Image cuisine"},
    [249] = {id=249,en="Dedication",ja="専心",de="Hingabe",fr="Assiduité",enl="Dedication",jal="専心",del="Hingabe",frl="Assiduité"},
    [250] = {id=250,en="EF Badge",ja="遠征軍参加資格",de="ET-Ausweis",fr="Ecusson CE",enl="EF Badge",jal="遠征軍参加資格",del="ET-Ausweis",frl="Ecusson CE"},
    [251] = {id=251,en="Food",ja="食事",de="Essen",fr="Nourriture",enl="Food",jal="食事",del="Essen",frl="Nourriture"},
    [252] = {id=252,en="Chocobo",ja="チョコボ",de="Chocobo",fr="Chocobo",enl="Chocobo",jal="チョコボ",del="Chocobo",frl="Chocobo",duration=1800},
    [253] = {id=253,en="Signet",ja="シグネット",de="Siegel",fr="Sceau",enl="Signet",jal="シグネット",del="Siegel",frl="Sceau"},
    [254] = {id=254,en="Battlefield",ja="バトルフィールド",de="Schlachtfeld",fr="Champ de bataille",enl="Battlefield",jal="バトルフィールド",del="Schlachtfeld",frl="Champ de bataille"},
    [256] = {id=256,en="Sanction",ja="サンクション",de="Sanktion",fr="Sanction",enl="Sanction",jal="サンクション",del="Sanktion",frl="Sanction"},
    [257] = {id=257,en="Besieged",ja="ビシージド",de="Belagerung",fr="Siège",enl="Besieged",jal="ビシージド",del="Belagerung",frl="Siège"},
    [258] = {id=258,en="Illusion",ja="イリュージョン",de="Illusion",fr="Illusion",enl="Illusion",jal="イリュージョン",del="Illusion",frl="Illusion"},
    [259] = {id=259,en="encumbrance",ja="エンカンバー",de="Bürde",fr="Fardeau",enl="encumbered",jal="エンカンバー",del="Bürde",frl="Fardeau"},
    [260] = {id=260,en="Obliviscence",ja="オブリビセンス",de="Vergessenheit",fr="Oblitération",enl="Obliviscence",jal="オブリビセンス",del="Vergessenheit",frl="Oblitération"},
    [261] = {id=261,en="impairment",ja="インペア",de="Eingriff",fr="Handicap",enl="impaired",jal="インペア",del="Eingriff",frl="Handicap"},
    [262] = {id=262,en="Omerta",ja="オメルタ",de="Schweigepflicht",fr="Omerta",enl="Omerta",jal="オメルタ",del="Schweigepflicht",frl="Omerta"},
    [263] = {id=263,en="debilitation",ja="デビリテート",de="Entkräftung",fr="Impotence",enl="debilitated",jal="デビリテート",del="Entkräftung",frl="Impotence"},
    [264] = {id=264,en="Pathos",ja="パトス",de="Pathos",fr="Pathos",enl="Pathos",jal="パトス",del="Pathos",frl="Pathos"},
    [265] = {id=265,en="Flurry",ja="フラーリー",de="Aufregung",fr="Exaltation",enl="Flurry",jal="フラーリー",del="Aufregung",frl="Exaltation"},
    [266] = {id=266,en="Concentration",ja="コンセントレーション",de="Konzentration",fr="Concentration",enl="Concentration",jal="コンセントレーション",del="Konzentration",frl="Concentration"},
    [267] = {id=267,en="Allied Tags",ja="アライドタグ",de="Bündniswappen",fr="Marque des alliés",enl="Allied Tags",jal="アライドタグ",del="Bündniswappen",frl="Marque des alliés"},
    [268] = {id=268,en="Sigil",ja="シギル",de="Sigille",fr="Sigil",enl="Sigil",jal="シギル",del="Sigille",frl="Sigil"},
    [269] = {id=269,en="Level Sync",ja="レベルシンク",de="Level-Adaption",fr="Synchronisation",enl="Level Sync",jal="レベルシンク",del="Level-Adaption",frl="Synchronisation"},
    [270] = {id=270,en="Aftermath: Lv.1",ja="アフターマス:Lv1",de="Konsequenz: Level 1",fr="Contrecoup : Niv. 1",enl="Aftermath: Lv.1",jal="アフターマス:Lv1",del="Konsequenz: Level 1",frl="Contrecoup : Niv. 1"},
    [271] = {id=271,en="Aftermath: Lv.2",ja="アフターマス:Lv2",de="Konsequenz: Level 2",fr="Contrecoup : Niv. 2",enl="Aftermath: Lv.2",jal="アフターマス:Lv2",del="Konsequenz: Level 2",frl="Contrecoup : Niv. 2"},
    [272] = {id=272,en="Aftermath: Lv.3",ja="アフターマス:Lv3",de="Konsequenz: Level 3",fr="Contrecoup : Niv. 3",enl="Aftermath: Lv.3",jal="アフターマス:Lv3",del="Konsequenz: Level 3",frl="Contrecoup : Niv. 3"},
    [273] = {id=273,en="Aftermath",ja="アフターマス",de="Konsequenz",fr="Contrecoup",enl="Aftermath",jal="アフターマス",del="Konsequenz",frl="Contrecoup"},
    [274] = {id=274,en="Enlight",ja="エンライト",de="Licht +",fr="EndoLumière",enl="Enlight",jal="エンライト",del="Licht +",frl="EndoLumière"},
    [275] = {id=275,en="Auspice",ja="オースピス",de="Auspizium",fr="Auspice",enl="Auspice",jal="オースピス",del="Auspizium",frl="Auspice"},
    [276] = {id=276,en="Confrontation",ja="コンフロント",de="Konfrontation",fr="Confrontation",enl="Confrontation",jal="コンフロント",del="Konfrontation",frl="Confrontation"},
    [277] = {id=277,en="Enfire II",ja="エンファイアII",de="Feuer ++",fr="EndoFeu II",enl="Enfire II",jal="エンファイアII",del="Feuer ++",frl="EndoFeu II"},
    [278] = {id=278,en="Enblizzard II",ja="エンブリザドII",de="Eis ++",fr="EndoGlace II",enl="Enblizzard II",jal="エンブリザドII",del="Eis ++",frl="EndoGlace II"},
    [279] = {id=279,en="Enaero II",ja="エンエアロII",de="Wind ++",fr="EndoVent II",enl="Enaero II",jal="エンエアロII",del="Wind ++",frl="EndoVent II"},
    [280] = {id=280,en="Enstone II",ja="エンストーンII",de="Erde ++",fr="EndoPierre II",enl="Enstone II",jal="エンストーンII",del="Erde ++",frl="EndoPierre II"},
    [281] = {id=281,en="Enthunder II",ja="エンサンダーII",de="Donner ++",fr="EndoFoudre II",enl="Enthunder II",jal="エンサンダーII",del="Donner ++",frl="EndoFoudre II"},
    [282] = {id=282,en="Enwater II",ja="エンウォータII",de="Wasser ++",fr="EndoEau II",enl="Enwater II",jal="エンウォータII",del="Wasser ++",frl="EndoEau II"},
    [283] = {id=283,en="Perfect Defense",ja="絶対防御",de="Perfekte Abwehr",fr="Défense absolue",enl="Perfect Defense",jal="絶対防御",del="Perfekte Abwehr",frl="Défense absolue"},
    [284] = {id=284,en="Egg",ja="タマゴ",de="Ei",fr="Œuf",enl="Egg",jal="タマゴ",del="Ei",frl="Œuf"},
    [285] = {id=285,en="Visitant",ja="ビジタント",de="Wallfahrer",fr="Aura d'incursion",enl="Visitant",jal="ビジタント",del="Wallfahrer",frl="Aura d'incursion"},
    [286] = {id=286,en="Baramnesia",ja="バアムネジア",de="Amnesieriegel",fr="AntiAmnésie",enl="Baramnesia",jal="バアムネジア",del="Amnesieriegel",frl="AntiAmnésie"},
    [287] = {id=287,en="Atma",ja="アートマ",de="Atma",fr="Âtma",enl="Atma",jal="アートマ",del="Atma",frl="Âtma"},
    [288] = {id=288,en="Endark",ja="エンダーク",de="Dunkel +",fr="EndoTénèbres",enl="Endark",jal="エンダーク",del="Dunkel +",frl="EndoTénèbres"},
    [289] = {id=289,en="Enmity Boost",ja="敵対心アップ",de="Feindseligkeits-Boost",fr="Inimitié augmentée",enl="Enmity Boost",jal="敵対心アップ",del="Feindseligkeits-Boost",frl="Inimitié augmentée"},
    [290] = {id=290,en="Subtle Blow Plus",ja="モクシャアップ",de="Subtilschlag-Boost",fr="Coup subtil augmenté",enl="Subtle Blow Plus",jal="モクシャアップ",del="Subtilschlag-Boost",frl="Coup subtil augmenté"},
    [291] = {id=291,en="Enmity Down",ja="敵対心ダウン",de="Feindseligkeits-Down",fr="Inimitié réduite",enl="Enmity Down",jal="敵対心ダウン",del="Feindseligkeits-Down",frl="Inimitié réduite"},
    [292] = {id=292,en="Pennant",ja="ペナント",de="IFF-Flagge",fr="Bannière de bastion",enl="Pennant",jal="ペナント",del="IFF-Flagge",frl="Bannière de bastion"},
    [293] = {id=293,en="Negate Petrify",ja="ネゲートペトリ",de="Stein negieren",fr="NégaPétrification",enl="Negate Petrify",jal="ネゲートペトリ",del="Stein negieren",frl="NégaPétrification"},
    [294] = {id=294,en="Negate Terror",ja="ネゲートテラー",de="Furcht negieren",fr="NégaTerreur",enl="Negate Terror",jal="ネゲートテラー",del="Furcht negieren",frl="NégaTerreur"},
    [295] = {id=295,en="Negate Amnesia",ja="ネゲートアムネジア",de="Amnesie negieren",fr="NégaAmnésie",enl="Negate Amnesia",jal="ネゲートアムネジア",del="Amnesie negieren",frl="NégaAmnésie"},
    [296] = {id=296,en="Negate Doom",ja="ネゲートドゥーム",de="Verhängnis negieren",fr="NégaGlas",enl="Negate Doom",jal="ネゲートドゥーム",del="Verhängnis negieren",frl="NégaGlas"},
    [297] = {id=297,en="Negate Poison",ja="ネゲートポイズン",de="Gift negieren",fr="NégaPoison",enl="Negate Poison",jal="ネゲートポイズン",del="Gift negieren",frl="NégaPoison"},
    [298] = {id=298,en="critical hit evasion down",ja="被クリティカルヒット率アップ",de="Krit. Ausweich-Down",fr="Coups critiques subis augmentés",enl="critical hit evasion down",jal="被クリティカルヒット率アップ",del="Krit. Ausweich-Down",frl="Coups critiques subis augmentés"},
    [299] = {id=299,en="Overload",ja="オーバーロード",de="Überladen",fr="Surcharge",enl="overloaded",jal="オーバーロード",del="Überladen",frl="Surcharge"},
    [300] = {id=300,en="Fire Maneuver",ja="ファイアマニューバ",de="Feuermanöver",fr="Manœuvre feu",enl="Fire Maneuver",jal="ファイアマニューバ",del="Feuermanöver",frl="Manœuvre feu"},
    [301] = {id=301,en="Ice Maneuver",ja="アイスマニューバ",de="Eismanöver",fr="Manœuvre glace",enl="Ice Maneuver",jal="アイスマニューバ",del="Eismanöver",frl="Manœuvre glace"},
    [302] = {id=302,en="Wind Maneuver",ja="ウィンドマニューバ",de="Windmanöver",fr="Manœuvre vent",enl="Wind Maneuver",jal="ウィンドマニューバ",del="Windmanöver",frl="Manœuvre vent"},
    [303] = {id=303,en="Earth Maneuver",ja="アースマニューバ",de="Erdmanöver",fr="Manœuvre terre",enl="Earth Maneuver",jal="アースマニューバ",del="Erdmanöver",frl="Manœuvre terre"},
    [304] = {id=304,en="Thunder Maneuver",ja="サンダーマニューバ",de="Donnermanöver",fr="Manœuvre foudre",enl="Thunder Maneuver",jal="サンダーマニューバ",del="Donnermanöver",frl="Manœuvre foudre"},
    [305] = {id=305,en="Water Maneuver",ja="ウォータマニューバ",de="Wassermanöver",fr="Manœuvre eau",enl="Water Maneuver",jal="ウォータマニューバ",del="Wassermanöver",frl="Manœuvre eau"},
    [306] = {id=306,en="Light Maneuver",ja="ライトマニューバ",de="Lichtmanöver",fr="Manœuvre lumière",enl="Light Maneuver",jal="ライトマニューバ",del="Lichtmanöver",frl="Manœuvre lumière"},
    [307] = {id=307,en="Dark Maneuver",ja="ダークマニューバ",de="Schattenmanöver",fr="Manœuvre ténèbres",enl="Dark Maneuver",jal="ダークマニューバ",del="Schattenmanöver",frl="Manœuvre ténèbres"},
    [308] = {id=308,en="Double-Up Chance",ja="ダブルアップチャンス",de="Doppelter Einsatz",fr="Chance de Surenchère",enl="Double-Up Chance",jal="ダブルアップチャンス",del="Doppelter Einsatz",frl="Chance de Surenchère"},
    [309] = {id=309,en="Bust",ja="バスト",de="Pleite",fr="Bust",enl="Bust",jal="バスト",del="Pleite",frl="Bust"},
    [310] = {id=310,en="Fighter's Roll",ja="ファイターズロール",de="Kämpfer-Wurf",fr="Jet combattant",enl="Fighter's Roll",jal="ファイターズロール",del="Kämpfer-Wurf",frl="Jet combattant"},
    [311] = {id=311,en="Monk's Roll",ja="モンクスロール",de="Mönchs-Wurf",fr="Jet du moine",enl="Monk's Roll",jal="モンクスロール",del="Mönchs-Wurf",frl="Jet du moine"},
    [312] = {id=312,en="Healer's Roll",ja="ヒーラーズロール",de="Heiler-Wurf",fr="Jet du guérisseur",enl="Healer's Roll",jal="ヒーラーズロール",del="Heiler-Wurf",frl="Jet du guérisseur"},
    [313] = {id=313,en="Wizard's Roll",ja="ウィザーズロール",de="Magier-Wurf",fr="Jet du sorcier",enl="Wizard's Roll",jal="ウィザーズロール",del="Magier-Wurf",frl="Jet du sorcier"},
    [314] = {id=314,en="Warlock's Roll",ja="ワーロックスロール",de="Hexer-Wurf",fr="Jet enchanteur",enl="Warlock's Roll",jal="ワーロックスロール",del="Hexer-Wurf",frl="Jet enchanteur"},
    [315] = {id=315,en="Rogue's Roll",ja="ローグズロール",de="Gauner-Wurf",fr="Jet du brigand",enl="Rogue's Roll",jal="ローグズロール",del="Gauner-Wurf",frl="Jet du brigand"},
    [316] = {id=316,en="Gallant's Roll",ja="ガランツロール",de="Galant-Wurf",fr="Jet du preux",enl="Gallant's Roll",jal="ガランツロール",del="Galant-Wurf",frl="Jet du preux"},
    [317] = {id=317,en="Chaos Roll",ja="カオスロール",de="Chaos-Wurf",fr="Jet du chaos",enl="Chaos Roll",jal="カオスロール",del="Chaos-Wurf",frl="Jet du chaos"},
    [318] = {id=318,en="Beast Roll",ja="ビーストロール",de="Bestien-Wurf",fr="Jet de la bête",enl="Beast Roll",jal="ビーストロール",del="Bestien-Wurf",frl="Jet de la bête"},
    [319] = {id=319,en="Choral Roll",ja="コーラルロール",de="Choral-Wurf",fr="Jet du chant",enl="Choral Roll",jal="コーラルロール",del="Choral-Wurf",frl="Jet du chant"},
    [320] = {id=320,en="Hunter's Roll",ja="ハンターズロール",de="Jäger-Wurf",fr="Jet du chasseur",enl="Hunter's Roll",jal="ハンターズロール",del="Jäger-Wurf",frl="Jet du chasseur"},
    [321] = {id=321,en="Samurai Roll",ja="サムライロール",de="Samurai-Wurf",fr="Jet du samouraï",enl="Samurai Roll",jal="サムライロール",del="Samurai-Wurf",frl="Jet du samouraï"},
    [322] = {id=322,en="Ninja Roll",ja="ニンジャロール",de="Ninja-Wurf",fr="Jet du ninja",enl="Ninja Roll",jal="ニンジャロール",del="Ninja-Wurf",frl="Jet du ninja"},
    [323] = {id=323,en="Drachen Roll",ja="ドラケンロール",de="Draken-Wurf",fr="Jet du drachen",enl="Drachen Roll",jal="ドラケンロール",del="Draken-Wurf",frl="Jet du drachen"},
    [324] = {id=324,en="Evoker's Roll",ja="エボカーズロール",de="Rufer-Wurf",fr="Jet de l'adjurateur",enl="Evoker's Roll",jal="エボカーズロール",del="Rufer-Wurf",frl="Jet de l'adjurateur"},
    [325] = {id=325,en="Magus's Roll",ja="メガスズロール",de="Magus-Wurf",fr="Jet du mage",enl="Magus's Roll",jal="メガスズロール",del="Magus-Wurf",frl="Jet du mage"},
    [326] = {id=326,en="Corsair's Roll",ja="コルセアズロール",de="Piraten-Wurf",fr="Jet du corsaire",enl="Corsair's Roll",jal="コルセアズロール",del="Piraten-Wurf",frl="Jet du corsaire"},
    [327] = {id=327,en="Puppet Roll",ja="パペットロール",de="Puppen-Wurf",fr="Jet du pantin",enl="Puppet Roll",jal="パペットロール",del="Puppen-Wurf",frl="Jet du pantin"},
    [328] = {id=328,en="Dancer's Roll",ja="ダンサーロール",de="Flamenco-Wurf",fr="Jet du danseur",enl="Dancer's Roll",jal="ダンサーロール",del="Flamenco-Wurf",frl="Jet du danseur"},
    [329] = {id=329,en="Scholar's Roll",ja="スカラーロール",de="Grimoire-Wurf",fr="Jet de l'érudit",enl="Scholar's Roll",jal="スカラーロール",del="Grimoire-Wurf",frl="Jet de l'érudit"},
    [330] = {id=330,en="Bolter's Roll",ja="ボルターズロール",de="Chocobo-Wurf",fr="Jet du coureur",enl="Bolter's Roll",jal="ボルターズロール",del="Chocobo-Wurf",frl="Jet du coureur"},
    [331] = {id=331,en="Caster's Roll",ja="キャスターズロール",de="Dozenten-Wurf",fr="Jet de l'incantateur",enl="Caster's Roll",jal="キャスターズロール",del="Dozenten-Wurf",frl="Jet de l'incantateur"},
    [332] = {id=332,en="Courser's Roll",ja="コアサーズロール",de="Korsaren-Wurf",fr="Jet du veneur",enl="Courser's Roll",jal="コアサーズロール",del="Korsaren-Wurf",frl="Jet du veneur"},
    [333] = {id=333,en="Blitzer's Roll",ja="ブリッツァロール",de="Brachial-Wurf",fr="Jet de l'agresseur",enl="Blitzer's Roll",jal="ブリッツァロール",del="Brachial-Wurf",frl="Jet de l'agresseur"},
    [334] = {id=334,en="Tactician's Roll",ja="タクティックロール",de="Taktiker-Wurf",fr="Jet du tacticien",enl="Tactician's Roll",jal="タクティックロール",del="Taktiker-Wurf",frl="Jet du tacticien"},
    [335] = {id=335,en="Allies' Roll",ja="アライズロール",de="Domino-Wurf",fr="Jet de l'allié",enl="Allies' Roll",jal="アライズロール",del="Domino-Wurf",frl="Jet de l'allié"},
    [336] = {id=336,en="Miser's Roll",ja="マイザーロール",de="Knauser-Wurf",fr="Jet de l'économe",enl="Miser's Roll",jal="マイザーロール",del="Knauser-Wurf",frl="Jet de l'économe"},
    [337] = {id=337,en="Companion's Roll",ja="コンパニオンロール",de="Kompagnon-Wurf",fr="Jet du compère",enl="Companion's Roll",jal="コンパニオンロール",del="Kompagnon-Wurf",frl="Jet du compère"},
    [338] = {id=338,en="Avenger's Roll",ja="カウンターロール",de="Rächer-Wurf",fr="Jet du vengeur",enl="Avenger's Roll",jal="カウンターロール",del="Rächer-Wurf",frl="Jet du vengeur"},
    [340] = {id=340,en="Warrior's Charge",ja="ウォリアーチャージ",de="Kriegerwut",fr="Charge du guerrier",enl="Warrior's Charge",jal="ウォリアーチャージ",del="Kriegerwut",frl="Charge du guerrier"},
    [341] = {id=341,en="Formless Strikes",ja="無想無念",de="Formlose Schläge",fr="Coups informes",enl="Formless Strikes",jal="無想無念",del="Formlose Schläge",frl="Coups informes",duration=180},
    [342] = {id=342,en="Assassin's Charge",ja="アサシンチャージ",de="Attentäterwut",fr="Charge assassine",enl="Assassin's Charge",jal="アサシンチャージ",del="Attentäterwut",frl="Charge assassine",duration=60},
    [343] = {id=343,en="Feint",ja="フェイント",de="Finte",fr="Feinte",enl="Feint",jal="フェイント",del="Finte",frl="Feinte",duration=60},
    [344] = {id=344,en="Fealty",ja="フィールティ",de="Lehnseid",fr="Fidélité",enl="Fealty",jal="フィールティ",del="Lehnseid",frl="Fidélité",duration=60},
    [345] = {id=345,en="Dark Seal",ja="ダークシール",de="Dunkles Siegel",fr="Sceau ténébreux",enl="Dark Seal",jal="ダークシール",del="Dunkles Siegel",frl="Sceau ténébreux",duration=60},
    [346] = {id=346,en="Diabolic Eye",ja="ディアボリクアイ",de="Diabolisches Auge",fr="Œil diabolique",enl="Diabolic Eye",jal="ディアボリクアイ",del="Diabolisches Auge",frl="Œil diabolique",duration=180},
    [347] = {id=347,en="Nightingale",ja="ナイチンゲール",de="Nachtigall",fr="Rossignol",enl="Nightingale",jal="ナイチンゲール",del="Nachtigall",frl="Rossignol",duration=60},
    [348] = {id=348,en="Troubadour",ja="トルバドゥール",de="Troubadour",fr="Troubadour",enl="Troubadour",jal="トルバドゥール",del="Troubadour",frl="Troubadour",duration=60},
    [349] = {id=349,en="Killer Instinct",ja="K.インスティンクト",de="Killer-Instinkt",fr="Instinct de tueur",enl="Killer Instinct",jal="K.インスティンクト",del="Killer-Instinkt",frl="Instinct de tueur",duration=180},
    [350] = {id=350,en="Stealth Shot",ja="ステルスショット",de="Tarnschuss",fr="Tir furtif",enl="Stealth Shot",jal="ステルスショット",del="Tarnschuss",frl="Tir furtif"},
    [351] = {id=351,en="Flashy Shot",ja="フラッシーショット",de="Grellschuss",fr="Tir flagrant",enl="Flashy Shot",jal="フラッシーショット",del="Grellschuss",frl="Tir flagrant"},
    [352] = {id=352,en="Sange",ja="散華",de="Sange",fr="Sange",enl="Sange",jal="散華",del="Sange",frl="Sange"},
    [353] = {id=353,en="Hasso",ja="八双",de="Hasso",fr="Hasso",enl="Hasso",jal="八双",del="Hasso",frl="Hasso",duration=300},
    [354] = {id=354,en="Seigan",ja="星眼",de="Seigan",fr="Seigan",enl="Seigan",jal="星眼",del="Seigan",frl="Seigan",duration=300},
    [355] = {id=355,en="Convergence",ja="コンバージェンス",de="Konvergenz",fr="Convergence",enl="Convergence",jal="コンバージェンス",del="Konvergenz",frl="Convergence"},
    [356] = {id=356,en="Diffusion",ja="ディフュージョン",de="Diffusion",fr="Diffusion",enl="Diffusion",jal="ディフュージョン",del="Diffusion",frl="Diffusion"},
    [357] = {id=357,en="Snake Eye",ja="スネークアイ",de="Schlangenauge",fr="As",enl="Snake Eye",jal="スネークアイ",del="Schlangenauge",frl="As"},
    [358] = {id=358,en="Light Arts",ja="白のグリモア",de="Weißes Grimoire",fr="Grimoire blanc",enl="Light Arts",jal="白のグリモア",del="Weißes Grimoire",frl="Grimoire blanc"},
    [359] = {id=359,en="Dark Arts",ja="黒のグリモア",de="Schwarz. Grimoire",fr="Grimoire noir",enl="Dark Arts",jal="黒のグリモア",del="Schwarz. Grimoire",frl="Grimoire noir"},
    [360] = {id=360,en="Penury",ja="簡素清貧の章",de="Ex Deo",fr="Modestie",enl="Penury",jal="簡素清貧の章",del="Ex Deo",frl="Modestie"},
    [361] = {id=361,en="Parsimony",ja="勤倹小心の章",de="Ex nihilo",fr="Parcimonie",enl="Parsimony",jal="勤倹小心の章",del="Ex nihilo",frl="Parcimonie"},
    [362] = {id=362,en="Celerity",ja="電光石火の章",de="Tempus fugit",fr="Célérité",enl="Celerity",jal="電光石火の章",del="Tempus fugit",frl="Célérité"},
    [363] = {id=363,en="Alacrity",ja="疾風迅雷の章",de="Tempus vincit",fr="Alacrité",enl="Alacrity",jal="疾風迅雷の章",del="Tempus vincit",frl="Alacrité"},
    [364] = {id=364,en="Rapture",ja="意気昂然の章",de="Fiat lux",fr="Fougue",enl="Rapture",jal="意気昂然の章",del="Fiat lux",frl="Fougue"},
    [365] = {id=365,en="Ebullience",ja="気炎万丈の章",de="Ultima ratio",fr="Ebullition",enl="Ebullience",jal="気炎万丈の章",del="Ultima ratio",frl="Ebullition"},
    [366] = {id=366,en="Accession",ja="女神降臨の章",de="Summum bonum",fr="Avènement",enl="Accession",jal="女神降臨の章",del="Summum bonum",frl="Avènement"},
    [367] = {id=367,en="Manifestation",ja="精霊光来の章",de="Summum malum",fr="Manifestation",enl="Manifestation",jal="精霊光来の章",del="Summum malum",frl="Manifestation"},
    [368] = {id=368,en="Drain Samba",ja="ドレインサンバ",de="Vampir-Samba",fr="Samba Spoliation",enl="Drain Samba",jal="ドレインサンバ",del="Vampir-Samba",frl="Samba Spoliation",duration=90},
    [369] = {id=369,en="Aspir Samba",ja="アスピルサンバ",de="Leech-Samba",fr="Samba Aspiration",enl="Aspir Samba",jal="アスピルサンバ",del="Leech-Samba",frl="Samba Aspiration",duration=90},
    [370] = {id=370,en="Haste Samba",ja="ヘイストサンバ",de="Kraken-Samba",fr="Samba Hâte",enl="Haste Samba",jal="ヘイストサンバ",del="Kraken-Samba",frl="Samba Hâte",duration=90},
    [371] = {id=371,en="Velocity Shot",ja="ベロシティショット",de="Schnell-Lader",fr="Tir véloce",enl="Velocity Shot",jal="ベロシティショット",del="Schnell-Lader",frl="Tir véloce"},
    [375] = {id=375,en="Building Flourish",ja="B.フラリッシュ",de="Odins Polka",fr="Pirouette intense",enl="Building Flourish",jal="B.フラリッシュ",del="Odins Polka",frl="Pirouette intense"},
    [376] = {id=376,en="Trance",ja="トランス",de="Trance",fr="Transe",enl="Trance",jal="トランス",del="Trance",frl="Transe"},
    [377] = {id=377,en="Tabula Rasa",ja="連環計",de="Tabula rasa",fr="Tabula rasa",enl="Tabula Rasa",jal="連環計",del="Tabula rasa",frl="Tabula rasa"},
    [378] = {id=378,en="Drain Daze",ja="ドレインデイズ",de="V. Benommenheit",fr="Stupeur spoliante",enl="Drain Daze",jal="ドレインデイズ",del="V. Benommenheit",frl="Stupeur spoliante"},
    [379] = {id=379,en="Aspir Daze",ja="アスピルデイズ",de="L. Benommenheit",fr="Stupeur aspirante",enl="Aspir Daze",jal="アスピルデイズ",del="L. Benommenheit",frl="Stupeur aspirante"},
    [380] = {id=380,en="Haste Daze",ja="ヘイストデイズ",de="K. Benommenheit",fr="Stupeur hâtive",enl="Haste Daze",jal="ヘイストデイズ",del="K. Benommenheit",frl="Stupeur hâtive"},
    [381] = {id=381,en="Finishing Move 1",ja="フィニシングムーブ1",de="Tanzmanöver 1",fr="Mouvement final 1",enl="Finishing Move 1",jal="フィニシングムーブ1",del="Tanzmanöver 1",frl="Mouvement final 1"},
    [382] = {id=382,en="Finishing Move 2",ja="フィニシングムーブ2",de="Tanzmanöver 2",fr="Mouvement final 2",enl="Finishing Move 2",jal="フィニシングムーブ2",del="Tanzmanöver 2",frl="Mouvement final 2"},
    [383] = {id=383,en="Finishing Move 3",ja="フィニシングムーブ3",de="Tanzmanöver 3",fr="Mouvement final 3",enl="Finishing Move 3",jal="フィニシングムーブ3",del="Tanzmanöver 3",frl="Mouvement final 3"},
    [384] = {id=384,en="Finishing Move 4",ja="フィニシングムーブ4",de="Tanzmanöver 4",fr="Mouvement final 4",enl="Finishing Move 4",jal="フィニシングムーブ4",del="Tanzmanöver 4",frl="Mouvement final 4"},
    [385] = {id=385,en="Finishing Move 5",ja="フィニシングムーブ5",de="Tanzmanöver 5",fr="Mouvement final 5",enl="Finishing Move 5",jal="フィニシングムーブ5",del="Tanzmanöver 5",frl="Mouvement final 5"},
    [386] = {id=386,en="Lethargic Daze 1",ja="クイックステップ1",de="Pirouette 1",fr="Stupeur ankylosante 1",enl="Lethargic Daze 1",jal="クイックステップ1",del="Pirouette 1",frl="Stupeur ankylosante 1"},
    [387] = {id=387,en="Lethargic Daze 2",ja="クイックステップ2",de="Pirouette 2",fr="Stupeur ankylosante 2",enl="Lethargic Daze 2",jal="クイックステップ2",del="Pirouette 2",frl="Stupeur ankylosante 2"},
    [388] = {id=388,en="Lethargic Daze 3",ja="クイックステップ3",de="Pirouette 3",fr="Stupeur ankylosante 3",enl="Lethargic Daze 3",jal="クイックステップ3",del="Pirouette 3",frl="Stupeur ankylosante 3"},
    [389] = {id=389,en="Lethargic Daze 4",ja="クイックステップ4",de="Pirouette 4",fr="Stupeur ankylosante 4",enl="Lethargic Daze 4",jal="クイックステップ4",del="Pirouette 4",frl="Stupeur ankylosante 4"},
    [390] = {id=390,en="Lethargic Daze 5",ja="クイックステップ5",de="Pirouette 5",fr="Stupeur ankylosante 5",enl="Lethargic Daze 5",jal="クイックステップ5",del="Pirouette 5",frl="Stupeur ankylosante 5"},
    [391] = {id=391,en="Sluggish Daze 1",ja="ボックスステップ1",de="Ausfallschritt 1",fr="Stupeur débilitante 1",enl="Sluggish Daze 1",jal="ボックスステップ1",del="Ausfallschritt 1",frl="Stupeur débilitante 1"},
    [392] = {id=392,en="Sluggish Daze 2",ja="ボックスステップ2",de="Ausfallschritt 2",fr="Stupeur débilitante 2",enl="Sluggish Daze 2",jal="ボックスステップ2",del="Ausfallschritt 2",frl="Stupeur débilitante 2"},
    [393] = {id=393,en="Sluggish Daze 3",ja="ボックスステップ3",de="Ausfallschritt 3",fr="Stupeur débilitante 3",enl="Sluggish Daze 3",jal="ボックスステップ3",del="Ausfallschritt 3",frl="Stupeur débilitante 3"},
    [394] = {id=394,en="Sluggish Daze 4",ja="ボックスステップ4",de="Ausfallschritt 4",fr="Stupeur débilitante 4",enl="Sluggish Daze 4",jal="ボックスステップ4",del="Ausfallschritt 4",frl="Stupeur débilitante 4"},
    [395] = {id=395,en="Sluggish Daze 5",ja="ボックスステップ5",de="Ausfallschritt 5",fr="Stupeur débilitante 5",enl="Sluggish Daze 5",jal="ボックスステップ5",del="Ausfallschritt 5",frl="Stupeur débilitante 5"},
    [396] = {id=396,en="Weakened Daze 1",ja="スタッターステップ1",de="Schuhplattler 1",fr="Stupeur abrutissante 1",enl="Weakened Daze 1",jal="スタッターステップ1",del="Schuhplattler 1",frl="Stupeur abrutissante 1"},
    [397] = {id=397,en="Weakened Daze 2",ja="スタッターステップ2",de="Schuhplattler 2",fr="Stupeur abrutissante 2",enl="Weakened Daze 2",jal="スタッターステップ2",del="Schuhplattler 2",frl="Stupeur abrutissante 2"},
    [398] = {id=398,en="Weakened Daze 3",ja="スタッターステップ3",de="Schuhplattler 3",fr="Stupeur abrutissante 3",enl="Weakened Daze 3",jal="スタッターステップ3",del="Schuhplattler 3",frl="Stupeur abrutissante 3"},
    [399] = {id=399,en="Weakened Daze 4",ja="スタッターステップ4",de="Schuhplattler 4",fr="Stupeur abrutissante 4",enl="Weakened Daze 4",jal="スタッターステップ4",del="Schuhplattler 4",frl="Stupeur abrutissante 4"},
    [400] = {id=400,en="Weakened Daze 5",ja="スタッターステップ5",de="Schuhplattler 5",fr="Stupeur abrutissante 5",enl="Weakened Daze 5",jal="スタッターステップ5",del="Schuhplattler 5",frl="Stupeur abrutissante 5"},
    [401] = {id=401,en="Addendum: White",ja="白の補遺",de="Addendum albus",fr="Addenda blanc",enl="Addendum: White",jal="白の補遺",del="Addendum albus",frl="Addenda blanc"},
    [402] = {id=402,en="Addendum: Black",ja="黒の補遺",de="Addendum niger",fr="Addenda noir",enl="Addendum: Black",jal="黒の補遺",del="Addendum niger",frl="Addenda noir"},
    [403] = {id=403,en="Reprisal",ja="リアクト",de="Reflexion",fr="Représailles",enl="Reprisal",jal="リアクト",del="Reflexion",frl="Représailles"},
    [404] = {id=404,en="Magic Evasion Down",ja="魔法回避率ダウン",de="Magie-Ausweich-Down",fr="Esquive mag. réduite",enl="Magic Evasion Down",jal="魔法回避率ダウン",del="Magie-Ausweich-Down",frl="Esquive mag. réduite"},
    [405] = {id=405,en="Retaliation",ja="リタリエーション",de="Sühne",fr="Contre-attaque",enl="Retaliation",jal="リタリエーション",del="Sühne",frl="Contre-attaque"},
    [406] = {id=406,en="Footwork",ja="猫足立ち",de="Beinarbeit",fr="Jeu de jambes",enl="Footwork",jal="猫足立ち",del="Beinarbeit",frl="Jeu de jambes"},
    [407] = {id=407,en="Klimaform",ja="虚誘掩殺の策",de="Prognostica",fr="Traité de réflexion",enl="Klimaform",jal="虚誘掩殺の策",del="Prognostica",frl="Traité de réflexion"},
    [408] = {id=408,en="Sekkanoki",ja="石火之機",de="Sekkanoki",fr="Sekkanoki",enl="Sekkanoki",jal="石火之機",del="Sekkanoki",frl="Sekkanoki"},
    [409] = {id=409,en="Pianissimo",ja="ピアニッシモ",de="Pianissimo",fr="Pianissimo",enl="Pianissimo",jal="ピアニッシモ",del="Pianissimo",frl="Pianissimo"},
    [410] = {id=410,en="Saber Dance",ja="剣の舞い",de="Klingentanz",fr="Danse du sabre",enl="Saber Dance",jal="剣の舞い",del="Klingentanz",frl="Danse du sabre"},
    [411] = {id=411,en="Fan Dance",ja="扇の舞い",de="Fächertanz",fr="Danse de l'éventail",enl="Fan Dance",jal="扇の舞い",del="Fächertanz",frl="Danse de l'éventail"},
    [412] = {id=412,en="Altruism",ja="不惜身命の章",de="Utile dulci",fr="Altruisme",enl="Altruism",jal="不惜身命の章",del="Utile dulci",frl="Altruisme"},
    [413] = {id=413,en="Focalization",ja="一心精進の章",de="Lege artis",fr="Focalisation",enl="Focalization",jal="一心精進の章",del="Lege artis",frl="Focalisation"},
    [414] = {id=414,en="Tranquility",ja="天衣無縫の章",de="Modus incognitus",fr="Humilité",enl="Tranquility",jal="天衣無縫の章",del="Modus incognitus",frl="Humilité"},
    [415] = {id=415,en="Equanimity",ja="無憂無風の章",de="Modus arcanus",fr="Ataraxie",enl="Equanimity",jal="無憂無風の章",del="Modus arcanus",frl="Ataraxie"},
    [416] = {id=416,en="Enlightenment",ja="大悟徹底",de="Licentia poetica",fr="Apaisement",enl="Enlightenment",jal="大悟徹底",del="Licentia poetica",frl="Apaisement"},
    [417] = {id=417,en="Afflatus Solace",ja="ハートオブソラス",de="Afflatus solatii",fr="Consolation",enl="Afflatus Solace",jal="ハートオブソラス",del="Afflatus solatii",frl="Consolation"},
    [418] = {id=418,en="Afflatus Misery",ja="ハートオブミゼリ",de="Afflatus miseriae",fr="Adversité",enl="Afflatus Misery",jal="ハートオブミゼリ",del="Afflatus miseriae",frl="Adversité"},
    [419] = {id=419,en="Composure",ja="コンポージャー",de="Fassung",fr="Aplomb",enl="Composure",jal="コンポージャー",del="Fassung",frl="Aplomb"},
    [420] = {id=420,en="Yonin",ja="陽忍",de="Sonnenkunst",fr="Yonin",enl="Yonin",jal="陽忍",del="Sonnenkunst",frl="Yonin"},
    [421] = {id=421,en="Innin",ja="陰忍",de="Schattenkunst",fr="Innin",enl="Innin",jal="陰忍",del="Schattenkunst",frl="Innin"},
    [422] = {id=422,en="Carbuncle's Favor",ja="カーバンクルの加護",de="Carbuncles Schutz",fr="Egide de Carbuncle",enl="Carbuncle's Favor",jal="カーバンクルの加護",del="Carbuncles Schutz",frl="Egide de Carbuncle"},
    [423] = {id=423,en="Ifrit's Favor",ja="イフリートの加護",de="Ifrits Schutz",fr="Egide d'Ifrit",enl="Ifrit's Favor",jal="イフリートの加護",del="Ifrits Schutz",frl="Egide d'Ifrit"},
    [424] = {id=424,en="Shiva's Favor",ja="シヴァの加護",de="Shivas Schutz",fr="Egide de Shiva",enl="Shiva's Favor",jal="シヴァの加護",del="Shivas Schutz",frl="Egide de Shiva"},
    [425] = {id=425,en="Garuda's Favor",ja="ガルーダの加護",de="Garudas Schutz",fr="Egide de Garuda",enl="Garuda's Favor",jal="ガルーダの加護",del="Garudas Schutz",frl="Egide de Garuda"},
    [426] = {id=426,en="Titan's Favor",ja="タイタンの加護",de="Titans Schutz",fr="Egide de Titan",enl="Titan's Favor",jal="タイタンの加護",del="Titans Schutz",frl="Egide de Titan"},
    [427] = {id=427,en="Ramuh's Favor",ja="ラムウの加護",de="Ramuhs Schutz",fr="Egide de Ramuh",enl="Ramuh's Favor",jal="ラムウの加護",del="Ramuhs Schutz",frl="Egide de Ramuh"},
    [428] = {id=428,en="Leviathan's Favor",ja="リヴァイアサンの加護",de="Leviathans Schutz",fr="Egide de Leviathan",enl="Leviathan's Favor",jal="リヴァイアサンの加護",del="Leviathans Schutz",frl="Egide de Leviathan"},
    [429] = {id=429,en="Fenrir's Favor",ja="フェンリルの加護",de="Fenrirs Schutz",fr="Egide de Fenrir",enl="Fenrir's Favor",jal="フェンリルの加護",del="Fenrirs Schutz",frl="Egide de Fenrir"},
    [430] = {id=430,en="Diabolos's Favor",ja="ディアボロスの加護",de="Diabolos' Schutz",fr="Egide de Diabolos",enl="Diabolos's Favor",jal="ディアボロスの加護",del="Diabolos' Schutz",frl="Egide de Diabolos"},
    [431] = {id=431,en="Avatar's Favor",ja="神獣の加護",de="Avatar-Empathie",fr="Egide",enl="Avatar's Favor",jal="神獣の加護",del="Avatar-Empathie",frl="Egide"},
    [432] = {id=432,en="Multi Strikes",ja="マルチアタック",de="Multi-Attacke",fr="Attaque multiple",enl="Multi Strikes",jal="マルチアタック",del="Multi-Attacke",frl="Attaque multiple"},
    [433] = {id=433,en="Double Shot",ja="ダブルショット",de="Doppelschuss",fr="Double tir",enl="Double Shot",jal="ダブルショット",del="Doppelschuss",frl="Double tir"},
    [434] = {id=434,en="Transcendency",ja="天神地祇",de="Göttertrunk",fr="Puissance des dieux",enl="Transcendency",jal="天神地祇",del="Göttertrunk",frl="Puissance des dieux"},
    [435] = {id=435,en="Restraint",ja="リストレント",de="Beherrschung",fr="Retenue",enl="Restraint",jal="リストレント",del="Beherrschung",frl="Retenue"},
    [436] = {id=436,en="Perfect Counter",ja="絶対カウンター",de="Super-Konter",fr="Riposte absolue",enl="Perfect Counter",jal="絶対カウンター",del="Super-Konter",frl="Riposte absolue"},
    [437] = {id=437,en="Mana Wall",ja="マナウォール",de="Mana-Wall",fr="Barrière de Mana",enl="Mana Wall",jal="マナウォール",del="Mana-Wall",frl="Barrière de Mana"},
    [438] = {id=438,en="Divine Emblem",ja="神聖の印",de="Gottesemblem",fr="Emblème divin",enl="Divine Emblem",jal="神聖の印",del="Gottesemblem",frl="Emblème divin"},
    [439] = {id=439,en="Nether Void",ja="ネザーヴォイド",de="Niederes Nichts",fr="Vacuité des limbes",enl="Nether Void",jal="ネザーヴォイド",del="Niederes Nichts",frl="Vacuité des limbes"},
    [440] = {id=440,en="Sengikori",ja="先義後利",de="Sengikori",fr="Sengikori",enl="Sengikori",jal="先義後利",del="Sengikori",frl="Sengikori"},
    [441] = {id=441,en="Futae",ja="二重",de="Futae",fr="Futae",enl="Futae",jal="二重",del="Futae",frl="Futae"},
    [442] = {id=442,en="Presto",ja="プレスト",de="Degagé",fr="Presto",enl="Presto",jal="プレスト",del="Degagé",frl="Presto"},
    [443] = {id=443,en="Climactic Flourish",ja="C.フラリッシュ",de="Wogende Polka",fr="Pirouette virulente",enl="Climactic Flourish",jal="C.フラリッシュ",del="Wogende Polka",frl="Pirouette virulente"},
    [444] = {id=444,en="Copy Image (2)",ja="分身(2)",de="Kopiebild (2)",fr="Réplique (2)",enl="Copy Image (2)",jal="分身(2)",del="Kopiebild (2)",frl="Réplique (2)"},
    [445] = {id=445,en="Copy Image (3)",ja="分身(3)",de="Kopiebild (3)",fr="Réplique (3)",enl="Copy Image (3)",jal="分身(3)",del="Kopiebild (3)",frl="Réplique (3)"},
    [446] = {id=446,en="Copy Image (4+)",ja="分身(4+)",de="Kopiebild (4+)",fr="Réplique (4+)",enl="Copy Image (4+)",jal="分身(4+)",del="Kopiebild (4+)",frl="Réplique (4+)"},
    [447] = {id=447,en="Multi Shots",ja="マルチショット",de="Multi-Schuss",fr="Tir multiple",enl="Multi Shots",jal="マルチショット",del="Multi-Schuss",frl="Tir multiple"},
    [448] = {id=448,en="Bewildered Daze",ja="フェザーステップ",de="Felinenschritt",fr="Stupeur accablante",enl="Bewildered Daze",jal="フェザーステップ",del="Felinenschritt",frl="Stupeur accablante"},
    [449] = {id=449,en="Bewildered Daze",ja="フェザーステップ",de="Felinenschritt",fr="Stupeur accablante",enl="Bewildered Daze",jal="フェザーステップ",del="Felinenschritt",frl="Stupeur accablante"},
    [450] = {id=450,en="Bewildered Daze",ja="フェザーステップ",de="Felinenschritt",fr="Stupeur accablante",enl="Bewildered Daze",jal="フェザーステップ",del="Felinenschritt",frl="Stupeur accablante"},
    [451] = {id=451,en="Bewildered Daze",ja="フェザーステップ",de="Felinenschritt",fr="Stupeur accablante",enl="Bewildered Daze",jal="フェザーステップ",del="Felinenschritt",frl="Stupeur accablante"},
    [452] = {id=452,en="Bewildered Daze",ja="フェザーステップ",de="Felinenschritt",fr="Stupeur accablante",enl="Bewildered Daze",jal="フェザーステップ",del="Felinenschritt",frl="Stupeur accablante"},
    [453] = {id=453,en="Divine Caress",ja="女神の愛撫",de="Göttersalbung",fr="Caresse divine",enl="Divine Caress",jal="女神の愛撫",del="Göttersalbung",frl="Caresse divine"},
    [454] = {id=454,en="Saboteur",ja="サボトゥール",de="Debilitas ",fr="Persévérance",enl="Saboteur",jal="サボトゥール",del="Debilitas ",frl="Persévérance"},
    [455] = {id=455,en="Tenuto",ja="テヌート",de="Tenuto",fr="Tenuto",enl="Tenuto",jal="テヌート",del="Tenuto",frl="Tenuto"},
    [456] = {id=456,en="Spur",ja="気張れ",de="Anspornen",fr="En avant !",enl="Spur",jal="気張れ",del="Anspornen",frl="En avant !"},
    [457] = {id=457,en="Efflux",ja="エフラックス",de="Efflux",fr="Effusion",enl="Efflux",jal="エフラックス",del="Efflux",frl="Effusion"},
    [458] = {id=458,en="Earthen Armor",ja="大地の鎧",de="Gaia-Panzer",fr="Armure tellurique",enl="Earthen Armor",jal="大地の鎧",del="Gaia-Panzer",frl="Armure tellurique"},
    [459] = {id=459,en="Divine Caress",ja="女神の愛撫",de="Göttersalbung",fr="Caresse divine",enl="Divine Caress",jal="女神の愛撫",del="Göttersalbung",frl="Caresse divine"},
    [460] = {id=460,en="Blood Rage",ja="ブラッドレイジ",de="Blutrausch",fr="Rage sanguinaire",enl="Blood Rage",jal="ブラッドレイジ",del="Blutrausch",frl="Rage sanguinaire"},
    [461] = {id=461,en="Impetus",ja="インピタス",de="Impetus",fr="Impulsivité",enl="Impetus",jal="インピタス",del="Impetus",frl="Impulsivité"},
    [462] = {id=462,en="Conspirator",ja="コンスピレーター",de="Verschwörer",fr="Conspirateur",enl="Conspirator",jal="コンスピレーター",del="Verschwörer",frl="Conspirateur"},
    [463] = {id=463,en="Sepulcher",ja="セプルカー",de="Sakraler Bannspruch",fr="Nexus sépulcral",enl="Sepulcher",jal="セプルカー",del="Sakraler Bannspruch",frl="Nexus sépulcral"},
    [464] = {id=464,en="Arcane Crest",ja="アルケインクレスト",de="Arcanabann",fr="Nexus arcanique",enl="Arcane Crest",jal="アルケインクレスト",del="Arcanabann",frl="Nexus arcanique"},
    [465] = {id=465,en="Hamanoha",ja="破魔の刃",de="Hamanoha",fr="Nexus démoniaque",enl="Hamanoha",jal="破魔の刃",del="Hamanoha",frl="Nexus démoniaque"},
    [466] = {id=466,en="Dragon Breaker",ja="ドラゴンブレイカー",de="Drachenbrecher",fr="Nexus draconique",enl="Dragon Breaker",jal="ドラゴンブレイカー",del="Drachenbrecher",frl="Nexus draconique"},
    [467] = {id=467,en="Triple Shot",ja="トリプルショット",de="Dreifachschuss",fr="Triple tir",enl="Triple Shot",jal="トリプルショット",del="Dreifachschuss",frl="Triple tir"},
    [468] = {id=468,en="Striking Flourish",ja="S.フラリッシュ",de="Doppelschlag-Polka",fr="Pirouette cinglante",enl="Striking Flourish",jal="S.フラリッシュ",del="Doppelschlag-Polka",frl="Pirouette cinglante"},
    [469] = {id=469,en="Perpetuance",ja="令狸執鼠の章",de="Bonum Auxilium",fr="Perpétuation",enl="Perpetuance",jal="令狸執鼠の章",del="Bonum Auxilium",frl="Perpétuation"},
    [470] = {id=470,en="Immanence",ja="震天動地の章",de="Dominus Elementorum ",fr="Immanence",enl="Immanence",jal="震天動地の章",del="Dominus Elementorum ",frl="Immanence"},
    [471] = {id=471,en="Migawari",ja="身替",de="Migawari",fr="Migawari",enl="Migawari",jal="身替",del="Migawari",frl="Migawari"},
    [472] = {id=472,en="Ternary Flourish",ja="T.フラリッシュ",de="Ternär-Polka",fr="Pirouette ternaire",enl="Ternary Flourish",jal="T.フラリッシュ",del="Ternär-Polka",frl="Pirouette ternaire"},
    [473] = {id=473,en="muddle",ja="アイテム使用不可",de="Torkel",fr="Objets inutilisables",enl="muddled",jal="アイテム使用不可",del="Torkel",frl="Objets inutilisables"},
    [474] = {id=474,en="Prowess",ja="一時技能",de="Elan",fr="Prouesse temporaire",enl="Prowess",jal="一時技能",del="Elan",frl="Prouesse temporaire"},
    [475] = {id=475,en="Voidwatcher",ja="ヴォイドウォッチャー",de="Abyssus-Wacht",fr="Milice des abîmes",enl="Voidwatcher",jal="ヴォイドウォッチャー",del="Abyssus-Wacht",frl="Milice des abîmes"},
    [476] = {id=476,en="Ensphere",ja="インスフィア",de="Sphäre",fr="Sphère bénéfique",enl="Ensphere",jal="インスフィア",del="Sphäre",frl="Sphère bénéfique"},
    [477] = {id=477,en="Sacrosanctity",ja="女神の聖域",de="Sacrosanctitas",fr="Sacro-sainteté",enl="Sacrosanctity",jal="女神の聖域",del="Sacrosanctitas",frl="Sacro-sainteté"},
    [478] = {id=478,en="Palisade",ja="パリセード",de="Palisade",fr="Palissade",enl="Palisade",jal="パリセード",del="Palisade",frl="Palissade"},
    [479] = {id=479,en="Scarlet Delirium",ja="レッドデリリアム",de="Leidensdelirium",fr="Frénésie écarlate",enl="Scarlet Delirium",jal="レッドデリリアム",del="Leidensdelirium",frl="Frénésie écarlate"},
    [480] = {id=480,en="Scarlet Delirium",ja="レッドデリリアム",de="Leidensdelirium",fr="Frénésie écarlate",enl="Scarlet Delirium",jal="レッドデリリアム",del="Leidensdelirium",frl="Frénésie écarlate"},
    [482] = {id=482,en="Decoy Shot",ja="デコイショット",de="Täuschungsschuss",fr="Tir leurre",enl="Decoy Shot",jal="デコイショット",del="Täuschungsschuss",frl="Tir leurre"},
    [483] = {id=483,en="Hagakure",ja="葉隠",de="Hagakure",fr="Hagakure",enl="Hagakure",jal="葉隠",del="Hagakure",frl="Hagakure"},
    [484] = {id=484,en="Issekigan",ja="一隻眼",de="Issekigan",fr="Issekigan",enl="Issekigan",jal="一隻眼",del="Issekigan",frl="Issekigan"},
    [485] = {id=485,en="Unbridled Learning",ja="ノートリアスナレッジ",de="Ungezähmtes Wissen",fr="Savoir irréfréné",enl="Unbridled Learning",jal="ノートリアスナレッジ",del="Ungezähmtes Wissen",frl="Savoir irréfréné"},
    [486] = {id=486,en="Counter Boost",ja="カウンターアップ",de="Konter-Boost",fr="Bonus riposte",enl="Counter Boost",jal="カウンターアップ",del="Konter-Boost",frl="Bonus riposte"},
    [487] = {id=487,en="Endrain",ja="エンドレイン",de="Aussaugen +",fr="EndoSpoliation",enl="Endrain",jal="エンドレイン",del="Aussaugen +",frl="EndoSpoliation"},
    [488] = {id=488,en="Enaspir",ja="エンアスピル",de="Osmose +",fr="EndoAspiration",enl="Enaspir",jal="エンアスピル",del="Osmose +",frl="EndoAspiration"},
    [489] = {id=489,en="Afterglow",ja="アフターグロウ",de="Nachschimmern",fr="Répercussion",enl="Afterglow",jal="アフターグロウ",del="Nachschimmern",frl="Répercussion"},
    [490] = {id=490,en="Brazen Rush",ja="ブラーゼンラッシュ",de="Wilder Ansturm",fr="Ruée hardie",enl="Brazen Rush",jal="ブラーゼンラッシュ",del="Wilder Ansturm",frl="Ruée hardie"},
    [491] = {id=491,en="Inner Strength",ja="インナーストレングス",de="Innere Stärke",fr="Force intérieure",enl="Inner Strength",jal="インナーストレングス",del="Innere Stärke",frl="Force intérieure"},
    [492] = {id=492,en="Asylum",ja="女神の羽衣",de="Obhut",fr="Manteau divin",enl="Asylum",jal="女神の羽衣",del="Obhut",frl="Manteau divin"},
    [493] = {id=493,en="Subtle Sorcery",ja="サテルソーサリー",de="Subtile Zauberei",fr="Sorcellerie subtile",enl="Subtle Sorcery",jal="サテルソーサリー",del="Subtile Zauberei",frl="Sorcellerie subtile"},
    [494] = {id=494,en="Stymie",ja="スタイミー",de="Sackgasse",fr="Obstruction",enl="Stymie",jal="スタイミー",del="Sackgasse",frl="Obstruction"},
    [496] = {id=496,en="Intervene",ja="インターヴィーン",de="Intervention",fr="Intervention",enl="Intervene",jal="インターヴィーン",del="Intervention",frl="Intervention"},
    [497] = {id=497,en="Soul Enslavement",ja="ソールエンスレーヴ",de="Seelenfessel",fr="Vile consumation",enl="Soul Enslavement",jal="ソールエンスレーヴ",del="Seelenfessel",frl="Vile consumation"},
    [498] = {id=498,en="Unleash",ja="アンリーシュ",de="Entfesseln",fr="Débridement",enl="Unleash",jal="アンリーシュ",del="Entfesseln",frl="Débridement"},
    [499] = {id=499,en="Clarion Call",ja="クラリオンコール",de="Fanfarenstoß",fr="Appel du clairon",enl="Clarion Call",jal="クラリオンコール",del="Fanfarenstoß",frl="Appel du clairon"},
    [500] = {id=500,en="Overkill",ja="オーバーキル",de="Übermacht",fr="Mitraillage",enl="Overkill",jal="オーバーキル",del="Übermacht",frl="Mitraillage"},
    [501] = {id=501,en="Yaegasumi",ja="八重霞",de="Yaegasumi",fr="Yaegasumi",enl="Yaegasumi",jal="八重霞",del="Yaegasumi",frl="Yaegasumi"},
    [502] = {id=502,en="Mikage",ja="身影",de="Mikage",fr="Mikage",enl="Mikage",jal="身影",del="Mikage",frl="Mikage"},
    [503] = {id=503,en="Fly High",ja="フライハイ",de="Höhenflug",fr="Haut vol",enl="Fly High",jal="フライハイ",del="Höhenflug",frl="Haut vol"},
    [504] = {id=504,en="Astral Conduit",ja="アストラルパッセージ",de="Astraler Leiter",fr="Voie astrale",enl="Astral Conduit",jal="アストラルパッセージ",del="Astraler Leiter",frl="Voie astrale"},
    [505] = {id=505,en="Unbridled Wisdom",ja="N.ウィズドム",de="Ungezähmte Weisheit",fr="Sagesse irréfrénée",enl="Unbridled Wisdom",jal="N.ウィズドム",del="Ungezähmte Weisheit",frl="Sagesse irréfrénée"},
    [507] = {id=507,en="Grand Pas",ja="グランドパー",de="Kabinettstück",fr="Grand pas",enl="Grand Pas",jal="グランドパー",del="Kabinettstück",frl="Grand pas"},
    [508] = {id=508,en="Widened Compass",ja="ワイデンコンパス",de="Superkompass",fr="Compas élargi",enl="Widened Compass",jal="ワイデンコンパス",del="Superkompass",frl="Compas élargi"},
    [509] = {id=509,en="Odyllic Subterfuge",ja="オディリックサブタ",de="Ode an Od",fr="Subterfuge odique",enl="Odyllic Subterfuge",jal="オディリックサブタ",del="Ode an Od",frl="Subterfuge odique"},
    [510] = {id=510,en="Ergon Might",ja="エルゴンパワー",de="Ergonische Kraft",fr="Energie ergonique",enl="Ergon Might",jal="エルゴンパワー",del="Ergonische Kraft",frl="Energie ergonique"},
    [511] = {id=511,en="Reive Mark",ja="レイヴシンボル",de="Vorstoß-Abzeichen",fr="Marque de Raid",enl="Reive Mark",jal="レイヴシンボル",del="Vorstoß-Abzeichen",frl="Marque de Raid"},
    [512] = {id=512,en="Ionis",ja="イオニス",de="Ionis",fr="Ionis",enl="Ionis",jal="イオニス",del="Ionis",frl="Ionis"},
    [513] = {id=513,en="Bolster",ja="ボルスター",de="Augmentierung",fr="Géodynamisme",enl="bolstered",jal="ボルスター",del="Augmentierung",frl="Géodynamisme"},
    [515] = {id=515,en="Lasting Emanation",ja="エンデュアエマネイト",de="Aura der Genügsamkeit",fr="Emanation durable",enl="Lasting Emanation",jal="エンデュアエマネイト",del="Aura der Genügsamkeit",frl="Emanation durable"},
    [516] = {id=516,en="Ecliptic Attrition",ja="サークルエンリッチ",de="Vollkommener Kreis",fr="Renforcement sphérique",enl="Ecliptic Attrition",jal="サークルエンリッチ",del="Vollkommener Kreis",frl="Renforcement sphérique"},
    [517] = {id=517,en="Collimated Fervor",ja="コリメイトファーバー",de="Kollimativer Rausch",fr="Ferveur collimatée",enl="Collimated Fervor",jal="コリメイトファーバー",del="Kollimativer Rausch",frl="Ferveur collimatée"},
    [518] = {id=518,en="Dematerialize",ja="デマテリアライズ",de="Dematerialisation",fr="Dématérialisation",enl="Dematerialize",jal="デマテリアライズ",del="Dematerialisation",frl="Dématérialisation"},
    [519] = {id=519,en="Theurgic Focus",ja="タウマテルギフォカス",de="Thaumaturgischer Fokus",fr="Focalisation thaumaturgique",enl="Theurgic Focus",jal="タウマテルギフォカス",del="Thaumaturgischer Fokus",frl="Focalisation thaumaturgique"},
    [522] = {id=522,en="Elemental Sforzo",ja="Ｅ.スフォルツォ",de="Verzauberungs-Sforzo",fr="Sforzo élémentaire",enl="Elemental Sforzo",jal="Ｅ.スフォルツォ",del="Verzauberungs-Sforzo",frl="Sforzo élémentaire"},
    [523] = {id=523,en="Ignis",ja="イグニス",de="Ignis",fr="Ignis",enl="Ignis",jal="イグニス",del="Ignis",frl="Ignis"},
    [524] = {id=524,en="Gelus",ja="ゲールス",de="Gelus",fr="Gelus",enl="Gelus",jal="ゲールス",del="Gelus",frl="Gelus"},
    [525] = {id=525,en="Flabra",ja="フラブラ",de="Flabra",fr="Flabra",enl="Flabra",jal="フラブラ",del="Flabra",frl="Flabra"},
    [526] = {id=526,en="Tellus",ja="テッルス",de="Tellus",fr="Tellus",enl="Tellus",jal="テッルス",del="Tellus",frl="Tellus"},
    [527] = {id=527,en="Sulpor",ja="スルポール",de="Sulpor",fr="Sulpor",enl="Sulpor",jal="スルポール",del="Sulpor",frl="Sulpor"},
    [528] = {id=528,en="Unda",ja="ウンダ",de="Unda",fr="Unda",enl="Unda",jal="ウンダ",del="Unda",frl="Unda"},
    [529] = {id=529,en="Lux",ja="ルックス",de="Lux",fr="Lux",enl="Lux",jal="ルックス",del="Lux",frl="Lux"},
    [530] = {id=530,en="Tenebrae",ja="テネブレイ",de="Tenebrae",fr="Tenebrae",enl="Tenebrae",jal="テネブレイ",del="Tenebrae",frl="Tenebrae"},
    [531] = {id=531,en="Vallation",ja="ヴァレション",de="Wall",fr="Vallation",enl="Vallation",jal="ヴァレション",del="Wall",frl="Vallation"},
    [532] = {id=532,en="Swordplay",ja="ソードプレイ",de="Fechtkunst",fr="Jeu d'épée",enl="Swordplay",jal="ソードプレイ",del="Fechtkunst",frl="Jeu d'épée"},
    [533] = {id=533,en="Pflug",ja="フルーグ",de="Pflug",fr="Pflug",enl="Pflug",jal="フルーグ",del="Pflug",frl="Pflug"},
    [534] = {id=534,en="Embolden",ja="エンボルド",de="Ermutigung",fr="Affermissement",enl="emboldened",jal="エンボルド",del="Ermutigung",frl="Affermissement"},
    [535] = {id=535,en="Valiance",ja="ヴァリエンス",de="Kühnheit",fr="Valeur",enl="Valiance",jal="ヴァリエンス",del="Kühnheit",frl="Valeur"},
    [536] = {id=536,en="Gambit",ja="ガンビット",de="Gambit",fr="Gambit",enl="Gambit",jal="ガンビット",del="Gambit",frl="Gambit"},
    [537] = {id=537,en="Liement",ja="リエモン",de="Liemont",fr="Liement",enl="Liement",jal="リエモン",del="Liemont",frl="Liement"},
    [538] = {id=538,en="One for All",ja="ワンフォアオール",de="Einer für alle",fr="Un pour tous",enl="One for All",jal="ワンフォアオール",del="Einer für alle",frl="Un pour tous"},
    [539] = {id=539,en="Regen",ja="リジェネ",de="Regenerieren",fr="Récup",enl="regenerating",jal="リジェネ",del="Regenerieren",frl="Récup"},
    [540] = {id=540,en="poison",ja="ポイズン",de="Gift",fr="Poison",enl="poisoned",jal="ポイズン",del="Gift",frl="Poison"},
    [541] = {id=541,en="Refresh",ja="リフレシュ",de="Erfrischen",fr="Recharge",enl="refreshing",jal="リフレシュ",del="Erfrischen",frl="Recharge"},
    [542] = {id=542,en="STR Boost",ja="STRアップ",de="STR-Boost",fr="STR augmentée",enl="STR-boosted",jal="STRアップ",del="STR-Boost",frl="STR augmentée"},
    [543] = {id=543,en="DEX Boost",ja="DEXアップ",de="DEX-Boost",fr="DEX augmentée",enl="DEX-boosted",jal="DEXアップ",del="DEX-Boost",frl="DEX augmentée"},
    [544] = {id=544,en="VIT Boost",ja="VITアップ",de="VIT-Boost",fr="VIT augmentée",enl="VIT-boosted",jal="VITアップ",del="VIT-Boost",frl="VIT augmentée"},
    [545] = {id=545,en="AGI Boost",ja="AGIアップ",de="AGI-Boost",fr="AGI augmentée",enl="AGI-boosted",jal="AGIアップ",del="AGI-Boost",frl="AGI augmentée"},
    [546] = {id=546,en="INT Boost",ja="INTアップ",de="INT-Boost",fr="INT augmentée",enl="INT-boosted",jal="INTアップ",del="INT-Boost",frl="INT augmentée"},
    [547] = {id=547,en="MND Boost",ja="MNDアップ",de="MND-Boost",fr="MND augmenté",enl="MND-boosted",jal="MNDアップ",del="MND-Boost",frl="MND augmenté"},
    [548] = {id=548,en="CHR Boost",ja="CHRアップ",de="CHR-Boost",fr="CHR augmenté",enl="CHR-boosted",jal="CHRアップ",del="CHR-Boost",frl="CHR augmenté"},
    [549] = {id=549,en="Attack Boost",ja="攻撃力アップ",de="Attacken-Boost",fr="Attaque augmentée",enl="attack-boosted",jal="攻撃力アップ",del="Attacken-Boost",frl="Attaque augmentée"},
    [550] = {id=550,en="Defense Boost",ja="防御力アップ",de="Verteidigungs-Boost",fr="Défense augmentée",enl="defense-boosted",jal="防御力アップ",del="Verteidigungs-Boost",frl="Défense augmentée"},
    [551] = {id=551,en="Magic Atk. Boost",ja="魔法攻撃力アップ",de="Magieattacken-Boost",fr="Attq. magique augmentée",enl="Magic Atk. Boost",jal="魔法攻撃力アップ",del="Magieattacken-Boost",frl="Attq. magique augmentée"},
    [552] = {id=552,en="Magic Def. Boost",ja="魔法防御力アップ",de="Magieverteidigungs-Boost",fr="Déf. magique augmentée",enl="Magic Def. Boost",jal="魔法防御力アップ",del="Magieverteidigungs-Boost",frl="Déf. magique augmentée"},
    [553] = {id=553,en="Accuracy Boost",ja="命中率アップ",de="Präzisions-Boost",fr="Précision augmentée",enl="accuracy-boosted",jal="命中率アップ",del="Präzisions-Boost",frl="Précision augmentée"},
    [554] = {id=554,en="Evasion Boost",ja="回避率アップ",de="Ausweich-Boost",fr="Esquive augmentée",enl="evasion-boosted",jal="回避率アップ",del="Ausweich-Boost",frl="Esquive augmentée"},
    [555] = {id=555,en="Magic Acc. Boost",ja="魔法命中率アップ",de="Magiepräzisions-Boost",fr="Préc. magique augmentée",enl="Magic Acc. Boost",jal="魔法命中率アップ",del="Magiepräzisions-Boost",frl="Préc. magique augmentée"},
    [556] = {id=556,en="Magic Evasion Boost",ja="魔法回避率アップ",de="Magie-Ausweich-Boost",fr="Esq. magique augmentée",enl="Magic Evasion Boost",jal="魔法回避率アップ",del="Magie-Ausweich-Boost",frl="Esq. magique augmentée"},
    [557] = {id=557,en="Attack Down",ja="攻撃力ダウン",de="Attacken-Down",fr="Attaque réduite",enl="afflicted with Attack Down",jal="攻撃力ダウン",del="Attacken-Down",frl="Attaque réduite"},
    [558] = {id=558,en="Defense Down",ja="防御力ダウン",de="Verteidigungs-Down",fr="Défense réduite",enl="afflicted with Defense Down",jal="防御力ダウン",del="Verteidigungs-Down",frl="Défense réduite"},
    [559] = {id=559,en="Magic Atk. Down",ja="魔法攻撃力ダウン",de="Magieattacken-Down",fr="Attq. magique réduite",enl="afflicted with Magic Atk. Down",jal="魔法攻撃力ダウン",del="Magieattacken-Down",frl="Attq. magique réduite"},
    [560] = {id=560,en="Magic Def. Down",ja="魔法防御力ダウン",de="Magieverteidigungs-Down",fr="Déf. magique réduite",enl="afflicted with Magic Adef. Down",jal="魔法防御力ダウン",del="Magieverteidigungs-Down",frl="Déf. magique réduite"},
    [561] = {id=561,en="Accuracy Down",ja="命中率ダウン",de="Präzisions-Down",fr="Précision réduite",enl="afflicted with Accuracy Down",jal="命中率ダウン",del="Präzisions-Down",frl="Précision réduite"},
    [562] = {id=562,en="Evasion Down",ja="回避率ダウン",de="Ausweich-Down",fr="Esquive réduite",enl="afflicted with Evasion Down",jal="回避率ダウン",del="Ausweich-Down",frl="Esquive réduite"},
    [563] = {id=563,en="Magic Acc. Down",ja="魔法命中率ダウン",de="Magiepräzisions-Down",fr="Préc. magique réduite",enl="afflicted with Magic Acc. Down",jal="魔法命中率ダウン",del="Magiepräzisions-Down",frl="Préc. magique réduite"},
    [564] = {id=564,en="Magic Evasion Down",ja="魔法回避率ダウン",de="Magie-Ausweich-Down",fr="Esq magique réduite",enl="afflicted with Magic Evasion Down",jal="魔法回避率ダウン",del="Magie-Ausweich-Down",frl="Esq magique réduite"},
    [565] = {id=565,en="slow",ja="スロウ",de="Gemach",fr="Lenteur",enl="slowed",jal="スロウ",del="Gemach",frl="Lenteur"},
    [566] = {id=566,en="paralysis",ja="麻痺",de="Paralyse",fr="Paralysie",enl="paralyzed",jal="麻痺",del="Paralyse",frl="Paralysie"},
    [567] = {id=567,en="weight",ja="ヘヴィ",de="Gewicht",fr="Pesanteur",enl="weighed down",jal="ヘヴィ",del="Gewicht",frl="Pesanteur"},
    [568] = {id=568,en="Foil",ja="特殊攻撃回避率アップ",de="Traverse",fr="Esq. spéc. augmentée",enl="Foil",jal="特殊攻撃回避率アップ",del="Traverse",frl="Esq. spéc. augmentée"},
    [569] = {id=569,en="Blaze of Glory",ja="グローリーブレイズ",de="Glanz und Gloria",fr="Emportement géomantique",enl="Blaze of Glory",jal="グローリーブレイズ",del="Glanz und Gloria",frl="Emportement géomantique"},
    [570] = {id=570,en="Battuta",ja="バットゥタ",de="Battuta",fr="Battuta",enl="Battuta",jal="バットゥタ",del="Battuta",frl="Battuta"},
    [571] = {id=571,en="Rayke",ja="レイク",de="Rayke",fr="Rayke",enl="Rayke",jal="レイク",del="Rayke",frl="Rayke"},
    [572] = {id=572,en="Avoidance Down",ja="回避能力ダウン",de="Abwendung-Down",fr="Esquive affaiblie",enl="afflicted with Avoidance Down",jal="回避能力ダウン",del="Abwendung-Down",frl="Esquive affaiblie"},
    [573] = {id=573,en="Deluge Spikes",ja="アクアスパイク",de="Flutspitzen",fr="Pointes d'eau",enl="Deluge Spikes",jal="アクアスパイク",del="Flutspitzen",frl="Pointes d'eau"},
    [574] = {id=574,en="Fast Cast",ja="ファストキャスト",de="Schnellzauber",fr="Rapido-magie",enl="Fast Cast",jal="ファストキャスト",del="Schnellzauber",frl="Rapido-magie"},
    [575] = {id=575,en="gestation",ja="出現準備期間",de="Verwandlungsphase",fr="Gestation",enl="gestating",jal="出現準備期間",del="Verwandlungsphase",frl="Gestation"},
    [576] = {id=576,en="Doubt",ja="減退中",de="Entfremdung",fr="Abattement",enl="afflicted with Doubt",jal="減退中",del="Entfremdung",frl="Abattement"},
    [577] = {id=577,en="Cait Sith's Favor",ja="ケット・シーの加護",de="Cait Siths Schutz",fr="Egide de Cait Sith",enl="Cait Sith's Favor",jal="ケット・シーの加護",del="Cait Siths Schutz",frl="Egide de Cait Sith"},
    [578] = {id=578,en="Fishy Intuition",ja="釣り師のセンス",de="Angelsinn",fr="Instinct de pêcheur",enl="Fishy Intuition",jal="釣り師のセンス",del="Angelsinn",frl="Instinct de pêcheur"},
}, {"id", "en", "ja", "de", "fr", "enl", "jal", "del", "frl", "duration"}

--[[
Copyright © 2013-2014, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
