-- Dictionary of terms collected from the BG translate addon thread:
-- http://www.bluegartr.com/threads/123229-Translate-Addon

local dict = {
    {en="Normal",ja="ふつう"},
    {en="Normal",ja="普通"},
    {en="Difficult",ja="むず"},
    {en="Very Difficult",ja="とてもむず"},
    
    {en="Menace",ja="メナス"},
    {en="Voidwatch",ja="ヴォッチ"},
    {en="Burrows",ja="バローズ"},
    {en="Alluvion",ja="アルビオン"},
    {en="Ra'Kaznar Skirmish",ja="カザスカ"},
    {en="Ra'Kaznar Skirmish",ja="スカカザ"},
    {en="Ra'Kaznar Skirmish",ja="かざすか"},
    
    {en="Leveling",ja="レベリング"},
    {en="Aby",ja="アビ"},
    {en="Altepa",ja="アルテパ"},
    {en="Misareaux",ja="セア ミザレオ"},
    {en="Doll",ja="ド-ル"},
    
    {en="Recruiting",ja="募集"},
    {en="Check seacom for jobs",ja="サチコ参照ジョブを添えてテルください"},
    {en="Search Comment",ja="サチコ"},
    {en="Job doesn't matter",ja="ジョブ不問"},
    {en="currently",ja="現在"},
    
    
    {en="Hennetiel",ja="NTL"},
    {en="Morimar",ja="モリマ"},
    {en="Kamihr",ja="カミール"},
    {en="Marjami",ja="マリアミ"},
    {en="Rala",ja="ララ"},
    {en="Yorcia",ja="ヨル"},
    {en="Foret",ja="水林"},
    {en="Ceizak",ja="ケイザ"},
    {en="Cirdas",ja="シルダス"},
    
    {en="Trial by Fire",ja="火の試練"},
    {en="Trial by Lightning",ja="雷の試練"},
    {en="Trial by Earth",ja="土の試練"},
    {en="Trial by Water",ja="水の試練"},
    {en="Trial by Ice",ja="氷の試練"},
    {en="Trial by Wind",ja="風の試練"},
    {en="Leviathan",ja="リヴァイアサン"},
    {en="Levi",ja="リヴァ"},
    
    {en="Tenzen",ja="てんぜん"},
    {en="Tenzen",ja="テンゼン"},
    {en="Warrior's Path",ja="武士道とは"},
    
    {en="Return to Delkfutt's Tower",ja="デルクフの塔 再び"},
    {en="Return to Delkfutt's Tower",ja="テルクフの塔再び"},
    {en="Eald'narche",ja="エルド"},
    {en="Kam'lanaut",ja="カムラ"},
    {en="Stellar Fulcrum",ja="天輪"},
    {en="Celestial Nexus",ja="宿星"},
    
    {en="BRD",ja="吟"},
    {en="GEO",ja="風"},
    
    {en="Wanted (Battle)",ja="ウォンテッド"},
    {en="Dragonfly",ja="トンボ"},
    {en="Cost",ja="コスト"},
    
    {en="Incursion",ja="インカ"},
    {en="Tryl",ja="トリル"},
    
    {en="*waves*",ja="ノシ"},
    {en="Full Alliance",ja="フルアラ"},
    
    {en="EIN",ja="エイン"},
    {en="Ampuole",ja="アンプル"},
    
    -- These are from wiki.ffo.jp:
    {en="Hugemaw Harold",ja="ひゅーじまうへらるど"},
    {en="Bouncing Bertha",ja="ばうんしんぐばーさ"},
    {en="Prickly Pitriv",ja="ぷりっくりーぴとりう゛"},
    {en="Ironhorn Balduro",ja="あいあんほーんばるだーの"},
    {en="Sleepy Mabel",ja="すりーぴーめーぶる"},
    {en="Valkurm Imperiator",ja="ばるくるむいんぴらとあ"},
    {en="Serpopard Ninlil",ja="さーぽぱーどにんりる"},
    {en="Abyssdiver",ja="あびすだいばー"},
    {en="Intuila",ja="いんつりあ"},
    {en="Emperor Arthro",ja="えんぺらーあーすろ"},
    {en="Orcfeltrap",ja="おーくふぇるとらっぷ"},
    {en="Lumber Jill",ja="らんばーじる"},
    {en="Joyous Green",ja="じょいあすぐりーん"},
    {en="Strix",ja="すとりくす"},
    {en="Warblade Beak",ja="うぉーぶれいどびーく"},
    {en="Arke",ja="あるけ"},
    {en="Largantua",ja="らがんちゅあ"},
    {en="Largantua",ja="ラガンチュア"},
    {en="Beist",ja="ばいすと"},
    {en="Jester Malatrix",ja="じぇすたーまらとりくす"},
    {en="Cactrot Veloz",ja="かくとろっとべろす"},
    {en="Woodland Mender",ja="うっどらんどめんだー"},
    {en="Sybaritic Samantha",ja="しばりちっくさまんさ"},
    {en="Keeper of Heiligtum",ja="きーぱーおぶはいりぐたむ"},
    {en="Douma Weapon",ja="どうまうぇぽん"},
    {en="King Ugoprygid",ja="きんぐうるぴじっど"},
    {en="Vedrfolnir",ja="う゛ぇどるふぉるにる"},
    
    
    {en="Ark Angel",ja="あーくえんじぇる"},
    {en="Hume",ja="ひゅーむ"},
    {en="Tarutaru",ja="たるたる"},
    {en="Mithra",ja="みすら"},
    {en="Elvaan",ja="えるう゛ぁーん"},
    {en="Galka",ja="がるか"},
    {en="Eald'narche",ja="えるどなーしゅ"},
    {en="Kam'lanaut",ja="かむらなーと"},
    {en="Ouryu",ja="おうりゅう"},
    {en="Lancelord Gaheel Ja",ja="らんすろーど・がひーじゃ"},
    {en="Gessho",ja="げっしょー"},
    {en="Shadow Lord",ja="しゃどうろーど"},
    {en="Head Wind",ja="むかいかぜ"},
    {en="Shadow Lord Fight",ja="らんくごみっしょん"},
    {en="Legacy of the Lost",ja="ぼうこくのいさん"},
    {en="Legacy of the Lost",ja="亡国の遺産"},
    {en="Warrior's Path",ja="ぶしどうとは"},
    {en="Puppet in Peril",ja="少女の傀儡"},
    {en="Puppet in Peril",ja="しょうじょのくぐつ"},
    {en="Puppet in Peril",ja="しょうじょのかいらい"},
    {en="The Savage",ja="たけきものたちよ"},
    {en="The Savage",ja="猛き者たちよ"},
    {en="The Celestial Nexus",ja="しゅくせいのざ"},
    {en="The Celestial Nexus",ja="宿星の座"},
    {en="Return to Delfutt's Tower",ja="デルクフの塔再び"},
    {en="Divine Might",ja="しんい"},
    {en="Divine Might",ja="神威"},
    {en="Trial by Fire",ja="ひのしれん"},
    {en="Trial by Lightning",ja="かみなりのしれん"},
    {en="Trial by Earth",ja="つちのしれん"},
    {en="Trial by Water",ja="みずのしれん"},
    {en="Trial by Ice",ja="こおりのしれん"},
    {en="Trial by Wind",ja="かぜのしれん"},
    {en="Leviathan",ja="りう゛ぁいあさん"},
    {en="Ramuh",ja="らむう"},
    {en="Titan",ja="たいたん"},
    {en="Garuda",ja="がるーだ"},
    {en="Shiva",ja="しう゛ぁ"},
    {en="Ifrit",ja="いふりーと"},
    {en="Fenrir",ja="ふぇんりる"},
    {en="Carbuncle",ja="かーばんくる"},
    {en="Diabolos",ja="でぃあぼろす"},
    {en="Cait Sith",ja="けっとしー"},
    {en="Atomos",ja="あともす"},
    
    
    {en="Vagary",ja="ベガリ"},
    {en="Vagary",ja="ベガリーインスペクター"},
    {en="Balamor",ja="バラモア"},
    {en="Dhokmak",ja="ドクマク"},
    {en="Ashrakk",ja="アシュラック"},
    {en="Plouton",ja="上位 ハデス"},
    {en="Perfidien",ja="下位 ハデス"},
    {en="Plouton",ja="上位ハデス"},
    {en="Perfidien",ja="下位ハデス"},
    {en="Hades",ja="ハデス"},
    {en="upper",ja="上位"},
    {en="lower",ja="下位"},
    
    {en="Sinister Reign",ja="シニスターレイン"},
}

return dict