-------------------------------------------------------------------------------
-- Currencies -----------------------------------------------------------------
-------------------------------------------------------------------------------

Currencies = T {
    "Ordelle Bronzepiece",
    "Montiont Silverpiece",
    "One Byne Bill",
    "One Hundred Byne Bill",
    "Tukuku Whiteshell",
    "Lungo-Nango Jadeshell",
    "Forgotten Thought",
    "Forgotten Hope",
    "Forgotten Touch",
    "Forgotten Journey",
    "Forgotten Step"
}

-------------------------------------------------------------------------------
-- Granules -------------------------------------------------------------------
-------------------------------------------------------------------------------

Granules = T {
    "Crimson granules of time",
    "Azure granules of time",
    "Amber granules of time",
    "Alabaster granules of time",
    "Obsidian granules of time"
}

-------------------------------------------------------------------------------
-- Proc Types----- ------------------------------------------------------------
-------------------------------------------------------------------------------

proctype = {"ja", "magic", "ws", "random", "none"}

-------------------------------------------------------------------------------
-- Enemy Stagger Array based on time > stagger > name -------------------------
-------------------------------------------------------------------------------

staggers = T {}
staggers["morning"] = T {}
staggers["morning"]["ja"] = {
    "Kindred Thief",
    "Kindred Beastmaster",
    "Kindred Monk",
    "Kindred Ninja",
    "Kindred Ranger",
    "Duke Gomory",
    "Marquis Andras",
    "Marquis Gamygyn",
    "Count Raum",
    "Marquis Cimeries",
    "Marquis Caim",
    "Baron Avnas",
    "Hydra Thief",
    "Hydra Beastmaster",
    "Hydra Monk",
    "Hydra Ninja",
    "Hydra Ranger",
    "Vanguard Backstabber",
    "Vanguard Grappler",
    "Vanguard Hawker",
    "Vanguard Pillager",
    "Vanguard Predator",
    "Voidstreaker Butchnotch",
    "Steelshank Kratzvatz",
    "Vanguard Beasttender",
    "Vanguard Kusa",
    "Vanguard Mason",
    "Vanguard Militant",
    "Vanguard Purloiner",
    "Ko'Dho Cannonball",
    "Vanguard Assassin",
    "Vanguard Liberator",
    "Vanguard Ogresoother",
    "Vanguard Salvager",
    "Vanguard Sentinel",
    "Wuu Qoho the Razorclaw",
    "Tee Zaksa the Ceaseless",
    "Vanguard Ambusher",
    "Vanguard Hitman",
    "Vanguard Pathfinder",
    "Vanguard Pit",
    "Vanguard Welldigger",
    "Bandrix Rockjaw",
    "Lurklox Dhalmelneck",
    "Trailblix Goatmug",
    "Kikklix Longlegs",
    "Snypestix Eaglebeak",
    "Jabkix Pigeonpecs",
    "Blazox Boneybod",
    "Bootrix Jaggedelbow",
    "Mobpix Mucousmouth",
    "Prowlox Barrelbelly",
    "Slystix Megapeepers",
    "Feralox Honeylips",
    "Bordox Kittyback",
    "Droprix Granitepalms",
    "Routsix Rubbertendon",
    "Slinkix Trufflesniff",
    "Swypestix Tigershins",
    "Nightmare Crawler",
    "Nightmare Raven",
    "Nightmare Uragnite",
    "Nightmare Fly",
    "Nightmare Flytrap",
    "Nightmare Funguar",
    "Nightmare Gaylas",
    "Nightmare Kraken",
    "Nightmare Roc",
    "Nightmare Hornet",
    "Nightmare Bugard",
    "Woodnix Shrillwhistle",
    "Hamfist Gukhbuk",
    "Lyncean Juwgneg",
    "Va'Rhu Bodysnatcher",
    "Doo Peku the Fleetfoot",
    "Nant'ina",
    "Antaeus"
}

staggers["morning"]["magic"] = {
    "Kindred White Mage",
    "Kindred Bard",
    "Kindred Summoner",
    "Kindred Black Mage",
    "Kindred Red Mage",
    "Duke Berith",
    "Marquis Decarabia",
    "Prince Seere",
    "Marquis Orias",
    "Marquis Nebiros",
    "Duke Haures",
    "Hydra White Mage",
    "Hydra Bard",
    "Hydra Summoner",
    "Hydra Black Mage",
    "Hydra Red Mage",
    "Vanguard Amputator",
    "Vanguard Bugler",
    "Vanguard Dollmaster",
    "Vanguard Mesmerizer",
    "Vanguard Vexer",
    "Soulsender Fugbrag",
    "Reapertongue Gadgquok",
    "Battlechoir Gitchfotch",
    "Vanguard Constable",
    "Vanguard Minstrel",
    "Vanguard Protector",
    "Vanguard Thaumaturge",
    "Vanguard Undertaker",
    "Gi'Pha Manameister",
    "Gu'Nhi Noondozer",
    "Ra'Gho Darkfount",
    "Va'Zhe Pummelsong",
    "Vanguard Chanter",
    "Vanguard Oracle",
    "Vanguard Prelate",
    "Vanguard Priest",
    "Vanguard Visionary",
    "Loo Hepe the Eyepiercer",
    "Xoo Kaza the Solemn",
    "Haa Pevi the Stentorian",
    "Xuu Bhoqa the Enigma",
    "Fuu Tzapo the Blessed",
    "Naa Yixo the Stillrage",
    "Vanguard Alchemist",
    "Vanguard Enchanter",
    "Vanguard Maestro",
    "Vanguard Necromancer",
    "Vanguard Shaman",
    "Elixmix Hooknose",
    "Gabblox Magpietongue",
    "Hermitrix Toothrot",
    "Humnox Drumbelly",
    "Morgmox Moldnoggin",
    "Mortilox Wartpaws",
    "Distilix Stickytoes",
    "Jabbrox Grannyguise",
    "Quicktrix Hexhands",
    "Wilywox Tenderpalm",
    "Ascetox Ratgums",
    "Brewnix Bittypupils",
    "Gibberox Pimplebeak",
    "Morblox Stubthumbs",
    "Whistrix Toadthroat",
    "Nightmare Bunny",
    "Nightmare Eft",
    "Nightmare Mandragora",
    "Nightmare Hippogryph",
    "Nightmare Sabotender",
    "Nightmare Sheep",
    "Nightmare Snoll",
    "Nightmare Stirge",
    "Nightmare Weapon",
    "Nightmare Makara",
    "Nightmare Cluster",
    "Gosspix Blabblerlips",
    "Flamecaller Zoeqdoq",
    "Gi'Bhe Fleshfeaster",
    "Ree Nata the Melomanic",
    "Baa Dava the Bibliophage",
    "Aitvaras"
}

staggers["morning"]["ws"] = {
    "Kindred Paladin",
    "Kindred Warrior",
    "Kindred Samurai",
    "Kindred Dragoon",
    "Kindred Dark Knight",
    "Count Zaebos",
    "Duke Scox",
    "Marquis Sabnak",
    "King Zagan",
    "Count Haagenti",
    "Hydra Paladin",
    "Hydra Warrior",
    "Hydra Samurai",
    "Hydra Dragoon",
    "Hydra Dark Knight",
    "Vanguard Footsoldier",
    "Vanguard Gutslasher",
    "Vanguard Impaler",
    "Vanguard Neckchopper",
    "Vanguard Trooper",
    "Wyrmgnasher Bjakdek",
    "Bladerunner Rokgevok",
    "Bloodfist Voshgrosh",
    "Spellspear Djokvukk",
    "Vanguard Defender",
    "Vanguard Drakekeeper",
    "Vanguard Hatamoto",
    "Vanguard Vigilante",
    "Vanguard Vindicator",
    "Ze'Vho Fallsplitter",
    "Zo'Pha Forgesoul",
    "Bu'Bho Truesteel",
    "Vanguard Exemplar",
    "Vanguard Inciter",
    "Vanguard Partisan",
    "Vanguard Persecutor",
    "Vanguard Skirmisher",
    "Maa Febi the Steadfast",
    "Muu Febi the Steadfast",
    "Vanguard Armorer",
    "Vanguard Dragontamer",
    "Vanguard Ronin",
    "Vanguard Smithy",
    "Buffrix Eargone",
    "Cloktix Longnail",
    "Sparkspox Sweatbrow",
    "Ticktox Beadyeyes",
    "Tufflix Loglimbs",
    "Wyrmwix Snakespecs",
    "Karashix Swollenskull",
    "Smeltix Thickhide",
    "Wasabix Callusdigit",
    "Anvilix Sootwrists",
    "Scruffix Shaggychest",
    "Tymexox Ninefingers",
    "Scourquix Scaleskin",
    "Draklix Scalecrust",
    "Moltenox Stubthumbs",
    "Ruffbix Jumbolobes",
    "Shisox Widebrow",
    "Tocktix Thinlids",
    "Nightmare Crab",
    "Nightmare Dhalmel",
    "Nightmare Scorpion",
    "Nightmare Goobbue",
    "Nightmare Manticore",
    "Nightmare Treant",
    "Nightmare Diremite",
    "Nightmare Tiger",
    "Nightmare Raptor",
    "Nightmare Leech",
    "Nightmare Worm",
    "Shamblix Rottenheart",
    "Elvaansticker Bxafraff",
    "Qu'Pho Bloodspiller",
    "Te'Zha Ironclad",
    "Koo Rahi the Levinblade",
    "Barong",
    "Alklha",
    "Stihi",
    "Fairy Ring",
    "Stcemqestcint",
    "Stringes",
    "Suttung"
}

staggers["morning"]["random"] = {"Nightmare Taurus"}
staggers["morning"]["none"] = {
    "Animated Claymore",
    "Animated Dagger",
    "Animated Great Axe",
    "Animated Gun",
    "Animated Hammer",
    "Animated Horn",
    "Animated Kunai",
    "Animated Knuckles",
    "Animated Longbow",
    "Animated Longsword",
    "Animated Scythe",
    "Animated Shield",
    "Animated Spear",
    "Animated Staff",
    "Animated Tabar",
    "Animated Tachi",
    "Fire Pukis",
    "Petro Pukis",
    "Poison Pukis",
    "Wind Pukis",
    "Kindred's Vouivre",
    "Kindred's Wyvern",
    "Kindred's Avatar",
    "Vanguard Eye",
    "Prototype Eye",
    "Nebiros's Avatar",
    "Haagenti's Avatar",
    "Caim's Vouivre",
    "Andras's Vouivre",
    "Adamantking Effigy",
    "Avatar Icon",
    "Goblin Replica",
    "Serjeant Tombstone",
    "Zagan's Wyvern",
    "Hydra's Hound",
    "Hydra's Wyvern",
    "Hydra's Avatar",
    "Rearguard Eye",
    "Adamantking Effigy",
    "Adamantking Image",
    "Avatar Icon",
    "Avatar Idol",
    "Effigy Prototype",
    "Goblin Replica",
    "Goblin Statue",
    "Icon Prototype",
    "Manifest Icon",
    "Manifest Icon",
    "Prototype Eye",
    "Serjeant Tombstone",
    "Statue Prototype",
    "Tombstone Prototype",
    "Vanguard Eye",
    "Vanguard's Avatar",
    "Vanguard's Avatar",
    "Vanguard's Avatar",
    "Vanguard's Avatar",
    "Vanguard's Crow",
    "Vanguard's Hecteyes",
    "Vanguard's Scorpion",
    "Vanguard's Slime",
    "Vanguard's Wyvern",
    "Vanguard's Wyvern",
    "Vanguard's Wyvern",
    "Vanguard's Wyvern",
    "Warchief Tombstone"
}

staggers["day"] = T {}
staggers["day"]["ja"] = {
    "Kindred Thief",
    "Kindred Beastmaster",
    "Kindred Monk",
    "Kindred Ninja",
    "Kindred Ranger",
    "Duke Gomory",
    "Marquis Andras",
    "Marquis Gamygyn",
    "Count Raum",
    "Marquis Cimeries",
    "Marquis Caim",
    "Baron Avnas",
    "Hydra Thief",
    "Hydra Beastmaster",
    "Hydra Monk",
    "Hydra Ninja",
    "Hydra Ranger",
    "Vanguard Backstabber",
    "Vanguard Grappler",
    "Vanguard Hawker",
    "Vanguard Pillager",
    "Vanguard Predator",
    "Voidstreaker Butchnotch",
    "Steelshank Kratzvatz",
    "Vanguard Beasttender",
    "Vanguard Kusa",
    "Vanguard Mason",
    "Vanguard Militant",
    "Vanguard Purloiner",
    "Ko'Dho Cannonball",
    "Vanguard Assassin",
    "Vanguard Liberator",
    "Vanguard Ogresoother",
    "Vanguard Salvager",
    "Vanguard Sentinel",
    "Wuu Qoho the Razorclaw",
    "Tee Zaksa the Ceaseless",
    "Vanguard Ambusher",
    "Vanguard Hitman",
    "Vanguard Pathfinder",
    "Vanguard Pit",
    "Vanguard Welldigger",
    "Bandrix Rockjaw",
    "Lurklox Dhalmelneck",
    "Trailblix Goatmug",
    "Kikklix Longlegs",
    "Snypestix Eaglebeak",
    "Jabkix Pigeonpecs",
    "Blazox Boneybod",
    "Bootrix Jaggedelbow",
    "Mobpix Mucousmouth",
    "Prowlox Barrelbelly",
    "Slystix Megapeepers",
    "Feralox Honeylips",
    "Bordox Kittyback",
    "Droprix Granitepalms",
    "Routsix Rubbertendon",
    "Slinkix Trufflesniff",
    "Swypestix Tigershins",
    "Nightmare Bunny",
    "Nightmare Eft",
    "Nightmare Mandragora",
    "Nightmare Hippogryph",
    "Nightmare Sabotender",
    "Nightmare Sheep",
    "Nightmare Snoll",
    "Nightmare Stirge",
    "Nightmare Weapon",
    "Nightmare Makara",
    "Nightmare Cluster",
    "Woodnix Shrillwhistle",
    "Hamfist Gukhbuk",
    "Lyncean Juwgneg",
    "Va'Rhu Bodysnatcher",
    "Doo Peku the Fleetfoot",
    "Nant'ina",
    "Antaeus"
}

staggers["day"]["magic"] = {
    "Kindred White Mage",
    "Kindred Bard",
    "Kindred Summoner",
    "Kindred Black Mage",
    "Kindred Red Mage",
    "Duke Berith",
    "Marquis Decarabia",
    "Prince Seere",
    "Marquis Orias",
    "Marquis Nebiros",
    "Duke Haures",
    "Hydra White Mage",
    "Hydra Bard",
    "Hydra Summoner",
    "Hydra Black Mage",
    "Hydra Red Mage",
    "Vanguard Amputator",
    "Vanguard Bugler",
    "Vanguard Dollmaster",
    "Vanguard Mesmerizer",
    "Vanguard Vexer",
    "Soulsender Fugbrag",
    "Reapertongue Gadgquok",
    "Battlechoir Gitchfotch",
    "Vanguard Constable",
    "Vanguard Minstrel",
    "Vanguard Protector",
    "Vanguard Thaumaturge",
    "Vanguard Undertaker",
    "Gi'Pha Manameister",
    "Gu'Nhi Noondozer",
    "Ra'Gho Darkfount",
    "Va'Zhe Pummelsong",
    "Vanguard Chanter",
    "Vanguard Oracle",
    "Vanguard Prelate",
    "Vanguard Priest",
    "Vanguard Visionary",
    "Loo Hepe the Eyepiercer",
    "Xoo Kaza the Solemn",
    "Haa Pevi the Stentorian",
    "Xuu Bhoqa the Enigma",
    "Fuu Tzapo the Blessed",
    "Naa Yixo the Stillrage",
    "Vanguard Alchemist",
    "Vanguard Enchanter",
    "Vanguard Maestro",
    "Vanguard Necromancer",
    "Vanguard Shaman",
    "Elixmix Hooknose",
    "Gabblox Magpietongue",
    "Hermitrix Toothrot",
    "Humnox Drumbelly",
    "Morgmox Moldnoggin",
    "Mortilox Wartpaws",
    "Distilix Stickytoes",
    "Jabbrox Grannyguise",
    "Quicktrix Hexhands",
    "Wilywox Tenderpalm",
    "Ascetox Ratgums",
    "Brewnix Bittypupils",
    "Gibberox Pimplebeak",
    "Morblox Stubthumbs",
    "Whistrix Toadthroat",
    "Nightmare Crab",
    "Nightmare Dhalmel",
    "Nightmare Scorpion",
    "Nightmare Goobbue",
    "Nightmare Manticore",
    "Nightmare Treant",
    "Nightmare Diremite",
    "Nightmare Tiger",
    "Nightmare Raptor",
    "Nightmare Leech",
    "Nightmare Worm",
    "Gosspix Blabblerlips",
    "Flamecaller Zoeqdoq",
    "Gi'Bhe Fleshfeaster",
    "Ree Nata the Melomanic",
    "Baa Dava the Bibliophage",
    "Aitvaras"
}

staggers["day"]["ws"] = {
    "Kindred Paladin",
    "Kindred Warrior",
    "Kindred Samurai",
    "Kindred Dragoon",
    "Kindred Dark Knight",
    "Count Zaebos",
    "Duke Scox",
    "Marquis Sabnak",
    "King Zagan",
    "Count Haagenti",
    "Hydra Paladin",
    "Hydra Warrior",
    "Hydra Samurai",
    "Hydra Dragoon",
    "Hydra Dark Knight",
    "Vanguard Footsoldier",
    "Vanguard Gutslasher",
    "Vanguard Impaler",
    "Vanguard Neckchopper",
    "Vanguard Trooper",
    "Wyrmgnasher Bjakdek",
    "Bladerunner Rokgevok",
    "Bloodfist Voshgrosh",
    "Spellspear Djokvukk",
    "Vanguard Defender",
    "Vanguard Drakekeeper",
    "Vanguard Hatamoto",
    "Vanguard Vigilante",
    "Vanguard Vindicator",
    "Ze'Vho Fallsplitter",
    "Zo'Pha Forgesoul",
    "Bu'Bho Truesteel",
    "Vanguard Exemplar",
    "Vanguard Inciter",
    "Vanguard Partisan",
    "Vanguard Persecutor",
    "Vanguard Skirmisher",
    "Maa Febi the Steadfast",
    "Muu Febi the Steadfast",
    "Vanguard Armorer",
    "Vanguard Dragontamer",
    "Vanguard Ronin",
    "Vanguard Smithy",
    "Buffrix Eargone",
    "Cloktix Longnail",
    "Sparkspox Sweatbrow",
    "Ticktox Beadyeyes",
    "Tufflix Loglimbs",
    "Wyrmwix Snakespecs",
    "Karashix Swollenskull",
    "Smeltix Thickhide",
    "Wasabix Callusdigit",
    "Anvilix Sootwrists",
    "Scruffix Shaggychest",
    "Tymexox Ninefingers",
    "Scourquix Scaleskin",
    "Draklix Scalecrust",
    "Moltenox Stubthumbs",
    "Ruffbix Jumbolobes",
    "Shisox Widebrow",
    "Tocktix Thinlids",
    "Nightmare Crawler",
    "Nightmare Raven",
    "Nightmare Uragnite",
    "Nightmare Fly",
    "Nightmare Flytrap",
    "Nightmare Funguar",
    "Nightmare Gaylas",
    "Nightmare Kraken",
    "Nightmare Roc",
    "Nightmare Hornet",
    "Nightmare Bugard",
    "Shamblix Rottenheart",
    "Elvaansticker Bxafraff",
    "Qu'Pho Bloodspiller",
    "Te'Zha Ironclad",
    "Koo Rahi the Levinblade",
    "Barong",
    "Alklha",
    "Stihi",
    "Fairy Ring",
    "Stcemqestcint",
    "Stringes",
    "Suttung"
}

staggers["day"]["random"] = {"Nightmare Taurus"}
staggers["day"]["none"] = {
    "Animated Claymore",
    "Animated Dagger",
    "Animated Great Axe",
    "Animated Gun",
    "Animated Hammer",
    "Animated Horn",
    "Animated Kunai",
    "Animated Knuckles",
    "Animated Longbow",
    "Animated Longsword",
    "Animated Scythe",
    "Animated Shield",
    "Animated Spear",
    "Animated Staff",
    "Animated Tabar",
    "Animated Tachi",
    "Fire Pukis",
    "Petro Pukis",
    "Poison Pukis",
    "Wind Pukis",
    "Kindred's Vouivre",
    "Kindred's Wyvern",
    "Kindred's Avatar",
    "Vanguard Eye",
    "Prototype Eye",
    "Nebiros's Avatar",
    "Haagenti's Avatar",
    "Caim's Vouivre",
    "Andras's Vouivre",
    "Adamantking Effigy",
    "Avatar Icon",
    "Goblin Replica",
    "Serjeant Tombstone",
    "Zagan's Wyvern",
    "Hydra's Hound",
    "Hydra's Wyvern",
    "Hydra's Avatar",
    "Rearguard Eye",
    "Adamantking Effigy",
    "Adamantking Image",
    "Avatar Icon",
    "Avatar Idol",
    "Effigy Prototype",
    "Goblin Replica",
    "Goblin Statue",
    "Icon Prototype",
    "Manifest Icon",
    "Manifest Icon",
    "Prototype Eye",
    "Serjeant Tombstone",
    "Statue Prototype",
    "Tombstone Prototype",
    "Vanguard Eye",
    "Vanguard's Avatar",
    "Vanguard's Avatar",
    "Vanguard's Avatar",
    "Vanguard's Avatar",
    "Vanguard's Crow",
    "Vanguard's Hecteyes",
    "Vanguard's Scorpion",
    "Vanguard's Slime",
    "Vanguard's Wyvern",
    "Vanguard's Wyvern",
    "Vanguard's Wyvern",
    "Vanguard's Wyvern",
    "Warchief Tombstone"
}

staggers["night"] = T {}
staggers["night"]["ja"] = {
    "Kindred Thief",
    "Kindred Beastmaster",
    "Kindred Monk",
    "Kindred Ninja",
    "Kindred Ranger",
    "Duke Gomory",
    "Marquis Andras",
    "Marquis Gamygyn",
    "Count Raum",
    "Marquis Cimeries",
    "Marquis Caim",
    "Baron Avnas",
    "Hydra Thief",
    "Hydra Beastmaster",
    "Hydra Monk",
    "Hydra Ninja",
    "Hydra Ranger",
    "Vanguard Backstabber",
    "Vanguard Grappler",
    "Vanguard Hawker",
    "Vanguard Pillager",
    "Vanguard Predator",
    "Voidstreaker Butchnotch",
    "Steelshank Kratzvatz",
    "Vanguard Beasttender",
    "Vanguard Kusa",
    "Vanguard Mason",
    "Vanguard Militant",
    "Vanguard Purloiner",
    "Ko'Dho Cannonball",
    "Vanguard Assassin",
    "Vanguard Liberator",
    "Vanguard Ogresoother",
    "Vanguard Salvager",
    "Vanguard Sentinel",
    "Wuu Qoho the Razorclaw",
    "Tee Zaksa the Ceaseless",
    "Vanguard Ambusher",
    "Vanguard Hitman",
    "Vanguard Pathfinder",
    "Vanguard Pit",
    "Vanguard Welldigger",
    "Bandrix Rockjaw",
    "Lurklox Dhalmelneck",
    "Trailblix Goatmug",
    "Kikklix Longlegs",
    "Snypestix Eaglebeak",
    "Jabkix Pigeonpecs",
    "Blazox Boneybod",
    "Bootrix Jaggedelbow",
    "Mobpix Mucousmouth",
    "Prowlox Barrelbelly",
    "Slystix Megapeepers",
    "Feralox Honeylips",
    "Bordox Kittyback",
    "Droprix Granitepalms",
    "Routsix Rubbertendon",
    "Slinkix Trufflesniff",
    "Swypestix Tigershins",
    "Nightmare Crab",
    "Nightmare Dhalmel",
    "Nightmare Scorpion",
    "Nightmare Goobbue",
    "Nightmare Manticore",
    "Nightmare Treant",
    "Nightmare Diremite",
    "Nightmare Tiger",
    "Nightmare Raptor",
    "Nightmare Leech",
    "Nightmare Worm",
    "Woodnix Shrillwhistle",
    "Hamfist Gukhbuk",
    "Lyncean Juwgneg",
    "Va'Rhu Bodysnatcher",
    "Doo Peku the Fleetfoot",
    "Nant'ina",
    "Antaeus"
}

staggers["night"]["magic"] = {
    "Kindred White Mage",
    "Kindred Bard",
    "Kindred Summoner",
    "Kindred Black Mage",
    "Kindred Red Mage",
    "Duke Berith",
    "Marquis Decarabia",
    "Prince Seere",
    "Marquis Orias",
    "Marquis Nebiros",
    "Duke Haures",
    "Hydra White Mage",
    "Hydra Bard",
    "Hydra Summoner",
    "Hydra Black Mage",
    "Hydra Red Mage",
    "Vanguard Amputator",
    "Vanguard Bugler",
    "Vanguard Dollmaster",
    "Vanguard Mesmerizer",
    "Vanguard Vexer",
    "Soulsender Fugbrag",
    "Reapertongue Gadgquok",
    "Battlechoir Gitchfotch",
    "Vanguard Constable",
    "Vanguard Minstrel",
    "Vanguard Protector",
    "Vanguard Thaumaturge",
    "Vanguard Undertaker",
    "Gi'Pha Manameister",
    "Gu'Nhi Noondozer",
    "Ra'Gho Darkfount",
    "Va'Zhe Pummelsong",
    "Vanguard Chanter",
    "Vanguard Oracle",
    "Vanguard Prelate",
    "Vanguard Priest",
    "Vanguard Visionary",
    "Loo Hepe the Eyepiercer",
    "Xoo Kaza the Solemn",
    "Haa Pevi the Stentorian",
    "Xuu Bhoqa the Enigma",
    "Fuu Tzapo the Blessed",
    "Naa Yixo the Stillrage",
    "Vanguard Alchemist",
    "Vanguard Enchanter",
    "Vanguard Maestro",
    "Vanguard Necromancer",
    "Vanguard Shaman",
    "Elixmix Hooknose",
    "Gabblox Magpietongue",
    "Hermitrix Toothrot",
    "Humnox Drumbelly",
    "Morgmox Moldnoggin",
    "Mortilox Wartpaws",
    "Distilix Stickytoes",
    "Jabbrox Grannyguise",
    "Quicktrix Hexhands",
    "Wilywox Tenderpalm",
    "Ascetox Ratgums",
    "Brewnix Bittypupils",
    "Gibberox Pimplebeak",
    "Morblox Stubthumbs",
    "Whistrix Toadthroat",
    "Nightmare Crawler",
    "Nightmare Raven",
    "Nightmare Uragnite",
    "Nightmare Fly",
    "Nightmare Flytrap",
    "Nightmare Funguar",
    "Nightmare Gaylas",
    "Nightmare Kraken",
    "Nightmare Roc",
    "Nightmare Hornet",
    "Nightmare Bugard",
    "Gosspix Blabblerlips",
    "Flamecaller Zoeqdoq",
    "Gi'Bhe Fleshfeaster",
    "Ree Nata the Melomanic",
    "Baa Dava the Bibliophage",
    "Aitvaras"
}

staggers["night"]["ws"] = {
    "Kindred Paladin",
    "Kindred Warrior",
    "Kindred Samurai",
    "Kindred Dragoon",
    "Kindred Dark Knight",
    "Count Zaebos",
    "Duke Scox",
    "Marquis Sabnak",
    "King Zagan",
    "Count Haagenti",
    "Hydra Paladin",
    "Hydra Warrior",
    "Hydra Samurai",
    "Hydra Dragoon",
    "Hydra Dark Knight",
    "Vanguard Footsoldier",
    "Vanguard Gutslasher",
    "Vanguard Impaler",
    "Vanguard Neckchopper",
    "Vanguard Trooper",
    "Wyrmgnasher Bjakdek",
    "Bladerunner Rokgevok",
    "Bloodfist Voshgrosh",
    "Spellspear Djokvukk",
    "Vanguard Defender",
    "Vanguard Drakekeeper",
    "Vanguard Hatamoto",
    "Vanguard Vigilante",
    "Vanguard Vindicator",
    "Ze'Vho Fallsplitter",
    "Zo'Pha Forgesoul",
    "Bu'Bho Truesteel",
    "Vanguard Exemplar",
    "Vanguard Inciter",
    "Vanguard Partisan",
    "Vanguard Persecutor",
    "Vanguard Skirmisher",
    "Maa Febi the Steadfast",
    "Muu Febi the Steadfast",
    "Vanguard Armorer",
    "Vanguard Dragontamer",
    "Vanguard Ronin",
    "Vanguard Smithy",
    "Buffrix Eargone",
    "Cloktix Longnail",
    "Sparkspox Sweatbrow",
    "Ticktox Beadyeyes",
    "Tufflix Loglimbs",
    "Wyrmwix Snakespecs",
    "Karashix Swollenskull",
    "Smeltix Thickhide",
    "Wasabix Callusdigit",
    "Anvilix Sootwrists",
    "Scruffix Shaggychest",
    "Tymexox Ninefingers",
    "Scourquix Scaleskin",
    "Draklix Scalecrust",
    "Moltenox Stubthumbs",
    "Ruffbix Jumbolobes",
    "Shisox Widebrow",
    "Tocktix Thinlids",
    "Nightmare Bunny",
    "Nightmare Eft",
    "Nightmare Mandragora",
    "Nightmare Hippogryph",
    "Nightmare Sabotender",
    "Nightmare Sheep",
    "Nightmare Snoll",
    "Nightmare Stirge",
    "Nightmare Weapon",
    "Nightmare Makara",
    "Nightmare Cluster",
    "Shamblix Rottenheart",
    "Elvaansticker Bxafraff",
    "Qu'Pho Bloodspiller",
    "Te'Zha Ironclad",
    "Koo Rahi the Levinblade",
    "Barong",
    "Alklha",
    "Stihi",
    "Fairy Ring",
    "Stcemqestcint",
    "Stringes",
    "Suttung"
}
staggers["night"]["random"] = {"Nightmare Taurus"}
staggers["night"]["none"] = {
    "Animated Claymore",
    "Animated Dagger",
    "Animated Great Axe",
    "Animated Gun",
    "Animated Hammer",
    "Animated Horn",
    "Animated Kunai",
    "Animated Knuckles",
    "Animated Longbow",
    "Animated Longsword",
    "Animated Scythe",
    "Animated Shield",
    "Animated Spear",
    "Animated Staff",
    "Animated Tabar",
    "Animated Tachi",
    "Fire Pukis",
    "Petro Pukis",
    "Poison Pukis",
    "Wind Pukis",
    "Kindred's Vouivre",
    "Kindred's Wyvern",
    "Kindred's Avatar",
    "Vanguard Eye",
    "Prototype Eye",
    "Nebiros's Avatar",
    "Haagenti's Avatar",
    "Caim's Vouivre",
    "Andras's Vouivre",
    "Adamantking Effigy",
    "Avatar Icon",
    "Goblin Replica",
    "Serjeant Tombstone",
    "Zagan's Wyvern",
    "Hydra's Hound",
    "Hydra's Wyvern",
    "Hydra's Avatar",
    "Rearguard Eye",
    "Adamantking Effigy",
    "Adamantking Image",
    "Avatar Icon",
    "Avatar Idol",
    "Effigy Prototype",
    "Goblin Replica",
    "Goblin Statue",
    "Icon Prototype",
    "Manifest Icon",
    "Manifest Icon",
    "Prototype Eye",
    "Serjeant Tombstone",
    "Statue Prototype",
    "Tombstone Prototype",
    "Vanguard Eye",
    "Vanguard's Avatar",
    "Vanguard's Avatar",
    "Vanguard's Avatar",
    "Vanguard's Avatar",
    "Vanguard's Crow",
    "Vanguard's Hecteyes",
    "Vanguard's Scorpion",
    "Vanguard's Slime",
    "Vanguard's Wyvern",
    "Vanguard's Wyvern",
    "Vanguard's Wyvern",
    "Vanguard's Wyvern",
    "Warchief Tombstone"
}
